ESMValGroup/ESMValCore

- meta.yaml
- yamale_meta.yaml
This pull request
- adds the conda recipe to build yamale, created by @cehbrecht 
- fixes the name of the github repository in the esmvalcore conda recipe
> Add yamale conda recipe and minor fix in conda build

- esmvalcore/cmor/fix.py
- tests/unit/cmor/test_fix.py
Changed the behaviour to try to select the final cube using the `short_name`. In those cases, ESMValTool will print a couple of warnings detailing the cubes found and the risks of let this kind of errors slip
Should reduce the frustration when using new datasets and the need for fixes, even if fixes can be developed to remove those warnings completely
Replaces ESMValGroup/ESMValTool#1134
> Do not fail if we get multiple cubes from file

- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
Automatic composition of a unique alias for each dataset used by a diagnostic. Should help diagnostics developer, as it can be used as a dictionary key, plot label. Will also help with the compatibility of the diagnostics with different datasets and uses, i.e comparing different datasets or comparing different ensemble members of the same dataset can be done with the same code
Now it takes into account project, dataset, experiment, ensemble and version to compose the alias, but can be extended easily by adding keys to a tuple. Does not fail if any of those keys is missing.
If user adds a custom alias, it is respected but the dataset is taken into account for the purpose of getting the automatic for the others
See #164
> Automatic definition of alias

- doc/esmvalcore/preprocessor.rst
- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
This pull request adds support for 1hr, 3hr and 6hr frequencies in the regrid_time method of the preprocessor.
> add hourly support for regrid_time

- esmvalcore/cmor/_fixes/cmip5/ec_earth.py
- esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py
- esmvalcore/cmor/_fixes/cmip5/gfdl_cm3.py
- esmvalcore/cmor/_fixes/cmip5/gfdl_esm2m.py
- esmvalcore/cmor/_fixes/cmip5/miroc5.py
This adds fixes for tos (temperature ocean surface, sst) for a couple of cmip5 models.
One thing that surprised me was that our common
```
metadata = cube.metadata
do_something(cube)
cube.metadata = metadata
```
trope did not work for me when adding a scalar to a cube. I had to add a `deepcopy(metadata)` to avoid the loss of important metadata.
Maybe in these cases it is better to work on the data directly like
```
cube.data = cube.core_data() + 273.15
```
so?
> Add fixes for tos (sea surface temperature) for some cmip5 models

- .circleci/config.yml
- tests/integration/cmor/test_table.py
- tests/integration/test_diagnostic_run.py
- tests/integration/test_recipe.py
This will reduce the load on CircleCI, reducing waiting time for us.
> Only run installation test on CircleCI if unit tests succeed

- esmvalcore/config-developer.yml
This adds an OBS6 project, which is the composed of the CMIP6 CMOR table + custom tables.
This is needed for working with ERA5 data, because CMIP5 does not contain an hourly table.
Also, it would be good to start using this as the default for new CMORizers.
> Add observational data with CMIP6 CMOR table (OBS6) project

- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
A small pull request to improve the error message we get when we can not concatenate all cubes in one.
Instead of printing all the cubes definitions, now we just plot the concatenated cubes, adding the start and end time of each ones. This should help finding the offending cube(s), and the differences that prevent concatenating.
In order to be able to do that without performance penalties, I changed the call to `concatenate_cube` with a call to `concatenate` and check manually if we get just one cube. 
Example of the new output:
```
2019-09-04 10:11:09,084 UTC [3152] ERROR   Can not concatenate cubes into a single one.
2019-09-04 10:11:09,084 UTC [3152] ERROR   Resulting cubes:
2019-09-04 10:11:09,085 UTC [3152] ERROR   air_temperature / (K)               (time: 72; latitude: 256; …
```
> Better concatenation error message

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
Minor change to address the bug highlighted in #266. (The `multi_model_statistics` preprocessor still assumes that all cubes have latitude and longitude components and this PR hides the loading of `lats` and `lons` arrays behind an if statement.
> Development multi model statistics bugfix

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
When loading `sfcWind` with mip `day` for the model
```yaml
- {activity: HighResMIP, dataset: CMCC-CM2-HR4, project: CMIP6, exp: highresSST-present, grid: gn, ensemble: r1i1p1f1, start_year: 1950, end_year: 2014}
```
@sloosvel and @nperezzanon found that the first timestep was missing. After investigating, I found that it was due to an error in the `extract_time` function that this pull request fixes, along with a new test case to test it.
The error was using a strict `start < time` in the constraint. It works well for most cases because models usually assign times close the middle of the interval  and not at the edge, but this model was using 0:00 hours at all times
> Extract time failing to get 0:00 hours of first day

- esmvalcore/_config.py
- esmvalcore/cmor/table.py
- tests/integration/test_recipe.py
> Retrieve properly the activity for exps linked to multiple ids 

- esmvalcore/cmor/_fixes/cmip5/ec_earth.py
- tests/integration/cmor/_fixes/cmip5/test_ec_earth.py
* In the ETH repository we have some older EC-EARTH files that do not include the height coordinate. This fixes the problem for tas.
* Also some files included `long_name` for time while some did not.
* Only applies the fixes if `height`/ `long_name` is missing.
@ruthlorenz
> fix ec_earth: missing_height

- esmvalcore/cmor/tables/custom/CMOR_xco2.dat
Changes the cmor table units from 1e-6 (ppm) to 1.
Cmorized data have been regenerated accordingly.
> Fix XCO2 units (custom table)

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
After several issues with the parent_time_unit format (#194, #209) due to #108 , the checker now considers the non-conversion of the time attributes if there is no parent experiment.   If there is a parent experiment but the format of the parent_time_unit cannot be read, an error message appears.
I tried fixing the no parent case as suggested in [here]( https://github.com/ESMValGroup/ESMValCore/pull/194#issuecomment-518556998) , but maybe this solution is simpler.
> Check parent_time_unit format

- esmvalcore/_recipe.py
> Find various fx files for OBS projects for preprocessor masking

- esmvalcore/preprocessor/_derive/lwp.py
Updates the variable derivation script lwp.py to allow for processing of CMIP6 data:
- CMIP6 cubes cannot be extracted with constraint "name" because of differences in the name between CMIP5 and CMIP5 --> using variable name instead (function _var_name_constraint from _shared.py)
- attribute "project_id" does not exist in CMIP6 --> using attribute "mip_era" in case of CMIP6 data
- attribute "model_id" is defined differently in CMIP5 and CMIP5 --> using attribute "source_id" in case of CMIP6
- added CMIP6 models that provide lwp only instead of lwp+iwp for variable clwvi to list of "bad" models
> CMIP6 updates for variable derivation (lwp)

- esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
- esmvalcore/cmor/_fixes/shared.py
This pull request fixes incomplete GFDL-CM4 metadata for variables uas, vas and tas, by adding the scalar coordinate "height".
Script [shared.py](esmvalcore/cmor/_fixes/shared.py) has been changed accordingly, and the new file [gfdl_cm4.py](esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py) has been created.
> Add fixes to near-surface uas, vas and tas metadata

- esmvalcore/config-developer.yml
- tests/integration/cmor/test_read_cmor_tables.py
- tests/integration/cmor/test_table.py
As requested by @axel-lauer  in ESMValGroup/ESMValTool#1011, 'obs4mips' is no longer cmor strict, as some of the error variables provided are not part of the tables
> Make obs4mips not cmor strict

- esmvalcore/_task.py
I am using Ubuntu running on the WSL to run ESMValTool. It works mostly fine, but the resource logger was failing because the `io_counters` are not available.
I adapted the code to work even if they are not available and now it works well
It is not real Windows support, but at least it will be easier for Windows users to run ESMValTool
> Support Windows Subsystem for Linux

- esmvalcore/cmor/_fixes/cmip5/cesm1_bgc.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_bgc.py
Add fix for `gpp` of `CESM1-BGC`.
-   [x] Circle/CI tests pass. Status can …
> Added fix for GPP of CESM1-BGC

- esmvalcore/cmor/tables/custom/CMOR_alb.dat
- esmvalcore/preprocessor/_derive/alb.py
- tests/integration/preprocessor/_derive/test_interface.py
This PR changes calculation of the derived variable "alb" (surface albedo) from using all-sky fluxes to clear-sky fluxes. This method should be a bit closer to how surface albedo is calculated from satellite data.
> changed surface albedo calculation from all-sky to clear-sky

- esmvalcore/preprocessor/_mapping.py
- esmvalcore/preprocessor/_regrid_esmpy.py
- tests/unit/preprocessor/_mapping/test_mapping.py
- tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
I added a regrid from irregular grid to another irregular grid (from the U points to the T points in NEMO terms) in the computation of the ocean heat transport derived variable.
It worked well but for some auxiliary coordinates that were not added to the new cube. this pull request fix this
> Fix regrid

- environment.yml
- meta.yaml
Bunch of packages from our environment are not yet able to deal with `python=3.8` that gets picked up automatically by an `env update` or `update all` (eg `numba` and possible a bunch more). Can we get this in asap, please :beer:
> pinned python lower than 3.8

- esmvalcore/preprocessor/_mask.py
> Generalized shapefile mask to account for possible multiple regions

- esmvalcore/_recipe.py
someone whose name starts with B and is Dutch pulled a Dutch one on the fx variables that actually have `start_` and `end_time`:grin: Closes https://github.com/ESMValGroup/ESMValTool/issues/1469
> run extract time only on non fx variables

- esmvalcore/preprocessor/__init__.py
This PR replaces the deprecated `getargspec` in `check_preprocessor_settings.py` to the new python3 compatible `getfullargspec`.
**Tasks**
-   [x] ~Add unit tests~
-   [x] ~Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line …
> Update deprecated getargspec in check_preprocessor_settings.py

- esmvalcore/cmor/table.py
Fixes #316 and superseeds #334 ()
> Use abspath as default for cmor  table location

- esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
There is a typo in the MIROC-ESM fix, which is corrected in this pull request. Previously this somehow worked, but iris 2.3 appears to be more strict.
**Tasks**
* * *
> Fix typo in MIROC-ESM fix

- esmvalcore/_recipe.py
A very small change that will be handy for CMIP6: when using the `--max-datasets` option, log the full `alias` of each one instead of just the `dataset` parameter. 
Why? Well, I limited a CMIP6 recipe that was trying to use all members available from all models and the log I got was like this:
```
Only considering MODEL1, MODEL1, MODEL1, MODEL1, MODEL1 
```
With the new change it will be something like this
```
Only considering MODEL1_r1i1p1f1, MODEL1_r2i1p1f1, MODEL1_r3i1p1f1, MODEL1_r4i1p1f1, MODEL1_r5i1p1f1 
```
> Use alias instead of dataset in max datasets log

- esmvalcore/cmor/table.py
Closes #412
**Tasks**
-   Add unit tests
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, …
> Consistently use dimension/coordinate names in VariableInfo.coordinates

- doc/esmvalcore/preprocessor.rst
- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
merging #351 missed a whole lot of refs  that I re-added here
A good example not to trust 100% gitHub when it tells you able to merge and do a `git merge master` in the branch before; that was an old PR that was initially pointing to `development` and the able to merge message has not been redirected towards `master` @mattiarighi can you pls approve so we can fix the `master` (currently the tests are failing there)
> Fix missing refs after 351 merge

- doc/esmvalcore/preprocessor.rst
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_area.py
In Table 1 of the paper, we mention `zonal_statistics` and `meridional_statistics`, but in the preprocessor this is called `zonal_means` and covers both the zonal (longitude stats) and the meridional (latitude stats) case.
This PR attempts to quickly solve the problem.
`recipe_flato13ipcc.yml` and `recipe_collins13ipcc.yml` should be adjusted accordingly.
Closes #24.
> [URGENT] Rename zonal_means to zonal_statistics

- esmvalcore/_config.py
- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
**Tasks**
-   [x] Circle/CI tests pass. Status can be seen below your pull …
> Allowed arbitrary CMIP6 fx variables in special preprocessors and added a catch on project not found in config-developer (invalid project)

- esmvalcore/_main.py
**Tasks**
(https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue …
> Remove log message about reference file

- esmvalcore/_task.py
In the last few days I had to look several time in the resource logger for the maximum consumed memory. It is tedious.
I modified a bit the resource logger so it prints at the end that value in the main log, to make getting this value easier for all. 
I am not very happy with the implementation, so any suggestion on how to improve it is even more welcome than usual
> Log max memory used by the recipe in the main log

- CITATION.cff
- esmvalcore/_version.py
- meta.yaml
Because I forgot to do this before making the v2.0.0b4 release.
I will make another release after this is merged.
> Increase version to v2.0.0b5

- esmvalcore/_task.py
Fix mistake in error message introduced in #385.
> Fix mistake in error message for diagnostic scripts that are not executable

- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_mapping.py
- esmvalcore/preprocessor/_regrid.py
- setup.cfg
- setup.py
- tests/__init__.py
- tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2g.py
- tests/integration/cmor/_fixes/cmip6/test_ipsl_cm6a_lr.py
- tests/integration/preprocessor/_io/test_load.py
- tests/integration/test_recipe.py
- tests/unit/cmor/test_fix.py
- tests/unit/preprocessor/_derive/test_uajet.py
- tests/unit/preprocessor/_mapping/test_mapping.py
- tests/unit/preprocessor/_regrid/test__stock_cube.py
- tests/unit/preprocessor/_regrid/test_extract_levels.py
- tests/unit/preprocessor/_regrid/test_regrid.py
- tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
- tests/unit/preprocessor/_time/test_time.py
- tests/unit/preprocessor/_units/test_convert_units.py
- tests/unit/preprocessor/_weighting/test_weighting_landsea_fraction.py
This pull request
- Removes no longer required test dependencies, that currently break the tests on CirclCI in the `master` branch
- Fixes a lot of warnings
> Clean up unit tests and fix warnings

- .zenodo.json
- CITATION.cff
Let's see if it works.
I found the instructions here: https://developers.zenodo.org/#representation
This pull request also puts the core development team at the top of the list.
> Try to add is-enes3 community and is-enes3 grant to zenodo and update authors

- esmvalcore/preprocessor/_derive/sithick.py
- tests/integration/preprocessor/_derive/test_sithick.py
Fixed a couple of issues in sithick derivation
-   [x ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is sufficient.
-   [x] Circle/CI tests …
> Fix sithick derivation when units of siconc are %

- esmvalcore/preprocessor/_derive/sispeed.py
- tests/integration/preprocessor/_derive/test_sispeed.py
Adding regrid to sispeed derivation
-   [x] Circle/CI tests pass. Status …
> Add regrid to sispeed derivation when siu and siv are not in the same grid

- esmvalcore/cmor/_fixes/cmip5/hadgem2_es.py
Checks whether latitude bounds are present before trying to limit their range to -90...+90. In some cases, latitude bounds are missing causing this fix to crash without such an additional check.
> minor bugfix in CMOR fix for CMIP5 model HadGEM2-ES

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
Since #166 was merged, the tool is generating lots of warnings because it's trying to automatically add bounds to coordinates that do not need them. This pull request changes the behaviour so we only try to guess bounds when they are required by the CMOR table.
**Tasks**
* * *
> Do not try to guess or warn about missing bounds when there shouldn't be any

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
The error message when trying to use `extract_time` on a cube which does not contain data for that time was not correct. This pull request fixes that.
**Tasks**
> Better error message when cube does not contain requested time

- esmvalcore/_recipe.py
Automatic attribute where 'alias' and 'dataset' name are the same.
Could be overwritten with a specific custom alias.
**Tasks**
* * *
Closes {#486}
> Include alias in MultiModel attributes

- esmvalcore/_recipe_checks.py
- esmvalcore/preprocessor/__init__.py
> Moved and completed time preprocessors list (PR 439 child 1)

- doc/esmvalcore/preprocessor.rst
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_regrid.py
- tests/integration/preprocessor/_regrid/test_extract_point.py
- tests/unit/preprocessor/_regrid/test_extract_point.py
This add a simple point extraction function the preprocessor, with interpolation. It uses `iris.cube.Cube.interpolate` under the hood.
**Tasks**
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/api/esmvalcore.html). For all other functions a one line docstring is …
> Add preprocessor extract_point function

- esmvalcore/cmor/_fixes/shared.py
- tests/integration/cmor/_fixes/test_shared.py
Coordinates that require different rounding values, can be given as a
list of strings. The default of `None` will round all dimension
coordinates, following the old behaviour.
Note that this functionality is used in a fix for a dataset (different pull request); instead of writing a completely new function, it was easier to adjust this one.
----
**Tasks**
-   [x] Public functions should have a …
> Add option to round only specified coordinates

- doc/esmvalcore/recipe.rst
Added documentation to avoid using leading 0s to specify years in recipe.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocess …
> Added documentation to avoid using leading 0s to specify years in recipe

- .circleci/config.yml
- .circleci/install_triggers
- setup.cfg
This pull request tries to make the tests we run on CircleCI more relevant.
- With these changes, CircleCI will only run tests that require installation/conda build for the master branch or when there are changes to the relevant files (meta.yaml, environment.yml, setup.py or the CircleCI configuration itself).
- Do not print the test coverage after every test run, this will make the output less cluttered.
> Run more relevant tests on CircleCI

- esmvalcore/_recipe.py
Hi @valeriupredoi, this is more the kind of refactoring I had in mind. I think it is clearer and more easily extensible for future preprocessors. It's left to also unify `_update_fx_settings_mask` and `_update_fx_settings_stats`, which should be possible if one untangles the 6 levels of indentation in the stats method, but at the moment I am out of time.
> Pr439 child2 main functionality klaus suggestion

- meta.yaml
@bouweandela any reason you kept the pin in `meta.yml`? Anyways, I tested the unpinning and all works fine :beer:
> Unpin on Python<3.8 for conda package

- esmvalcore/_task.py
Terminate the task worker pool if an exception occurs instead of waiting for garbage collection. This will probably solve #531.
**Tasks**
> Immediately stop all tasks on error

- esmvalcore/cmor/_fixes/cmip5/fgoals_g2.py
- esmvalcore/cmor/_fixes/cmip5/noresm1_me.py
- tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
Provides small fixes for two CMIP5 datasets.
This relies on #476 . The relevant commit is included in this PR to let unit tests pass, but this PR should preferably not be merged before that one has been merged, and this PR is then updated.
----
**Tasks**
(https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
-   [x] Circle/CI tests pass. Status can be …
> Fix CMIP5  FGOALS-g2 and NorESM1-ME coordinates

- CITATION.cff
- esmvalcore/_version.py
- meta.yaml
A new release and conda package will be required after #528 is merged.
> Increase version to v2.0.0b7

- tests/unit/data_finder/test_get_start_end_year.py
Motivated by transient test fails due to random combinations that look like dates as @bouweandela explains in https://github.com/ESMValGroup/ESMValCore/pull/530#issuecomment-593466236
> Test get start end year replace with tmp_dir/test.nc so no fluke dates can be found in temporary file name

- esmvalcore/_task.py
Fix bug that made diagnostics with diagnostics as ancestors fail
**Tasks**
* * *
Closes #554
> Fix bug that made diagnostics with diagnostics as ancestors fail

- esmvalcore/cmor/_fixes/cmip5/miroc5.py
- tests/integration/cmor/_fixes/cmip5/test_miroc5.py
This PR adds a fix for `hur` of MIROC5.
**Tasks**
-   [x] Circle/CI tests …
> Added fix for hur of MIROC5

- esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1.py
- esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1_m.py
- esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
- esmvalcore/cmor/_fixes/cmip6/bcc_esm1.py
- tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
- tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1_m.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py
This PR adds fixes for `tos` of the CMIP6 BCC models
**Tasks**
-   [x] …
> Added fixes for tos of BCC models

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
This PR adds several fixes for `cl`, `cli` and `clw` for the CESM2 models.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preproces …
> Added fixes for CESM2 models

- esmvalcore/cmor/_fixes/cmip5/ccsm4.py
- tests/integration/cmor/_fixes/cmip5/test_ccsm4.py
> Fix mask in land variables for CCSM4 (fixes #578)

- esmvalcore/preprocessor/_area.py
> Cast dtype float32 to output from zonal and meridional area preprocessors

- esmvalcore/cmor/_fixes/cmip5/cesm1_bgc.py
- esmvalcore/cmor/tables/custom/CMOR_co2s.dat
- esmvalcore/preprocessor/_derive/co2s.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_bgc.py
- tests/integration/cmor/_fixes/test_fix.py
- tests/unit/preprocessor/_derive/test_co2s.py
This PR adds the derivation script for `co2s` (CO2 mole fraction at surface level). It can be tested with this sample recipe:
```yaml
---
documentation:
description: |
Test.
authors:
- schlund_manuel
maintainer:
- schlund_manuel
projects:
- crescendo
DATASET_ANCHOR: &datasets
- {dataset: BNU-ESM}
- {dataset: CanESM2}
- {dataset: CESM1-BGC}
- {dataset: GFDL-ESM2G}
- {dataset: GFDL-ESM2M}
- {dataset: MIROC-ESM}
- {dataset: NorESM1-ME}
diagnostics:
test:
variables:
co2s:
project: CMIP5
exp: esmHistorical
ensemble: r1i1p1
mip: Amon
additional_datasets: *datasets
start_year: 1950
end_year: 1955
derive: true
scripts:
null
```
Please note that using `core_data()` instead of `data` [here](https://github.com/ESMValGroup/ESMValCore/blob/dede748b065741e76590982ca0e1c5e5b94a7a40/esmvalcore/preprocesso …
> Added derivation script for co2s

- esmvalcore/cmor/tables/custom/CMOR_co2s.dat
- esmvalcore/preprocessor/_derive/co2s.py
- tests/unit/preprocessor/_derive/test_co2s.py
This PR fixes the custom `co2s` table to match its CMIP6 version as discussed in #587.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalco …
> Adapted custom co2s table to match CMIP6 version

- esmvalcore/_recipe.py
- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
Implemented for two special cases (hybrid height coordinate and hybrid pressure coordinate), can easily be expanded to more cases.
**Tasks** …
> Implemented concatenation of cubes with derived coordinates

- esmvalcore/preprocessor/_derive/co2s.py
- tests/unit/preprocessor/_derive/test_co2s.py
This PR fixes an error in the derivation script of `co2s`.  In order to represent the true CO2 mole fraction at surface, it is necessary to interpolate the data on the surface air pressure. A recipe to test these changes can be found in #587.
**Tasks**
- …
> Fixed derivation of co2s

- doc/requirements.txt
The documentation test has been broken since https://github.com/ESMValGroup/ESMValCore/pull/562 was merged. This pull request fixes it by adding `pandas` to the list of packages that readthedocs needs to install.
**Tasks**
> Add pandas as a requirement for building the documentation

- .circleci/config.yml
- doc/contributing.rst
- package/meta.yaml
When creating a conda package, all files that are in the same directory as meta.yaml are copied into the package. This resulted in very large conda packages. By moving meta.yaml to it's own directory, we can create much smaller conda packages. I already used that to build the past few conda packages, but this pull request actually implements that.
**Tasks**
> Reduce the size of conda package

- tests/integration/test_diagnostic_run.py
> make ncl or R tests not fail if package not installed

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/iris_helpers.py
- esmvalcore/preprocessor/_derive/_shared.py
- esmvalcore/preprocessor/_derive/alb.py
- esmvalcore/preprocessor/_derive/lwp.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/cmor/_fixes/test_shared.py
- tests/unit/test_iris_helpers.py
This PR extends the fixes for `cl`, `cli` and `clw` for the CESM2 models (the original fix only flips the vertical coords, but not the data itself).
I also had to move the function `var_name_constraint` to a new module (`iris_helpers`) because of circular dependencies in `esmvaltool.cmor._fixes.shared` and `esmvaltool.preprocessor.shared`. I'm happy to rename that module if anybody knows a better name.
**Tasks**
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API …
> Extended fix for cl-like variables of CESM2 models

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
Added several operators to the multimodel, as requested by @mwjury 
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.htm …
> Add max, min and std operators to multimodel

- esmvalcore/config-user.yml
**Tasks**
* * *
Closes https://github.com/ESMValGroup/ESMValTool/issues/1622
> Config file populated with site-specific data paths examples

- README.md
The Codacy badges were broken after the update of the Codacy project. This pull request fixes the links.
> Update Codacy badges

- esmvalcore/cmor/_fixes/native6/era5.py
- tests/integration/cmor/_fixes/native6/test_era5.py
**Tasks**
If you need help with any of the tasks above, please …
> Added fix to convert "geopotential" to "geopotential height" for ERA5

- esmvalcore/preprocessor/_area.py
- esmvalcore/preprocessor/_download.py
- esmvalcore/preprocessor/_mask.py
- setup.py
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/preprocessor/_derive/test_sispeed.py
- tests/integration/test_recipe.py
Unpin flake8, so we can use the latest version.
**Tasks**
> Unpin flake8

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_cycles.py
- tests/unit/preprocessor/_cycles/test_cycles.py
This PR adds a preprocessor to calculate peak-to-peak amplitude of data aggregated over specified coordinates.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmva …
> Added preprocessor to extract amplitude of cycles

- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
> Overhaul concatenation and allow for correct concatenation of multiple overlapping datasets

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
**Tasks**
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to find out …
> Do not fix longitude values if they are too far from valid range

- esmvalcore/preprocessor/_volume.py
- tests/unit/preprocessor/_volume/test_volume.py
> Change volume stats to handle and output masked array result

- esmvalcore/preprocessor/_mask.py
- tests/__init__.py
- tests/integration/preprocessor/_mask/test_mask.py
> Fix mask fx dict handling not to fail if empty list in values

- esmvalcore/preprocessor/_area.py
- tests/unit/preprocessor/_area/test_area.py
> area_weights for cordex in area_statistics

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
> Preserve metadata during anomalies computation when using iris cubes difference

- esmvalcore/_task.py
- tests/unit/task/test_diagnostic_task.py
**Tasks**
If you need help with any of the tasks above, please …
> Try to use the same python for running diagnostics as for esmvaltool

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- doc/conf.py
- doc/contributing.rst
- doc/develop/fixing_data.rst
- esmvalcore/_main.py
Changed references to documentation from esmvaltool.readthedocs.io to docs.esmvaltool.org. This closes https://github.com/ESMValGroup/ESMValCore/issues/315.
> Updated references to documentation (now docs.esmvaltool.org)

- esmvalcore/cmor/_fixes/cmip5/access1_0.py
- esmvalcore/cmor/_fixes/cmip5/access1_3.py
- tests/integration/cmor/_fixes/cmip5/test_access1_0.py
- tests/integration/cmor/_fixes/cmip5/test_access1_3.py
The access1 datasets have time units `Unit('days since 0001-01-01', calendar='proleptic_gregorian')`. The existing fix only changes the calendar, but that results in a wrong interpretation of the time points, where the days are offset by ~2 days. This PR changes the time offset first to 'days since 1850-01-01', using `convert_units` to make sure that time points are updated as well. For the recent period (after 1582 or so), both calendars should be the same, and hence the calendar can now safely be changed to 'gregorian'.
**Tasks**
- …
> Solve bug in ACCESS1 dataset fix for calendar. 

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
> Make multimodel work correctly with yearly data

- doc/recipe/overview.rst
- esmvalcore/_recipe.py
- tests/unit/test_recipe.py
> Fix the syntax for adding multiple ensemble members from the same dataset

- esmvalcore/cmor/table.py
-   [x] Circle/CI tests pass. Status can be seen below your pull request. …
> Fix bug that made preprocessor with fx files fail in rare cases

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
To solve the issue raised by @ledm in ESMValGroup/ESMValTool#1621
**Tasks** …
> Add support for string coordinates

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
> Optimize time weights in time preprocessor for climate statistics

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
This PR fixes the the bug in the calculation of the time weights introduced by #684. I know that this implementation does not use `dask` anymore, but unfortunately [`iris.util.broadcast_to_shape`](https://scitools.org.uk/iris/docs/latest/iris/iris/util.html#iris.util.broadcast_to_shape) does not support `dask`.
This needs to be included for `v2.0.0`.
**Tasks**
-   [x] Public functions should have a numpy-style docstring so they appear properly in the [API …
> Fixed bug in time weights calculation

- setup.py
The unit tests on CircleCI are failing with pytest==6.0.0rc1, so avoid that version.
**Tasks**
> Avoid pytest version that crashes

- doc/quickstart/find_data.rst
- doc/recipe/overview.rst
- doc/recipe/preprocessor.rst
A few documentation suggestions, mentioned in:
[Issue #1684](https://github.com/ESMValGroup/ESMValTool/issues/1684)
Closes ESMValGroup/ESMValTool#1684
> Suggested Documentation changes

- esmvalcore/_task.py
> Produce a readable warning if ancestors are a string instead of a list.

- doc/api/esmvalcore.cmor.rst
- esmvalcore/cmor/__init__.py
- esmvalcore/cmor/fixes.py
- tests/unit/cmor/test_fixes.py
Added `add_plev_from_altitude` and `add_sigma_factory` to public API necessary for ESMValGroup/ESMValTool#1585. Needs to be included for the `v2.0.0` release.
**Tasks** …
> Expanded cmor public API

- docker/Dockerfile
- docker/Dockerfile.dev
- setup.py
This is a small refactor of the docker file that reduces the size of the docker image from 1.1 GB to ~800 MB (as stated in Docker Hub). 
**Tasks** …
> Reduce size of docker image

- setup.py
The `development` docker container uses a [test] extra, but it was not provided by setup.py.
**Tasks**
> Add 'test' extra to installation, used by docker development tag

- README.md
The link to the ESMValCore package on Dockerhub was still pointing to the ESMValTool package.
> Correct dockerhub link

- doc/quickstart/run.rst
- esmvalcore/_main.py
The were some mistakes in the config-user documentation.
> Improve config-user documentation

- .pre-commit-config.yaml
Small tweak to make the excluded files span multiple lines, as in https://github.com/ESMValGroup/ESMValTool/pull/1805 . It makes the regex a bit more robust, looks nicer, and will make it a bit easier to add/remove new directories to the exclude list if necessary.
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
If you need help with any …
> Readable exclude pattern for pre-commit

- setup.cfg
Add trailing comma in isort config. Yapf respects the trailing comma and will not reformat the imports.
**Tasks**
-   [X] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [X] This pull request has a descriptive title that can be used in a changelog
If you need help with any of the tasks above, please do not hesitate to ask by commenting in …
> Fix yapf-isort import formatting conflict (Fixes #777)

- doc/quickstart/configure.rst
- environment.yml
- esmvalcore/_task.py
- package/meta.yaml
- setup.py
- tests/unit/task/test_diagnostic_task.py
**SUMMARY**
This PR kills two birds with one stone: replaced the profiler from `vmprof` to `vprof` that according to @bouweandela in #765 is more maintained and removes the need for `libunwind` as dependency that causes issues on OSX as detailed in #779 
**Tasks**
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link …
> Replace vmprof with vprof

- esmvalcore/_config.py
- esmvalcore/_main.py
A small fix that will make life easier for other parts of ESMValTool (like the cmorizer). 
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preproces …
> Default config-user path now set in config-user read function

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_area.py
- esmvalcore/preprocessor/_shared.py
- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_area/test_area.py
- tests/unit/preprocessor/_time/test_time.py
Adding RMS iris analysis operator (which allow Area Weighting) to the preprocessor. This allows computing root mean squares in the _area.py and _time.py preprocessors.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] Codacy code quality …
> added RMS iris analysis operator

- esmvalcore/cmor/_fixes/shared.py
- tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
> Fix crash for FGOALS-g2 variables without longitude coordinate

- esmvalcore/preprocessor/_area.py
When some of the datasets do not have fx_files, the current function expects them to have their paths set to None but it is actually the empty string. With this fix, the function will work as expected with both options.
**Tasks**
-   [x] If writing a new/modified …
> Fix area_statistics fx files loading

- esmvalcore/preprocessor/_regrid.py
- tests/unit/preprocessor/_regrid/test_extract_levels.py
> Use dask to reduce memory consumption of extract_levels for masked data

- .zenodo.json
- CITATION.cff
- doc/changelog.rst
- esmvalcore/_version.py
- package/meta.yaml
Changed release version to 2.1.0 in files containing it, added citations for the extra peeps we added previously in the zenodo file only and produced and added release notes.
> Release notes v2.1

- .github/workflows/action-pypi-build-and-deploy.yml
- esmvalcore/_version.py
- pyproject.toml
- setup.py
Automate the deployment to PyPi 🐍📦
See  #814
**Tasks**
-   [ ] Please use `yamllint` to check that your YAML files do not contain mistakes
> Create Github Actions workflow to build and deploy on Test PyPi and PyPi

- .pre-commit-config.yaml
- doc/changelog.rst
- doc/conf.py
- Remove duplicate entries from v2.1.0 changelog, these pull requests were already included in v2.0.0
- Update the intersphinx URLs
- Ignore doc/conf.py with pre-commit
> Remove duplicate entries from v2.1.0 changelog

- doc/contributing.rst
Just noticed that the numbering of the steps was wrong, this pull request fixes it.
> Fix numbering of steps in release instructions

- esmvalcore/preprocessor/_derive/rsnstcsnorm.py
- tests/unit/preprocessor/_derive/test_rsntcsnorm.py
Fixing unit for derived variable rsnstcsnorm to prevent over correction caused by changes of #754. This time based on master. Sorry, the other branch (fix_derived_var_rsnstcsnorm) should be deleted.
**Tasks**
-   [ ] Public functions should have a numpy-style docstring so they appear properly in the [API documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/a …
> Fixing unit for derived variable rsnstcsnorm to prevent overcorrection2

- esmvalcore/_recipe.py
- esmvalcore/preprocessor/_io.py
- tests/unit/preprocessor/_weighting/test_weighting_landsea_fraction.py
This pull request removes code needed for Python versions we no longer support: `dict`s are ordered since Python 3.6, so there is no need to use an `OrderedDict` anymore.
It also removes the function `esmvalcore._recipe._get_value`, which was not used for anything anymore.
> Remove code needed for Python <3.6

- package/meta.yaml
- setup.py
Add requests as a dependency, because it's missing from the list of dependencies and it's used:
https://github.com/ESMValGroup/ESMValCore/blob/02b8f668e89cabae656978b44faa1bb27f7158be/esmvalcore/_citation.py#L8
**Tasks**
-   [ ] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. If you suspect Codacy may be wrong, please ask …
> Add requests as a dependency

- environment.yml
- package/meta.yaml
https://github.com/ESMValGroup/ESMValCore/issues/869 - we're in the bogs with `python=3.9` and we need to fix that, until then we need a functional package; note that the latest environment throws 3 test fails as well, as seen from the GA tests [here](https://github.com/ESMValGroup/ESMValCore/runs/1431151389?check_suite_focus=true) - those need to be fixed, preferably in a different branch, let's get this one merged quickly before users start crying around. I'll have a look at those tests on Monday :+1:  - OK I figured it out - the tests are dying coz of #876 and are fixed in #878 :beer:
> Pin Python to less than 3.9

- environment.yml
- package/meta.yaml
- tests/integration/cmor/_fixes/cmip5/test_access1_0.py
- tests/integration/cmor/_fixes/cmip5/test_access1_3.py
> Pin cftime>=1.3.0 to have newer string formatting in and fix two tests

- esmvalcore/preprocessor/_download.py
- tests/unit/data_finder/test_get_start_end_year.py
- tests/unit/data_finder/test_select_files.py
- tests/unit/preprocessor/test_download.py
Downloading CMIP6 data with Synda did not work because the query is different from CMIP5. This pull request adds the correct query.
**Tasks**
> Add support for downloading CMIP6 data with Synda

- esmvalcore/cmor/check.py
**Tasks**
-   [x] Circle/CI tests pass. Status can be seen below your pull request. If the tests are failing, click the link to …
> Fix overwritting in generic level check

- esmvalcore/_task.py
> Add double quotes to script args in rerun screen message when using vprof profiling

- doc/recipe/preprocessor.rst
- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/cmor/fixes.py
- esmvalcore/preprocessor/_regrid.py
- tests/integration/cmor/_fixes/test_shared.py
- tests/integration/preprocessor/_regrid/test_extract_levels.py
- tests/unit/cmor/test_fixes.py
This pull requests extends the existing preprocessor function _extract_levels_. The possibility to convert pressure levels (air_pressure) into height (altitude) and vice versa is added. For the conversion, existing code in cmor/_fixes/shared.py is used that uses the US standard atmosphere to convert from height to pressure. A similar function has been implemented to also allow conversion from pressure to height.
**Tasks**
-   [x] If writing a new/modified …
> Add plev/altitude conversion to extract_levels

- README.md
Make CircleCI badge specific to master branch, so the status shown in README.md reflects the current state of the master branch.
> Make CircleCI badge specific to master branch

- .circleci/config.yml
The codacy coverage reporter (silently!) fails as it cannot find curl. Updating to a newer version that also supports wget.
**Tasks**
> Update codacy coverage reporter to fix coverage

- README.md
Hi all, the docker build badge has been broken for a while. This PR fixes it.
**Tasks** …
> Fix docker build badge url

- .github/pull_request_template.md
When you fill the current pull request template, the associated issue will not be automatically closed. This pull request updates the template so issues are automatically closed by GitHub when the linked pull request is merged.
> Support automatically closing issues

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
There is already a fix for the latitude and longitude bounds for the variable "tas" in esmvalcore/cmor/_fixes/cmip6/cesm2.py. Instead of only to "Tas" it should be applied to "AllVars". I found at least part of the same problem (bounds differ) the fix solves for "prw". It can be expected that it occurs also for other variables if e.g. different experiments from CESM2 are combined. The case I tested was combining historical and ssp585 for prw.
-   Closes/Fixes: #915
***
-   \[ \] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do
-   \[ \] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] …
> Changed latitude longitude fix from Tas to AllVars.

- tests/integration/cmor/_fixes/native6/test_era5.py
Fixes #920
Changes here:
- Avoid hardcoded year 2020 in the comment
- Add more realistic pressure levels to test variable `zg`
***
-   \[x\] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do
-   \[x\] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[x\] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   \[ \] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/ …
> Avoid hardcoded year in tests and add improvement to plev test case

- environment.yml
- package/meta.yaml
- tests/integration/cmor/test_table.py
-   Related to #927 - it doesn't close it, it addresses the test failure when the environment picks up `scipy=1.6.0`; the real closure needs to be addressed in the issue by identifying if the differences from the spline calculation are normal or not (I don't know this stuff)
-   the test naming change is there because new FLAKE is complaining, see [test result](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/3841/workflows/81e1cde0-1051-4b3a-a9a2-303df0a3fcb3/jobs/17567)
***
-   \[ \] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do
-   \[ \] Code …
> Pin scipy to less than 1.6.0 until ESMValGroup/ESMValCore/issues/927 gets resolved

- esmvalcore/_config.py
- esmvalcore/_logging.py
- esmvalcore/_main.py
- tests/unit/test_logging.py
This code moves the logging out of the `_config.py` module into its own `_logging.py`, so that the logger can be imported without initializing `DIAGNOSTICS_PATH` / `CFG` / etc. I also did some refactoring and added some documentation based on my understanding of this module. No functionality has been added or changed.
I hope that this will make it easer to work with. This is also needed for #907 for I'm looking to see if I can merge logging from there with the logging config that already exists.
-   Addresses part of #889
***
-   [x] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests- …
> Refactor logging configuration

- doc/conf.py
The URL where the iris documentation lives has changed. This pull request updates it, so the documentation builds successfully again.
> Update iris documentation URL for sphinx

- esmvalcore/preprocessor/__init__.py
- tests/unit/preprocessor/test_configuration.py
Fix duplicated keys in DEFAULT_ORDER and add some tests to avoid it happening again
-   Closes #971 
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or …
> Fix duplication in preprocessors DEFAULT_ORDER 

- .pre-commit-config.yaml
Hi everyone, this PR pins the versions of `pre-commit` hooks.
-   Related #926
***
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) …
> Pin pre-commit hooks

- README.md
- doc/quickstart/find_data.rst
- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_time.py
Iris documentation has been moved to ReadTheDocs. This PR updates our links to it
***
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or …
> Fix links to Iris documentation

- esmvalcore/config-user.yml
The `remove_preproc_dir` needs to be set to `false` by default because 80% users actually need the preprocessor files and may contribute to confusion amongst uninitiated users
> Set remove_preproc_dir to false in default config-user

- CITATION.cff
- doc/contributing.rst
- esmvalcore/_version.py
- package/meta.yaml
Just what it says
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduct …
> Set version to 2.2.0

- esmvalcore/_task.py
- esmvalcore/preprocessor/__init__.py
- tests/unit/task/test_print.py
-   Closes #980
***
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Documentation builds …
> Restore task summary in debug log

- environment.yml
- setup.py
`fiona` is again giving us headaches, the reason why I am moving it to be a `conda-forge` dependency instead of PyPi is in this [comment](https://github.com/ESMValGroup/ESMValCore/issues/972#issuecomment-774111132) as a result of @remi-kazeroni noticing fiona trying to read an old csv file from GDAL that has disappeared from GDAL>=3.1 and asking us about it in this [comment](https://github.com/ESMValGroup/ESMValCore/issues/972#issuecomment-773321942), also an issue documented here https://github.com/Toblerity/Fiona/issues/897 (towards the bottom)
> Move fiona to be installed from conda forge

- esmvalcore/cmor/_fixes/native6/mswep.py
Hi everyone, I made a silly mistake in converting the units in the MSWEP fix (#969). This PR addresses that. The data have been verified to be similar to ERA5/ERA-Interim 👍
***
-   [x] …
> Bugfix: Fix units for MSWEP data

- doc/contributing.rst
When preparing the release, we realized that some of the steps should be done in a different order. In particular, that we should do the code freeze before changing the release number and the changelog.
This PR is to fix that in the documentation
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new …
> Change the order of the publication steps

- .circleci/config.yml
At the moment, coverage reports are only uploaded to Codacy if there are changes to files listed in .circleci/install_triggers. For most pull request that means that there is no coverage information available on Codacy. This pull request fixes that problem by uploading the coverage report from the tests that always run.
> Report coverage for tests that run on any pull request

- esmvalcore/cmor/check.py
- esmvalcore/cmor/fix.py
- esmvalcore/cmor/table.py
Just to avoid messing with the pre-commit hooks, as usually is just @sloosvel and me modifying these files
***
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) …
> Format cmor related files

- doc/quickstart/configure.rst
- esmvalcore/_data_finder.py
- tests/unit/data_finder/test_replace_tags.py
At BSC, we have different paths for variables generated directly from the model and those computed afterwards. In order to be able to read both, we need to pass multiple input_dirs because we need some replacements in the first part of the path.
An example:
```yaml
EC-EARTH:
input_dir:
default:
- '{expid}/cmorfiles/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
- '{expid}/diags/{activity}/{institute}/{dataset}/{exp}/{ensemble}/{mip}/{short_name}/{grid}/{latestversion}'
```
-   [x] Labels are assigned so they can be used in the …
> Support multiple paths in input_dir

- tests/integration/test_task.py
Fixed a test that caused problems with MacOSX when using multiprocessing set to spawn (standard in Python 3.8).
-   Closes #1002
***
-   [ ] …
> Fix tests for multi-processing with spawn method (i.e. macOSX with Python>3.8)

- esmvalcore/preprocessor/_multimodel.py
This PR extends the preprocessor multi_model_statistics to allow handling of data with a vertical corrdinate "altitude".
-   Closes #1009 
***
-   [ ] …
> Extend preprocessor multi_model_statistics to handle data with "altitude" coordinate

- esmvalcore/cmor/_fixes/cmip5/bnu_esm.py
- esmvalcore/cmor/_fixes/cmip5/ccsm4.py
- esmvalcore/cmor/_fixes/cmip5/cesm1_bgc.py
- esmvalcore/cmor/_fixes/cmip5/cesm1_cam5.py
- esmvalcore/cmor/_fixes/cmip5/cesm1_fastchem.py
- esmvalcore/cmor/_fixes/cmip5/cesm1_waccm.py
- esmvalcore/cmor/_fixes/cmip5/fio_esm.py
- esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py
- tests/integration/cmor/_fixes/cmip5/test_bnu_esm.py
- tests/integration/cmor/_fixes/cmip5/test_ccsm4.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_bgc.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_cam5.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_fastchem.py
- tests/integration/cmor/_fixes/cmip5/test_cesm1_waccm.py
- tests/integration/cmor/_fixes/cmip5/test_fio_esm.py
- tests/integration/cmor/_fixes/cmip5/test_gfdl_cm2p1.py
This PR provides fixes for the CMIP5 datasets BNU-ESM, CCSM4, CESM1-BGC, CESM1-CAM5, CESM1-FASTCHEM, CESM1-WACCM, FIO-ESM, GFDL-CM2p1. Variable cl (3-dim cloud fraction) is erroneously reported in units percent (%) but units are actually given as fraction (0-1).
-   Closes #1016
-   [ ] …
> Added fixes for various CMIP5 datasets, variable cl (3-dim cloud fraction)

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
Extract season was having side efefcts in the form of extra aux coords left in the original cube. This PR fixes it
-   Closes #1013
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/e …
> Avoid side effects in extract_season

- .github/workflows/action-test.yml
I am trying to gather enough statistic to prove that if we run the test in single thread mode we will not see the Segmentation Faults we've been seeing for nearly a year now. So to do that I want to have the GA run the test only workflow every three hours; unfortunately it's not possible to have this done on a branch, it has to be the main branch, but we can let this go for a few days, gather enough statistic then revert to the nightly run as we had it so far. If this is true then we can do what @stefsmeets suggests in this [comment](https://github.com/ESMValGroup/ESMValCore/issues/1020#issuecomment-785809295) and hopefully rid ourselves of those pesty SegFaults for good. Please see logic behind this PR in https://github.com/ESMValGroup/ESMValCore/issues/1020
> Switch to running the Github Action test workflow every 3 hours in single thread mode to observe if Sementation Faults occur

- .github/workflows/action-test.yml
reverts changes that supported the (now false supposition) tests pass w/o SegFaults if run in single thread mode from #1020
> Revert to original Github Actions test workflow removing the 3-hourly test run with -n 1

- tests/unit/preprocessor/_multimodel/test_multimodel.py
Hi everyone, we are developing a new implementation of multi-model statistics preprocessor in #968. The goal of this PR is to to better chart out the requirements for the preprocessor, and to have a more complete description of the functionality through the unit tests, so that no functionality / features are lost.
The current set of tests does not cover all the functionality and is difficult to extend as it still makes use of the old `unittest` framework. This PR re-implements the functionality of the old tests using `pytest`.
***
-   [x] PR has a descriptive title for the …
> Update tests for multimodel statistics preprocessor

- tests/sample_data/multimodel_statistics/test_multimodel.py
-   Closes #1028
To show that this actually solves the problem, I
1.  created a branch called `fix-regression-multimodel-tests` off `master` before #1021 was merged and pushed it, to run the tests and create the pytest cache. 
2. pulled the current master into `fix-regression-multimodel-tests` and pushed that, to show that the tests fail because of the stale cache. 
3. changed the cache key, committed and pushed to run the tests again and to show that this solves the problem.
You can view the results of the test runs here:
https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore?branch=fix-regression-multimodel-tests
I added some comments with instructions to change the cache key every time the cached input data is changed, to hopefully avoid this problem in the future.
***
- …
> Avoid stale cache for multimodel statistics regression tests

- .github/workflows/action-conda-publish.yml
- .github/workflows/action-install-from-conda.yml
- .github/workflows/action-install-from-pypi.yml
- .github/workflows/action-install-from-source.yml
- .github/workflows/action-test.yml
To make sure that recently fixed tests (and other issues) are run on OSX as well as Linux, newer versions of Python (3.8 and 3.9) are added to Github Actions.
Follows up on #1003
**NB: the Anaconda Publish action fails, which it does on Master too, [e.g.](https://github.com/ESMValGroup/ESMValCore/runs/2013956597?check_suite_focus=true) @ESMValGroup/esmvaltool-coreteam**
***
-   [x] Labels are assigned so they can be used in the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing. …
> add newer Python versions in OSX to Github Actions

- esmvalcore/cmor/check.py
- esmvalcore/preprocessor/_time.py
- tests/unit/test_cmor_api.py
Closes #1036 
as a thumb rule, we should really not use variable names like `time` as well as we should make a proper `__init__.py` file for the `cmor` module - this fix here is not elegant at all but until we de-convolute `cmor` module from `preprocessor` modue via a good `__init__` file I can't see another solution
> Move _get_time_bounds from preprocessor._time to cmor.check to avoid circular import with cmor module

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
This PR adds fixes for `cl`, `cli` and `clw` for the CESM2 models.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [x] …
> Added fixes for hybrid level coordinates of CESM2 models

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
We found that when a `extract_month` call in a cube that did not have the required month in it ESMValTool fails with an obscure extract trace
```python
File "/opt/conda/lib/python3.8/site-packages/esmvalcore/_task.py", line 735, in _run_task
output_files = task.run()
File "/opt/conda/lib/python3.8/site-packages/esmvalcore/_task.py", line 242, in run
self.output_files = self._run(input_files)
File "/opt/conda/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 432, in _run
product.apply(step, self.debug)
File "/opt/conda/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 300, in apply
self.cubes = preprocess(self.cubes, step, **self.settings[step])
File "/opt/conda/lib/python3.8/site-packages/esmvalcore/preprocessor/__init__.py", line 253, in …
```
> Raise in extract_season and extract_month if result is None

- esmvalcore/cmor/tables/custom/CMOR_rlns.dat
- esmvalcore/cmor/tables/custom/CMOR_rsns.dat
As per the discussion in #1050 the custom CMOR file for the variables rsns and rlns (Surface Net **downward** Shortwave/Longwave Radiation) contain a wrong value in the field `positive: up`. This pull request corrects them to `down.` 
-   Closes  #1050
***
-   [x] Code follows the [style …
> Fix 'positive' attribute for rsns/rlns variables

- esmvalcore/cmor/_fixes/native6/era5.py
As discussed in #1050 we need some additional radiation data from ERA5 (namely rsus, rlus, rsns, rlns). This pull request adds fixes to these variables equivalent to the existing fixes for rsds and rlds. 
Additional information: radiation upward variables are not available for ERA5. We discussed several ideas but have not really come up with a solution how to fix this on the fly (e.g. https://github.com/ESMValGroup/ESMValCore/issues/1050#issuecomment-800271692). Fixing it in the diagnostic (as I suggested here: https://github.com/ESMValGroup/ESMValCore/issues/1050#issuecomment-800226289) does not work because some of the calculations are not linear (e.g., there is a difference if we do std(rsus) or std(rsds) - std(rsns)). 
Therefore I now calculate the upwards variables offline as a first …
> Add fixes for the net & up radiation variables from ERA5

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
This pull request adds missing bounds properly if the longitude values have been recomputed.
-   Closes #1056 
***
-   [ ] …
> Fix bug when fixing bounds after fixing longitude values

- .gitignore
- .pre-commit-config.yaml
- .prospector.yml
- doc/conf.py
- doc/contributing.rst
- esmvalcore/_config/_logging.py
- esmvalcore/_recipe.py
- esmvalcore/_task.py
- esmvalcore/cmor/table.py
- esmvalcore/experimental/_logging.py
- esmvalcore/experimental/_warnings.py
- esmvalcore/experimental/config/_config_object.py
- esmvalcore/experimental/config/_validated_config.py
- esmvalcore/experimental/recipe.py
- esmvalcore/experimental/recipe_info.py
- esmvalcore/experimental/recipe_metadata.py
- esmvalcore/experimental/recipe_output.py
- esmvalcore/experimental/templates/__init__.py
- esmvalcore/experimental/utils.py
- esmvalcore/preprocessor/_regrid.py
- package/meta.yaml
- setup.cfg
- setup.py
- tests/integration/test_data_finder.py
- tests/integration/test_recipe_checks.py
- tests/unit/experimental/test_config.py
- tests/unit/preprocessor/_time/test_time.py
- tests/unit/preprocessor/_weighting/test_weighting_landsea_fraction.py
Hi everyone, this PR adds [mypy](https://mypy.readthedocs.io/en/latest/index.html) as an additional test in `pytest`.
It also fixes all the type annotations where possible.
-   Closes #993 
-   Link to documentation: https://esmvaltool--1042.org.readthedocs.build/projects/ESMValCore/en/1042/contributing.html#python
***
-   [x] …
> Add tests for type annotations with mypy

- .circleci/config.yml
- package/meta.yaml
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
Continuation from #1064 to include the same test run strategy for conda build tests ~and try bump the number of threads we use for running the parallel tests on Circle.~ Bumping number of threads with `-n 4` definitely leads to memory issues for the conda build tests and might lead to the same issue for the regular CI tests, so let's keep them at 2
> Run conda build parallel AND sequential tests

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
This pull request flips back the coordinate bounds if they have been reversed when checking the coordinate direction
-   Closes #1060 
***
-   [ ] …
> Fix bounds after reversing coordinate values

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- esmvalcore/cmor/_fixes/fix.py
- esmvalcore/cmor/_fixes/shared.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/test_fix.py
- tests/integration/cmor/_fixes/test_shared.py
This PR adds the support for `mip`-level fixes, i.e. a fix for all variables of a MIP table for a single dataset. As test case, a fix for CESM2 is included, which supersedes #888.
@tomaslovato Can you briefly do a test if this works for CESM's `thetao` for the scientific review?
@jvegasbsc  Could you please do a brief technical review?
Thanks!!
Closes #1094.
***
*** …
> Supported `mip`-level fixes

- esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1.py
- esmvalcore/cmor/_fixes/cmip5/bcc_csm1_1_m.py
- esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
- esmvalcore/cmor/_fixes/cmip6/bcc_esm1.py
- esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py
- esmvalcore/cmor/_fixes/common.py
- tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
- tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1_m.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py
- tests/integration/cmor/_fixes/cmip6/test_fgoals_g3.py
- tests/integration/cmor/_fixes/test_common.py
This PR
- renames `grid_latitude` and `grid_longitude` to `cell index along first/second dimension` (see #1067).
- removes duplicated code from ocean grid fixes and corresponding tests.
- adds missing tests for `tos` and `siconc` of FGOALS-g3.
I checked all affected preprocessed files (raw and regridded to a regular grid) before and after this PR with `cdo diff` and found no differences.
I didn't find any appearance of `grid_latitude` or `grid_longitude` in ESMValTool, so this shouldn't affect any diagnostic.
Closes #1067.
***
[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technica …
> Fix erroneous use of `grid_latitude` and `grid_longitude` and cleaned ocean grid fixes

- esmvalcore/_citation.py
> Add timeout to requests.get in _citation.py

- doc/develop/fixing_data.rst
- esmvalcore/cmor/_fixes/cmip6/cnrm_esm2_1.py
- esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
- esmvalcore/cmor/_fixes/cmip6/ipsl_cm6a_lr.py
- esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cnrm_esm2_1.py
- tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
- tests/integration/cmor/_fixes/cmip6/test_ipsl_cm6a_lr.py
- tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
Based on PR #1095 create the ocean depth `mip-level` fixes for other problematic CMIP6 datastest, namely cnrm_esm2_1, gfdl_esm4, ipsl_cm6a_lr
Closes #1069 (and also #527 and #1100)
***
*** …
> ocean depth fix for cnrm_esm2_1, gfdl_esm4, ipsl_cm6a_lr datasets +  mcm_ua_1_0

- tests/integration/data_finder.yml
This PR adds additional test cases for the integration tests of `_data_finder.py` which should make the review of #1082 easier.
Closes #1085.
There are no changes in the code itself, so I think we can merge this quickly. What do you think @valeriupredoi ?
***
*** …
> Added additional test cases for integration tests of data_finder.py

- esmvalcore/_recipe.py
- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
- tests/integration/preprocessor/_io/test_save.py
- tests/unit/test_recipe.py
This PR fixes a bug that was introduced in #917 that prevented the usage of the ``--skip-nonexistent`` option. I also add a tiny test for it.
Note that I also adapted the preprocessors `concatenate` and `save` which gave ugly error messages when an empty cube was passed. This should never happen during a regular ESMValTool run, but could happen when these functions are used as part of the `esmvalcore` API. 
Closes #1040, closes #988.
***
[2]: …
> Fixed --skip-nonexistent option

- esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
- tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
Fix for the 10m height missing for `uas`
Closes #1101
***
***
> Fix for uas variable of the MCM_UA_1_0 dataset

- esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
- esmvalcore/cmor/_fixes/cmip6/bcc_esm1.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_esm1.py
Fixes for `sos` and `siconc` of `BCC-ESM1` model and `sos` of `BCC-CSM2` model. 
Closes #1089 
***
***
> Fixes for sos and siconc of BCC models

- package/meta.yaml
- setup.py
- tests/integration/cmor/_fixes/cmip5/test_access1_0.py
- tests/integration/cmor/_fixes/cmip5/test_access1_3.py
`cf-time<2.1.5` would introduce an empty space in `num2date` for years that are <1000, whereas newer `cf-units>=2.1.5` would not, hence two of our tests are failing as seen by [Github Actions](https://github.com/ESMValGroup/ESMValCore/actions/runs/862322433) - this is a recurring problem since a few versions ago they were adding a 0 in front, hopefully next release they'll not add a horse :horse: 
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific …
> Pin cf-units and fix tests (cf-units>=2.1.5)

- .circleci/config.yml
- .github/workflows/action-conda-publish.yml
- .github/workflows/action-install-from-conda.yml
- .github/workflows/action-install-from-pypi.yml
- .github/workflows/action-install-from-source.yml
- .github/workflows/action-pypi-build-and-deploy.yml
- .github/workflows/action-test.yml
- README.md
- doc/changelog.rst
- doc/contributing.rst
- doc/develop/derivation.rst
- doc/develop/preprocessor_function.rst
- doc/quickstart/configure.rst
- doc/quickstart/install.rst
- doc/recipe/overview.rst
This PR updates all references to "master" e.g. in the documentation and readme files (master branch) to "main" (the new GitHub standard, see https://github.com/github/renaming). See also corresponding PR in ESMValTool: https://github.com/ESMValGroup/ESMValTool/pull/2172.
Closes https://github.com/ESMValGroup/ESMValCore/issues/1031
***
> Updated references master to main

- esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
Closes #1107. Adds 0m-depth coordinate for fgco2 in CESM2 models.
***
> Run fgco2 fix for all CESM2 models

- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_fv2.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py
- esmvalcore/cmor/_fixes/cmip6/cesm2_waccm_fv2.py
- esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
- esmvalcore/cmor/_fixes/cmip6/gfdl_esm4.py
- esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
- esmvalcore/cmor/_fixes/common.py
- esmvalcore/cmor/_fixes/shared.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_fv2.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2_waccm_fv2.py
- tests/integration/cmor/_fixes/cmip6/test_gfdl_cm4.py
- tests/integration/cmor/_fixes/cmip6/test_gfdl_esm4.py
- tests/integration/cmor/_fixes/cmip6/test_kiost_esm.py
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/cmor/_fixes/test_shared.py
Closes #1104. Add missing scalar coordinate `typesi` for the variable `siconc` of CMIP6 models. 
***
***
These fixes reuse what was done in #629.
> Fixes for the siconc variable of CMIP6 models

- tests/integration/test_recipe.py
The strategy is to fix #1159 properly (one way or another), but to allow for us not having failed tests during the current release procedures, I am skipping the two tests that fail conditioning on version < 2.4.0 (if we don't fix it by then, we'll have those two tests fail again). I copied over the functionality of those two tests in a couple `_incomplete` tests that run everything else that doesn't fail and we should test for (we should remove those and re-instate the actual complete, currently skipped now).
Related to **BUT IT DON'T CLOSE IT** #1159 
***
[1]: …
> Fix test failing due to fx files chosen differently on different OS's

- .github/workflows/action-test.yml
- tests/integration/cmor/_fixes/cmip5/test_access1_0.py
- tests/integration/cmor/_fixes/cmip5/test_access1_3.py
Got rid of `num2date` calls that change the outputted string formatted date everytime there's a new release of `cf_units` and compare datime objects straight out the box.
Closes #1158 
***
*** …
> Compare datetimes instead of strings in _fixes/cmip5/test_access1_X.py

- esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py
- tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py
This PR checks and changes the circular attribute for dataset MCM-UA-1-0 after fixing the longitudes. This is done to avoid getting masked values after regridding.
Closes #1175 
***
~- [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~
~-  [🛠][1] Any changed [dependencies have been added or …
> Set circular attribute in MCM-UA-1-0 fix

- esmvalcore/preprocessor/_area.py
- tests/unit/preprocessor/_area/test_area.py
Hi all! This PR fixes a bug where the the `extract_shape` preprocessor crops on the whole shapefile when a subset of ids is specified. For example, if the whole shapefile covers regions all over the world, let's say A, B and C, but you are only interested in A. `extract_region` currently will return a cube with coordinates defined by a bounding box fitting A, B and C, masking everything 
outside of A. This can result in unexpectedly large cubes.
This PR crops on the selected regions, so the bounding box will fit _just_ A. This works for multiple regions, e.g. if A and B are specified, the bounding box will fit A and B (but not C).
This only applies if the `ids` keyword is specified. If `ids` is not specified (`None`), there is no change in behaviour.
Closes #1072 
***
It is the …
> Crop on the ID-selected region(s) and not on the whole shapefile

- codecov.yml
Improve codecov status checks
Link to documentation: https://docs.codecov.com/docs/commit-status
***
***
> Improve codecov status checks

- esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
- tests/integration/cmor/_fixes/cmip5/test_miroc_esm.py
Fix time coordinate of `gpp_Lmon_MIROC-ESM_esmFixClim1_r1i1p1_000101-014012.nc`.
Closes #1187.
***
***
> Fixed time coordinate of MIRCO-ESM

- esmvalcore/cmor/_fixes/cmip5/miroc5.py
Necessary after  merge of #1110 to make the derived variable lvp for recipe_deangelis15nat.yml possible again, see issue #1191 
The merged pull request #1110 introduced a rounding for latitude for the variable pr. Therefore its grid is now in conflict with the one from hfls and evspsbl which should be used to calculate the derived variabe lvp (used by recipe_deangelis15nat.yml), see also ESMValGroup/ESMValTool#2198. I tested that recipe_deangelis15nat.yml ran again when including this change. But I'm not sure, if including more variables can have the same effect on other recipes as PR #1110 had on recipe_deangelis15nat.yml?
Closes #1191
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item …
> Enhancing MIROC5 fix for hfls and evspsbl

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
Following #1210 this PR implements the following behavior for multimodel statistics, when the input data is a daily frequency with inconsistent calendars:
- `span='overlap'`: discard those days that occur only in certain calendars but not in others
- `span='full'`: use nearest-neighbour lookup to fill missing days. Missing dates outside the original date range are masked.
This is in contrast to the previous behavior, which was:
- `span='overlap'`: Find the first and last day that is present in all datasets; remove everything before the first and after the last day.
- `span='full'`: Find the very first and the very last day across all cubes; pad every cube with masked out data before and after its actual data to cover the full time range.
This only worked for data with the same number of …
> Fix alignment of daily data with inconsistent calendars in multimodel statistics

- .github/workflows/action-conda-publish.yml
- .github/workflows/action-install-from-conda.yml
- .github/workflows/action-install-from-pypi.yml
- .github/workflows/action-install-from-source.yml
- .github/workflows/action-test.yml
- environment.yml
- package/meta.yaml
- setup.py
- tests/integration/cmor/_fixes/cmip5/test_access1_0.py
- tests/integration/cmor/_fixes/cmip5/test_access1_3.py
- `cf-units` went up to 3.0.0 and this broke the tests again, now we have use of `cf-units` for both reference and test dates
- I removed the Github Action tests for Python 3.6 - it is old and we should not support it anymore, on top of it all `cf-units=2.1.5` throws a very dubious error when comparing datetimes as we do in those tests, and 3.0.0 doesn't have a packaging for Python 3.6
***
*** …
> pin cf-units, remove github actions test for Python 3.6 and fix test_access1_0 and test_access1_3 to use cf-units for comparisons

- .github/workflows/action-test.yml
- environment.yml
- package/meta.yaml
- setup.py
A bunch of bugfixes and improvements have been added in the 3.0.2 release of iris, including a fix to a nasty bounds behavior, see [last comment on the issue](https://github.com/ESMValGroup/ESMValCore/issues/799#issuecomment-872331326) - this is not make or break but it's good to make sure we don't pick up an older (3.0.1 actually) version. I suggest we have this in time for the imminent bugfix release 2.3.1 :grin: 
> Pin lower bound for iris to 3.0.2

- doc/recipe/preprocessor.rst
- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
This PR fixes the automatic retrieval of fx files when no `mip` is specified.
I agree with @sloosvel that a predefined order for the mip tables is not useful due to the many different project tables. Therefore I just implemented an alphabetic ordering, i.e., the first `mip` that has data is automatically selected. To bypass this, the user has to define a specific `mip` in the recipe. I added a paragraph to the documentation that describes this process.
This should go into 2.3.1 since this fixes a bug that (1) lets the test fails and (2) might lead to the tool wrongly complaining about missing data. #1169 only disabled the tests and didn't actually fix the bug.
Closes #1159.
Link to documentation: https://esmvaltool--1216.org.readthedocs.build/projects/ESMValCore/en/1216/recipe/preprocessor …
> Fixed search for fx files when no ``mip`` is given

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
The fx variables are removed before computing multimodel statistics, in order to avoid issues when merging cubes with iris. 
Closes #1213
***
***
> Remove fx variables before computing multimodel statistics

- tests/unit/preprocessor/_multimodel/test_multimodel.py
This PR adds a test that performs the following check:
When two cubes of variables `tas`, both with scalar coordinate `height`, but with different values (1.5 or 2 m, respectively), are combined in multimodel:
* The preprocessor will work
* The result cube will have only 1 height coordinate (i.e. they are combined)
* The new scalar height coordinates will represent the midpoint between the incoming cubes, which are set as bounds
Closes #1204
***
[2]: …
> Add test to verify behaviour for scalar height coord for tas in multi-model

- esmvalcore/_recipe_checks.py
- tests/integration/test_recipe_checks.py
> Sort missing years in "No input data available for years" message

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
This adds code to the climate_statistics preprocessor to detect whether it has changed the dtype of the cube. If this is the case, it changes the dtype back to the original dtype.
Closes #1235 
***
*** …
> Make sure climate statistics always returns original dtype

- esmvalcore/preprocessor/_area.py
- tests/unit/preprocessor/_area/test_area.py
This adds code to the area_statistics preprocessor to detect whether it has changed the dtype of the cube. If this is the case, it changes the dtype back to the original dtype.
Closes #1236 
***
*** …
> Make sure area_statistics preprocessor always returns original dtype

- .circleci/config.yml
- codecov.yml
- esmvalcore/_config/_config.py
- esmvalcore/_main.py
- esmvalcore/_recipe_checks.py
- esmvalcore/config-user.yml
- tests/integration/test_main.py
- tests/unit/experimental/test_config.py
When there is no user-specified config-user file, the info stdout says Using config file None, which is both untrue and user confusing, even though the actual value is indeed `None`
Closes https://github.com/ESMValGroup/ESMValTool/issues/2235
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two …
> Add a more friendly and useful message when using default config file

- environment.yml
- package/meta.yaml
- setup.py
[iris 3.0.4](https://scitools-iris.readthedocs.io/en/stable/whatsnew/3.0.4.html) have dropped support for Python 3.6 and we haven't yet, we decided to drop support when it's obsolete in fall 2021 (with release 2.4 for us)
***
***
> Pin `iris<3.0.4` to ensure we still (sort of) support Python 3.6

- .github/workflows/action-test.yml
- environment.yml
- package/meta.yaml
- tests/integration/cmor/_fixes/cmip5/test_bcc_csm1_1.py
- tests/integration/cmor/_fixes/test_common.py
This PR fixes a test that fails in a more recent version of `scipy` (>1.6). Note that now the pin is `scipy>=1.6` instead of `scipy<1.6` to make sure that the newer version is picked up. Without the pin, I still got version 1.5.3 from `conda env create`.
Closes #927.
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of …
> Allow more recent version of `scipy`

- tests/integration/preprocessor/_regrid/test_extract_point.py
Fix the numpy deprecation warnings coming from tests/integration/preprocessor/_regrid/test_extract_point.py:
```
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__multiple_both_linear
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__multiple_both_nearest
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__multiple_linear
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__multiple_nearest
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__single_linear
tests/integration/preprocessor/_regrid/test_extract_point.py::Test::test_extract_point__single_nearest …
```
> Fix numpy deprecation warnings

- .pre-commit-config.yaml
- setup.cfg
Fixes the first half of  #1005
See also https://github.com/google/yapf/issues/744
***
***
> Work around issue with yapf not following PEP8

- .circleci/config.yml
- doc/contributing.rst
- doc/quickstart/install.rst
Closes #1279 
[conda install](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/5473/workflows/ee6c1e56-a960-4200-a2ab-b28502b8a8b0/jobs/26229) works fine with these changes, hopefully it'll not run out of memory anymore, at least as often as before :beer: 
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) …
> modernize `conda_install` test on Circle CI by installing from conda-forge with Python 3.9 and change install instructions in documentation

- doc/quickstart/configure.rst
- esmvalcore/config-user.yml
This PR adds a path for the `auxiliary_data_dir` on Jasmin and Mistral. These are included in the "lines to uncomment" for each of the two machines. Not sure if these paths would be better placed below 
```yaml
auxiliary_data_dir: ./auxiliary_data
```
Closes #1266 
Link to documentation: [https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=auxiliary#user-configuration-file)
***
[1]: …
> Machine-specific directories for auxiliary data in the `config-user.yml` file

- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_load.py
I found an EC-Earth experiment at BSC that has the `history` attribute at the coords and not only in the cube. It was added in the CMORization process to keep track of the changes done to that coordinate. I am not sure if this is something particular of ec2cmor or if this is coming directly from the cmor library.
I extended the automatic removal of the history attribute to the coordinates to automatically fix it
***
***
To help with the …
> Remove history attribute from coords

- doc/api/esmvalcore.api.config.rst
- doc/quickstart/configure.rst
- esmvalcore/_config/_config.py
- esmvalcore/_recipe.py
- esmvalcore/_task.py
- esmvalcore/experimental/config/_config_validators.py
Remove `write_netcdf` and `write_plots` from config-user.yml. These settings have been deprecated for a year and are scheduled for removal in v2.4.
Related to #93
***
***
> Remove write_netcdf and write_plots from config-user.yml

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
This reduces the runtime of the `multi_model_statistics` preprocessor function in some cases by reducing the number of steps that need to be taken to iterate over the time dimension.
I think there was a bug in the computation of the `peak` statistic, which resulted in a cube with the wrong dimensions. @Peter9192 Could you check if the new behavior is correct, since you added the test for that in #1150?
***
***
To help with the number …
> Speed up multimodel statistics and fix bug in peak computation

- esmvalcore/_provenance.py
- tests/integration/test_recipe.py
Closes #1148
No longer embed provenance in output files.
***
***
> No longer embed provenance in output files

- .github/workflows/action-install-from-source.yml
- .github/workflows/action-pypi-build-and-deploy.yml
- environment.yml
- package/meta.yaml
- setup.py
See the issue and [comment](https://github.com/ESMValGroup/ESMValCore/issues/1208#issuecomment-915175795) for more details, in a nutshell - for some reason `esmf/esmpy=8.1.0` reduces cpu affinity to 0 when running esmvalcore; thanks to @SarahAlidoost for noticing this; 8.1.1 is fine but is yet to be solved for in the conda/mamba environment; 8.0.1 is fine too and it's what esmvaltool currently ingests in the environment 
Closes #1208 
***
[2]: …
> Pin esmpy to anything but 8.1.0 since that particular one changes the CPU affinity

- doc/api/esmvalcore.preprocessor.rst
- esmvalcore/preprocessor/__init__.py
- tests/integration/test_recipe.py
Move multimodel statistics preprocessor function to the end of the default order.
Some formatting issues and the use of a deprecated Python standard library function are also fixed in this pull request.
Closes #1221
Link to documentation: https://esmvaltool--1299.org.readthedocs.build/projects/ESMValCore/en/1299/api/esmvalcore.preprocessor.html
***
*** …
> Run the multimodel statistics preprocessor last

- doc/requirements.txt
An incompatibility between the readthedocs sphinx theme and newer versions of docutils prevents proper rendering of bullet lists.
By pinning docutils <0.17 in the doc environment, we can get proper lists again.
For details see https://stackoverflow.com/a/68008428.
Pins docutils <0.17.
Closes #1179 
Link to documentation: https://esmvaltool--1320.org.readthedocs.build/projects/ESMValCore/en/1320/
***
***
To help with the number pull …
> Pin docutils <0.17 to fix bullet lists on readthedocs

- esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
- tests/integration/cmor/_fixes/cmip6/test_fgoals_f3_l.py
Add bounds to tos using `OceanGridFix`
Closes #1325
***
- [ x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available
~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~
***
- 🙏 …
> Add grid fix for tos in fgoals-f3-l

- doc/develop/fixing_data.rst
- esmvalcore/config-developer.yml
For datasets using project ISLCM, instead of writing e.g. :
`out: Analyse/TS_MO'`
one should now write :
`out: Analyse, freq: TS_MO`
This is mainly in order to avoid side effects when creating output
directories based on attributes value
Link to documentation: https://esmvaltool--1304.org.readthedocs.build/projects/ESMValCore/en/1304/develop/fixing_data.html#ipsl-cm6
***
***
- 🙏 We kindly ask you …
> Fix DRS for IPSLCM : split attribute 'freq' into : 'out' and 'freq'

- esmvalcore/config-developer.yml
> Add "grid" as a tag to the output file template for CMIP6

- esmvalcore/cmor/tables/custom/CMOR_rlns.dat
- esmvalcore/cmor/tables/custom/CMOR_rsns.dat
This PR adds `standard_name` to the custom tables for the variables `rlns` and `rsns`. This is necessary for the derivation of the `rlus` and `rsus` variables in ERA5 otherwise a wrong standard name containing "upward" is used and the derivation fails (see [comment](https://github.com/ESMValGroup/ESMValTool/issues/2396#issuecomment-960826885)).
Related to https://github.com/ESMValGroup/ESMValTool/issues/2396
- https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/cmor/tables/custom/CMOR_rlns.dat
- https://github.com/ESMValGroup/ESMValCore/blob/main/esmvalcore/cmor/tables/custom/CMOR_rsns.dat
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to the [🛠 Technical][1] …
> Adding standard names to the custom tables of the `rlns` and `rsns` variables

- esmvalcore/preprocessor/_area.py
- tests/unit/preprocessor/_area/test_area.py
This pull request adds support to handle fx variables without crashing in the `extract_shape` preprocessor. It removes them before the shape extraction, and re-adds them after the data has been masked.
Closes #1394
***
*** …
> Fix `extract_shape` when fx vars are present

- doc/recipe/preprocessor.rst
- esmvalcore/_recipe.py
- esmvalcore/_recipe_checks.py
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_bias.py
- tests/integration/test_recipe_checks.py
- tests/unit/preprocessor/_bias/test_bias.py
This PR adds a `bias` preprocessor that is able to calculate absolute or relative biases relative to a predefined reference dataset.
Closes #119 
Link to documentation: https://esmvaltool--1406.org.readthedocs.build/projects/ESMValCore/en/1406/recipe/preprocessor.html#bias
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) …
> Added bias preprocessor

- esmvalcore/_provenance.py
- esmvalcore/preprocessor/__init__.py
- tests/unit/preprocessor/test_error_logging.py
This PR improves the error messages when a preprocessor is failing. For example, this old message
```
2021-12-08 12:41:02,140 UTC [44931] ERROR   Failed to run fix_metadata([<iris 'Cube' of surface_downwelling_shortwave_flux_in_air / (W m-2) (time: 1; -- : 81920)>, <iris 'Cube' of surface downwelling direct visible radiation at radiation time / (W m-2) (time: 1; -- : 81920)>, <iris 'Cube' of surface_downwelling_shortwave_flux_in_air_assuming_clear_sky / (W m-2) (time: 1; -- : 81920)>, <iris 'Cube' of daylght_frc_rt / (unknown) (time: 1; -- : 81920)>, <iris 'Cube' of surface_upwelling_shortwave_flux_in_air / (W m-2) (time: 1; -- : 81920)>, <iris 'Cube' of vert. integr. heating by atm. gravity wave drag / (W m-2) (time: 1; -- : 81920)>, <iris 'Cube' of meridional stress from subgrid scale …
```
> Improve error messages when a preprocessor is failing

- .github/workflows/run-tests.yml
- tests/unit/preprocessor/test_error_logging.py
#1408 broke the tests for python 3.7, which are only tested for `main`. This should fix it.
@ESMValGroup/esmvaltool-coreteam would it maybe be possible to also run these tests on the feature branches so we immediately see that those fail and not only after the merge to `main`?
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-request …
> Fixed tests for python 3.7

- esmvalcore/preprocessor/_regrid.py
- tests/integration/preprocessor/_regrid/test_regrid.py
- tests/unit/preprocessor/_regrid/test_regrid.py
Right now, `unstructured_nearest` regridding does not return masked arrays. This PR fixes this.
Closes #1413
***
***
> Correctly use masked arrays after `unstructured_nearest` regridding

- doc/recipe/preprocessor.rst
The brackets used in the documentation of the `seasons` argument to several preprocessor functions were not a valid way to create a list in YAML. This pull request fixes the problem.
Link to documentation: https://esmvaltool--1420.org.readthedocs.build/projects/ESMValCore/en/1420/recipe/preprocessor.html#seasonal-statistics
***
*** …
> Correct brackets in preprocessor documentation for list of seasons

- esmvalcore/preprocessor/_derive/_shared.py
I changed the calculation of the derived variable so that it can work with the latest version of iris.
Closes #1427
***
> Fixing the broken derivation script for XCH4 (and XCO2)

- esmvalcore/_main.py
- esmvalcore/_recipe.py
- esmvalcore/experimental/config/_config_validators.py
- esmvalcore/preprocessor/_derive/__init__.py
- tests/unit/main/test_esmvaltool.py
- tests/unit/test_recipe.py
This PR adds additional validation for the validity of command line arguments before reading the configuration. This allows us to detect errors like
```
> esmvaltool run --config-usa ~/config-user.yml ~/tmp/recipes/recipe_cox18nature.yml
...
esmvalcore.experimental.config._validated_config.InvalidConfigParameter: `config-usa` is not a valid config parameter.
```
In addition, this also catches wrong types (this has also been caught previously, but later in the run):
```
> esmvaltool run --config-file ~/config/DKRZ_default.yml --offline=aaaa ~/ESMValTool/esmvaltool/recipes/examples/recipe_python.yml
...
esmvalcore.experimental.config._validated_config.InvalidConfigParameter: Key `offline`: Could not convert `aaaa` to `bool`
```
Moreover, I renamed the option `skip-nonexistent` to …
> Added earlier validation for command line arguments

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_regrid.py
- tests/integration/preprocessor/_regrid/test_extract_levels.py
- tests/unit/preprocessor/_regrid/test_extract_levels.py
This PR deprecates the vertical regridding schemes `nearest_horizontal_extrapolate_vertical` and `linear_horizontal_extrapolate_vertical` in favor of `nearest_extrapolate` and `linear_extrapolate`.
I changed all affected recipes and tested them successfully (see ESMValGroup/ESMValTool#2487).
Closes #1170
Link to documentation: https://esmvaltool--1429.org.readthedocs.build/projects/ESMValCore/en/1429/recipe/preprocessor.html#vertical-interpolation
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#sci …
> Renamed vertical regridding schemes

- esmvalcore/config-user.yml
- esmvalcore/esgf/_download.py
- tests/unit/esgf/test_download.py
This PR fixes a bug in the automatic download feature that led to weird error messages. It assigns `median_speed = 0.0` if no non-zero values for the download speed can be found from past runs. This avoids cryptic error messages that result from using the download feature on a node without internet connection.
Closes #1440
***
*** …
> Fixed bug that caused automatic download to fail in rare cases

- esmvalcore/config-user.yml
- tests/unit/config/test_config.py
Apply changes from ESMValGroup/ESMValTool#2507
***
***
> Synchronized config-user.yml with version from ESMValTool

- doc/quickstart/configure.rst
- esmvalcore/_config/_config.py
- esmvalcore/config-user.yml
- tests/unit/config/test_config.py
This fixes the issues raise in #1456 and also synchronizes the `config-user.yml` file with the corresponding section in the documentation.
Closes #1456
Link to documentation: https://esmvaltool--1457.org.readthedocs.build/projects/ESMValCore/en/1457/quickstart/configure.html#user-configuration-file
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html# …
> Solved issues in configuration files

- CITATION.cff
- esmvalcore/_version.py
- package/meta.yaml
> Increased ESMValCore version to 2.5.0rc1

- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/preprocessor/_multimodel.py
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/cmor/_fixes/test_shared.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
This is a solution for the issue described in https://github.com/ESMValGroup/ESMValCore/issues/1222.
Variables on hybrid vertical levels (e.g. clw) have to be converted to pressure or height levels to be able to be processed by some diagnostics and to be able to calculate meaningful multi-model statistics across different models. For this conversion, some models provide an auxiliary coordinate 'p0'. Calculating the multi-model mean over such datasets converted to pressure or height levels fails because 'p0' is kept after converting the vertical levels but (as expected) not identical in all models. This problem is solved by deleting the scalar auxiliary coordinates p0 and ptop (if present) after converting to pressure or altitude levels.
Closes #1222
It is the responsibility of the author …
> Removed scalar coordinates `p0` and `ptop` prior to merge in `multi_model_statistics`

- .github/workflows/run-tests.yml
- environment.yml
Just addressing my own comment here https://github.com/ESMValGroup/ESMValCore/pull/1476#discussion_r801543931 and going by the gentleman's agreement that we should get as many dependencies off conda-forge as possible
***
*** …
> Move `nested-lookup` dependency to `environment.yml` to be installed from conda-forge instead of PyPi

- esmvalcore/_recipe.py
- tests/__init__.py
- tests/unit/test_recipe.py
Re-adds the attributes `dataset` and `alias` (which many diagnostics rely on) to multi_model_statistics output.
Closes #1480
***
***
> Added `dataset` and `alias` attributes to `multi_model_statistics` output

- CITATION.cff
- doc/changelog.rst
- doc/conf.py
- doc/recipe/preprocessor.rst
Adds first version of the changelog for v2.5.0.
Link to documentation: https://esmvaltool--1476.org.readthedocs.build/projects/ESMValCore/en/1476/changelog.html#v2-5-0
***
***
> Added changelog for v2.5.0 release

- doc/recipe/overview.rst
- esmvalcore/_recipe.py
- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
- tests/unit/test_recipe.py
This PR
- fixes an issue with integer auxiliary time coordinates in the `multi_model_statistics` preprocessor that occurs when preprocessor like `annual_statitics` are used in combination with `multi_model_statistics`.
- Adds the attributes `start_year` and `end_year` to the multi-models statistics output that is needed by many diagnostics.
- Fixes the timerange of multi-models statistics output  when `span=overlap` is used.
Closes #1485
Link to documentation: https://esmvaltool--1486.org.readthedocs.build/projects/ESMValCore/en/1486/recipe/overview.html
***
[1]: …
> Fixed issues with multi-model-statistics timeranges

- .github/workflows/create-condalock-file.yml
Deps change very often and the conda lock file gets updated way too many times with every push on `main` - this is not something bad, since the lock file gets recreated many times (even a day) which is good, but it is rather annoying, and we risk the github-actions bot to be one of our main contributors, which is ridiculous :laughing: 
***
*** …
> turn off conda lock file creation on any push on `main` branch from Github Action test

- esmvalcore/cmor/check.py
Fixes log formatting of CMOR messages.
Closes #1492
***
> Fixed output messages for CMOR logging

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
The default behavior of `iris.cube.Cube.extract()` is to return a scalar coordinate if only a single value is extracted. This causes some NCL diagnostics to fail if `clip_timerange` extracts only single point in time. This PR fixes this behavior.
Closes #1496
***
*** …
> Fixed `clip_timerange` if only a single time point is extracted

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
This PR fixes a bug in the `multi_model_statistics` that caused errors in rare cases (e.g., https://esmvaltool.dkrz.de/shared/esmvaltool/v2.5.0-test-rc2/recipe_smpi_4cds_20220213_125027/run/main_log_debug.txt).
Closes #1499
***
*** …
> Fixed chunking in `multi_model_statistics`

- esmvalcore/_data_finder.py
- esmvalcore/_recipe.py
- esmvalcore/esgf/_search.py
- tests/integration/test_recipe.py
- tests/unit/test_data_finder.py
This PR makes sure that the years in `timerange` are always in the format `YYYY`.
Closes #1515
***
***
> Fixed timerange selection for automatic downloads

- .github/pull_request_template.md
- .github/workflows/run-tests-comment.yml
- doc/contributing.rst
This PR enables the user to turn on running Github Actions tests (the full tests, from `run-tests.yml` workflow) in a Pull Request, just by commenting a string - tagging the bot @runGAtests - before merging; this is very useful since we don't want to add branches to the GA workflow, then remove, forget about removing them etc.
This is a PITA to test since GH wants these workflows to first be on the default branch (`main` in our case) so I emulated the behavior on my fork:
- I have the relevant workflow script in my `main` https://github.com/valeriupredoi/ESMValCore/blob/main/.github/workflows/run-tests-comment.yml
- then I open a PR and comment "@runGAtests" https://github.com/valeriupredoi/ESMValCore/pull/2
- then these little critters go about running …
> [Github Actions] Trigger Github Actions tests (`run-tests.yml` workflow) from a comment in a PR

- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-condalock-file.yml
- .github/workflows/install-from-pypi.yml
- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-comment.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
- doc/recipe/preprocessor.rst
- environment.yml
- package/meta.yaml
- setup.py
See discussion here: https://github.com/ESMValGroup/ESMValTool/issues/2584. On OSX, Python 3.7 is no longer supported by conda-forge.
Closes #1528
***
***
> Dropped Python 3.7

- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
This PR ensures that `start_year` and `end_year` are available for derived variables.
Closes #1546 
***
***
> Added `start_year` and `end_year` attributes to derived variables

- doc/contributing.rst
- environment.yml
- setup.py
As promised before the release, this PR removes the pin to iris<=3.1.0 and sets it to iris>=3.2.1 to allow the use of new features.
***
> Pinned iris>=3.2.1

- doc/contributing.rst
Due to https://github.com/ESMValGroup/ESMValCore/issues/1531 the GA test triggered via PR comment is deactivated but can still be used with two more clicks, so I added a bit of docs on how to do it; I also added a link to the GA hosted runners doc page.
***
*** …
> [Github Actions Docs] Full explanation on how to use the GA test triggered by PR comment and added docs link for GA hosted runners 

- esmvalcore/config-user.yml
This PR adds an entry to the config-user.yml file for Levante. It gives all the paths to the data on Levante. Also, it adds info about a shared directory for the automatically downloaded data (read/write access for members of the ESMValTool development project only). 
I suggest to keep the Mistral entry for as long as the machine is available.
Once this is merged, it would be good to sync with the https://github.com/ESMValGroup/ESMValTool/blob/main/config-user-example.yml
Related to https://github.com/ESMValGroup/ESMValTool/discussions/2631
***
[1]: …
> Add support for DKRZ-Levante

- doc/quickstart/configure.rst
- esmvalcore/_config/_esgf_pyclient.py
- esmvalcore/esgf/_logon.py
- esmvalcore/esgf/_search.py
- esmvalcore/esgf/facets.py
- tests/integration/esgf/test_search_download.py
- tests/unit/config/test_esgf_pyclient.py
- tests/unit/esgf/test_facet.py
- tests/unit/esgf/test_logon.py
- tests/unit/esgf/test_search.py
Closes #1333
Link to documentation: https://esmvaltool--1561.org.readthedocs.build/projects/ESMValCore/en/1561/quickstart/configure.html#search
***
***
> Try searching multiple ESGF index nodes

- esmvalcore/_recipe.py
- tests/sample_data/experimental/test_run_recipe.py
> Show all results on recipe results webpage

- esmvalcore/cmor/_fixes/cmip6/icon_esm_lr.py
- tests/integration/cmor/_fixes/cmip6/test_icon_esm_lr.py
The CMIP6 model ICON-ESM-LR has wrong var_names for latitude and longitude. This PR adds a fix for this.
Note: This is **not** related to the ICON native model CMORizer!
***
> Added `AllVars` fix for CMIP6's ICON-ESM-LR

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_regrid.py
- tests/integration/preprocessor/_regrid/test_extract_point.py
I panicked a little bit while reviewing one of @sloosvel 's PRs dealing with yet another extraction scenario since I thought the extraction process can do extrapolation on top of the known interpolation and we'd end up extracting a point in Italy when the cube only contains Nigeria, in which case data would be absolutely bonkers. It proves out that in that case the code don't fail, but returns fully masked data of the extracted point cube - good - but this is mentioned nowhere! So here it is, mentioned here, and added a test for good measure - even though there was a test for outside points extraction, this one checks specifically for the mask to be full.
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will …
> Tweak `extract_point` preprocessor: explain what it returns if one point coord outside cube and add explicit test 

- doc/api/esmvalcore.iris_helpers.rst
- doc/api/esmvalcore.rst
- doc/conf.py
- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/iris_helpers.py
- esmvalcore/preprocessor/_derive/_shared.py
- esmvalcore/preprocessor/_derive/alb.py
- esmvalcore/preprocessor/_derive/lvp.py
- esmvalcore/preprocessor/_derive/lwp.py
- esmvalcore/preprocessor/_derive/sm.py
- esmvalcore/preprocessor/_derive/vegfrac.py
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/cmor/_fixes/test_shared.py
- tests/unit/test_iris_helpers.py
This PR adds an API documentation for the module `esmvalcore.iris_helpers` deprecates the function `var_name_constraint` in it. It replaces it with iris' [`NameConstraint`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.html#iris.NameConstraint) class.
Note: I didn't remove the appearances of `var_name_constraint` in the ICON CMORizer on purpose since they are fixed in #1549 and I want to avoid merge conflicts.
Closes #1536
Closes #1537
Link to documentation: https://esmvaltool--1592.org.readthedocs.build/projects/ESMValCore/en/1592/api/esmvalcore.iris_helpers.html
***
[1]: …
> Deprecate the function `esmvalcore.var_name_constraint`

- esmvalcore/preprocessor/_derive/amoc.py
- tests/unit/preprocessor/_derive/test_amoc.py
- tests/unit/preprocessor/_derive/test_shared.py
Improving a bit the Amoc derivation script `amoc.py`:
- add optionality for CMIP6 variable that changed name
- add some Value- and iris.Constraint- Errors
- add a test to it ~although I am not 100% happy with the test since it doesn't actually check the computation
but for that I need to assemble a fairly complex cube and know what that Atlantic constraint is - no time now - @ledm can do that~ scratch that it's a boss test for 100% coverage :grin: 
Closes https://github.com/ESMValGroup/ESMValTool/issues/2645
***
[2]: …
> Add CMIP6 `amoc` derivation case and add a test

- esmvalcore/cmor/tables/custom/CMOR_hfns.dat
- esmvalcore/preprocessor/_derive/hfns.py
- tests/unit/preprocessor/_derive/test_hfns.py
This PR adds the derivation of `hfns` also used in the EMAC CMORizer in order to decrease the size of https://github.com/ESMValGroup/ESMValCore/pull/1554.
***
> Added derivation of `hfns`

- .circleci/config.yml
- docker/Dockerfile.dev
Closes #1600
I already uploaded a new docker container [`esmvalgroup/esmvalcore:development`](https://hub.docker.com/layers/esmvalgroup/esmvalcore/development/images/sha256-80e6f76ca0a7e62375f6a4b6b8ba4fd48fe24aec3b13c54cccb17c27822fcdff?context=explore) built from `docker/Dockerfile.dev` in this pull request. Tests in this branch and in #1554 are working as expected again with the new container.
***
***
To help with the number pull …
> Install git and ssh before checking out code on CircleCI

- esmvalcore/cmor/tables/custom/CMOR_MP_BC_tot.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_CFCl3.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_CH4.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_CO.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_CO2.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_ClOX.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_DU_tot.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_N2O.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_NH3.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_NO.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_NO2.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_NOX.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_O3.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_OH.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_S.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_SO2.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_SO4mm_tot.dat
- esmvalcore/cmor/tables/custom/CMOR_MP_SS_tot.dat
- esmvalcore/cmor/tables/custom/CMOR_awhea.dat
- esmvalcore/cmor/tables/custom/CMOR_prl.dat
This PR adds the custom CMOR tables used for the EMAC CMORizer to reduce the size of https://github.com/ESMValGroup/ESMValCore/pull/1554.
***
> Added custom CMOR tables used for EMAC CMORizer

- esmvalcore/config-user.yml
This PR removes the Mistral entry from the `config-user.yml` file because Mistral has just been turned off. Sorry for the last minute PR but it would be good to remove unnecessary lines from the `config-user.yml` for the upcoming release.
Related to https://github.com/ESMValGroup/ESMValTool/discussions/2631
***
~~- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#t …
> Remove support for Mistral in `config-user.yml`

- doc/recipe/overview.rst
- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
This PR adds a check that does not allow to combine `force_derivation: false` and wildcards in the `timerange` tag and should the previous `force_derivation: false` behaviour.
Closes #1626 
***
*** …
> Fix `force_derivation` bug

- doc/changelog.rst
This PR adds the changelog for the first release candidate of v2.6
***
***
> Add changelog for v2.6.0rc1

- doc/develop/fixing_data.rst
- doc/quickstart/configure.rst
- doc/quickstart/find_data.rst
- esmvalcore/cmor/table.py
- esmvalcore/config-developer.yml
- tests/integration/cmor/test_read_cmor_tables.py
- tests/integration/cmor/test_table.py
This PR allows the specification of a custom location for the custom CMOR tables in the `config-developer.yml` file (using the `custom` key).
Closes #1623 
- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/quickstart/find_data.html#datasets-in-native-format
- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/quickstart/configure.html#custom-cmor-tables
- https://esmvaltool--1625.org.readthedocs.build/projects/ESMValCore/en/1625/develop/fixing_data.html#add-support-for-new-native-datasets
***
[1]: …
> Custom user-defined location for custom CMOR tables

- README.md
It's good to have CI Dashboard badges so we can have a bird's eye view of what our CI/CD is doing - @bouweandela pointed me to a dashboard from Circle, so I thought I'd have a go at a dash from Github Actions - proves out GA don't have a native dashboard so I found meercode.io offers a very decent integration (not only for GA) - can one of you @bouweandela @zklaus @schlunma please test if the badge is leading to the correct dashboard - it does for me, but I am registered with meercode, so not sure if that's working overall. Cheers :beer: 
**UPDATE at point of moving it to Ready for Review**
Folks see plots and stats and all manners of dashboard-y stuff if they click on the Meercode badge, and autheticate with GitHub. Do we need documentation for this? I think we're fine like this -
> Test Github Actions dashboard badge from meercode.io

- tests/unit/esgf/test_search.py
If `FIRST_ONLINE_INDEX_NODE` was already set to a URL by some other code, the unit tests of `esmvalcore.esgf.find_files` would fail as these depended on it being set to `None`. This pull request ensures it is always set to `None` before these tests are started.
Closes #1649
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) …
> Improve esmvalcore.esgf unit test

- doc/changelog.rst
See https://github.com/ESMValGroup/ESMValTool/issues/2704#issuecomment-1178956231
Link to documentation: https://esmvaltool--1658.org.readthedocs.build/projects/ESMValCore/en/1658/changelog.html#deprecations
***
***
> Expanded information on deprecations in changelog

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Temporarily fixes test failures noted in https://github.com/ESMValGroup/ESMValCore/issues/1655
Does not offer a long-term fix. That should be included after the 2.6.0 release.
***
> Pin cf-units to lower than 3.1.0 to temporarily avoid changes within new version related to calendars

- setup.py
Closes #1696 
Issues with the latest version of `flake8` (>5) - not 100% what's happening at flake8 end, the PyCQA devs are not very keen on telling us much
***
***
> pin `flake8<5.0.0` since Circle CI tests are failing copiously

- doc/develop/fixing_data.rst
- esmvalcore/cmor/_fixes/emac/_base_fixes.py
- esmvalcore/cmor/_fixes/emac/emac.py
- esmvalcore/cmor/_fixes/icon/_base_fixes.py
- esmvalcore/cmor/_fixes/icon/icon.py
- esmvalcore/cmor/_fixes/native_datasets.py
- tests/integration/cmor/_fixes/emac/test_emac.py
- tests/integration/cmor/_fixes/icon/test_icon.py
- tests/integration/cmor/_fixes/test_native_datasets.py
This PR simplifies native model fixes by adding a base class `NativeDatasetFix` with common operations necessary for almost all datasets. This will dramatically simplify https://github.com/ESMValGroup/ESMValCore/pull/1678.
Closes #1690
Link to documentation: https://esmvaltool--1694.org.readthedocs.build/projects/ESMValCore/en/1694/develop/fixing_data.html#fix-native-data
***
***
- 🙏 We kindly ask …
> Refactored native model fixes by adding common base class `NativeDatasetFix`

- .github/workflows/run-tests-monitor.yml
- esmvalcore/cmor/_fixes/native_datasets.py
#1694 added type annotations that are only available since Python 3.9; thus, [tests are failing with Python 3.8](https://github.com/ESMValGroup/ESMValCore/actions/runs/2868811592). This PR fixes this.
*** …
> Fixed type annotations for Python 3.8

- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
Closes #1716
The introduction of scalar cubes in iris complicates a number of things, including our advanced concatenation mechanism - it is possible, as seen from the test case changed in this PR, that along the path of concatenation as we do it, one of the processed cubes that we use as intermediary laison to be *scalar* - then the whole show crumbles. I am not a fan of scalar cubes as they are defined in iris, but that's for another day. Anyway, this PR fixes that particular corner case, and adds a test case (converts the previous test case to a more meaningful one, that is). 
All started from @bouweandela 's [comment](https://github.com/ESMValGroup/ESMValCore/pull/1713#issuecomment-1236850683) - cheers, Bouwe! :beer: 
***
It is the responsibility of the author to make sure the pull …
> Core `_io.concatenate()` may fail due to case when one of the cubes is scalar - this fixes that

- esmvalcore/_config/extra_facets/ipslcm-mappings.yml
- esmvalcore/config-developer.yml
- tests/integration/data_finder.yml
- tests/integration/test_data_finder.py
While coding for #1678 I realized that we currently don't have any tests for input file names/input directories/output files for the EMAC and ICON on-the-fly CMORizers. This PR adds those. In additon, I slightly adapted the output file name for EMAC to make it consistent with CMIP data.
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-r …
> Added tests for input/output filenames for ICON and EMAC on-the-fly CMORizer

- environment.yml
- setup.py
Closes #1723 
SegFaults galore - we all love 'em :grin: 
***
***
> Pin `netCDF4 != 1.6.1` since that seems to throw a flurry of Segmentation Faults

- README.md
Am a bit baffled this has been like this for eons. Maybe it got put there on purpose, but the purpose is lost on me. Anyway, the Tool docs are failing very frequently now (all the time actually) because the mapgenerator/matplotlib issue - we have a fix for that, but it's not yet merged.
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pu …
> pick up esmvalcore badge instead of esmvaltool one in README

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_regrid.py
- tests/unit/preprocessor/_regrid/test_extract_levels.py
Blast! Nearly forgot about these guys :no_bicycles: 
***
***
> Remove deprecation warning for regrid schemes already deprecated for v2.7.0

- esmvalcore/_config/extra_facets/emac-mappings.yml
- esmvalcore/cmor/_fixes/emac/emac.py
- tests/integration/cmor/_fixes/emac/test_emac.py
A colleague of us informed us about a slight error in the calculation of the precipitation rate in EMAC. It should be aprc + aprl, right now we use aprc + aprl + aprs. This PR fixes that.
@valeriupredoi it would be really nice if this PR made it into the new relaese, so our colleagues can use it with the Levante module (which always uses the latest version). Since it's just a very minor chance I hope that's not a problem. Cheers! 🍺 
*** …
> Fix calculation of precipitation flux in EMAC on-the-fly CMORizer

- CITATION.cff
The bogstandard update of CITATION.cff for 2.7.0 release, please :beer:
> update CITATION.cff file with 2.7.0 release info

- CITATION.cff
- doc/changelog.rst
This is a bit of a departure from our usual way of updating the changelog, but I had to add a couple items to the Changelog in the [release branch](https://github.com/ESMValGroup/ESMValCore/tree/release_270stable) - the update of the changelog from #1746 and @schlunma 's very useful #1755 - I could have waited for a final final approval and only then moving it to the release branch, but given it's just two itty bitty changelog changes I'd rather get it done with the Core stable release :grin: 
This will be the first documentation entry for v2.8.0 yay!
***
[1]: …
> updating changelog and CITATION in main to reflect files from 2.7.0 release

- README.md
> fix anaconda badge in README

- esmvalcore/esgf/_download.py
- esmvalcore/esgf/_search.py
There is a mistake in the docstring of `esmvalcore.esgf.find_files`. The function is called `search` in the docstring, where it should be `find_files`. This pull request corrects the issue.
Link to documentation: https://esmvaltool--1784.org.readthedocs.build/projects/ESMValCore/en/1784/api/esmvalcore.esgf.html#esmvalcore.esgf.find_files
***
*** …
> Fix mistake in the documentation of `esmvalcore.esgf.find_files`

- .github/workflows/run-tests.yml
- esmvalcore/_task.py
- setup.cfg
Suggested by @zklaus in https://github.com/ESMValGroup/ESMValCore/pull/1787#pullrequestreview-1176952599 which this PR supersedes #1787 
Closes #1788 
***
***
> set implicit optional to true in mypy config to avert side effects and test fails from new mypy version

- setup.cfg
Thanks @zklaus for noticing this :beer: 
***
***
> remove duplicate implicit_optional = True line in setup.cfg

- .github/workflows/run-tests.yml
- tests/sample_data/experimental/test_run_recipe.py
The tests in `tests/sample_data/experimental/test_run_recipe.py` are failing occasionally because the data cannot be found. This pull request changes the tests so they use their own configuration instead of the global tool configuration. With a bit of luck, this might solve the issue.
Closes #1793
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#r …
> Fix failing test due to missing sample data

- setup.cfg
- tests/integration/data_finder.yml
This removes the `cmor_table` facet from the esmvalcore/_data_finder.py tests. A long time ago, the CMOR table could be different from the project. This is no longer the case, so it can be removed.
This also adds `hist` to the list of ignored spelling mistakes, because that raised incorrect warnigns with the pre-commit hook for codespell while trying to commit this change.
Part of #1609
***
***
- 🙏 …
> Remove outdated cmor_table facet from data finder tests

- environment.yml
- setup.py
Pin netCDF4 < 1.6.1
See #1723, https://github.com/ESMValGroup/ESMValTool/issues/2924, https://github.com/SciTools/iris/issues/5016
***
***
> Pin netCDF4<1.6.1

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Unpin NetCDF4 because this pin was needed because of an `iris` issue that has now been taken care of by `iris`.
Ongoing efforts to avoid effects described in #1727 (do not kill that issue BTW, it's needed to have contact with iris folks until things get sorted out correctly on their side). Done the same in Tool https://github.com/ESMValGroup/ESMValTool/pull/2929
***
*** …
> Unpin NetCF4

- esmvalcore/_main.py
- tests/unit/main/test_esmvaltool.py
If the output directory already exists the tool would stop. Now it will try several alternatives by adding a suffix `-1`, `-2,`, etc before giving up. This problem occurs when you try to run multiple recipes with the same name in parallel.
Closes #1817
***
*** …
> Create a session directory with suffix "-1", "-2", etc if it already exists

- esmvalcore/preprocessor/_regrid.py
- esmvalcore/preprocessor/_regrid_esmpy.py
- tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
This PR adds missing scalar coordinates of the input cubes to the output of `esmpy_regrid` and fixes a bunch of Codacy issues in the corresponding files.
Closes #1810 
***
***
> Added scalar coords of input cubes to output of esmpy_regrid

- .circleci/config.yml
- .github/workflows/create-condalock-file.yml
- .github/workflows/install-from-condalock-file.yml
- .github/workflows/run-tests-comment.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
- setup.cfg
- tests/integration/cmor/_fixes/test_common.py
- tests/integration/cmor/_fixes/test_shared.py
Let's see if indeed SegFaults that we used to see are now gone (bar, of course, the ones - many of them - from netCDF>1.6.0 + iris). Don't merge this just yet (hence draft, I'd like to run a few of these test sets).
***
*** …
> No more sequential tests since SegFaults were not noticed anymore (knock on wood)

- esmvalcore/preprocessor/_mask.py
- tests/integration/preprocessor/_mask/test_mask.py
This PR fixes a severe bug which lead to a wrong masking of data with `mask_fillvalues` if the data contains zeros. This has already been discussed [2 years ago](https://github.com/ESMValGroup/ESMValCore/issues/487#issuecomment-677732121) and has recently lead to problems.
I also fixed some prospector issues along the way.
Related to #487
***
*** …
> Fix severe bug in `mask_fillvalues`

- esmvalcore/esgf/_search.py
This enables the graceful handling of more types of failure to connect to an esgf index node.
Closes #1833
***
***
> Improve error handling if an esgf index node is offline

- esmvalcore/cmor/_fixes/icon/icon.py
- esmvalcore/config/extra_facets/icon-mappings.yml
- tests/integration/cmor/_fixes/icon/test_icon.py
- tests/integration/test_recipe.py
Currently, the ICON on-the-fly CMORizer derives liquid water path (LWP) as `clwvi` minus `clivi`. However, for ICON, LWP = `cliwvi`. This PR fixes that.
***
> Fix LWP of ICON on-the-fly CMORizer

- esmvalcore/preprocessor/_regrid_esmpy.py
https://github.com/ESMValGroup/ESMValCore/pull/1811 introduced the addition of scalar coordinate to the output of the irregular regridding. However, by mistake, I read the scalar coordinates from the source **representant**, not the source cube itself. Since the **representant** is the result of slicing the source, it potentially contains many (unwanted) scalar coordinates and also leads to the bug described in https://github.com/ESMValGroup/ESMValCore/issues/1844.
This PR fixes that.
Closes #1844
***
[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical-r …
> Fixed issue in irregular regridding regarding scalar coordinates

- pyproject.toml
This sets the version number on the `main` and feature branches so it starts with `v2.8.0.dev` (considering that the current release is `v2.7.0`). To make a release branch for a previous release, call it `v2.7.x` and the version number will be automatically correct (e.g. something starting with `v2.7.1-dev` if branched of the `v2.7.0` tag). This approach avoids the need to merge micro releases back into the `main` branch just to get the version number right.
@ESMValGroup/technical-lead-development-team 
See https://pypi.org/project/setuptools-scm/ for the details.
***
[1]: …
> Set the version number on the development branches to one minor version more than the previous release

- tests/integration/preprocessor/_regrid/test_regrid.py
Port feature (test fix that would fail with iris=3.4) from PR https://github.com/ESMValGroup/ESMValCore/pull/1846 to v2.5.1 bugfix release
> [v2.7.1 bugfix release] remove unnecessary test in regrid to allow install of iris 3.4 - feature from PR 1846

- esmvalcore/cmor/_fixes/cmip6/kiost_esm.py
- tests/integration/cmor/_fixes/cmip6/test_kiost_esm.py
The KIOST-ESM model (CMIP6) contains in the siconc field NaNs instead of missing_values. This will be fixed here.
Closes #1828 
***
> Fix siconc in KIOST-ESM

- pyproject.toml
Porting changes by @bouweandela in #1854 to v2.7.1 bugfix release :beer:
> [v2.7.1 bugfix release] Add sematic versioning: set the version number on the development branches to one minor version more than the previous release

- doc/changelog.rst
- pyproject.toml
Add Changelog for v2.7.1 (V's own creation) and semantic versioning from PR #1854 
Added [changelog](https://esmvaltool--1858.org.readthedocs.build/projects/ESMValCore/en/1858/changelog.html)
> [v2.7.1 bugfix release] Finalize v2.7.1 bugfix: add changelog for v2.7.1 bugfix release

- esmvalcore/cmor/_fixes/emac/emac.py
The applied changes add the default variable name of EMAC to the derived variables included in _fixes/emac/emac.py (without the _ave). 
I decided to put the default variable name (without _ave) last, since the _ave is most often used to derive monthly means. If both variable are available, the monthly average calculated by the model itself is used instead of the average of the instantaneous output produced by post-processing. Although there should not be a difference in most cases.
[2]: …
> Add standard variable names for EMAC

- esmvalcore/preprocessor/_regrid_esmpy.py
- tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
> Update esmpy import for ESMF v8.4.0

- esmvalcore/esgf/_search.py
- tests/unit/esgf/test_search.py
> Improve resilience of ESGF search

- esmvalcore/esgf/_search.py
- esmvalcore/local.py
- tests/unit/local/test_select_files.py
> Fix issue with no files found if timerange start/end differs in length

- esmvalcore/_recipe.py
- tests/integration/test_recipe.py
This pull requests adds addintional keys to create unique aliases for CORDEX datasets and datasets with a sub_experiment tag.
Closes #1885 
***
~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~
*** …
> Add `driver` and `sub_experiment` tags to generate dataset aliases

- esmvalcore/esgf/_download.py
- tests/unit/esgf/test_search.py
Closes #1861
Closes #1862
***
***
> Fix issues with searching for files on ESGF

- doc/quickstart/find_data.rst
Add a description how to use the `extract_levels` preprocessor on native ICON data.
Related to https://github.com/ESMValGroup/ESMValTool/pull/3016#issuecomment-1398424930
Link to documentation: https://esmvaltool--1903.org.readthedocs.build/projects/ESMValCore/en/1903/quickstart/find_data.html#icon
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html# …
> Updated ICON doc with information on usage of extract_levels preprocessor

- esmvalcore/cmor/check.py
- tests/unit/cmor/test_cmor_check.py
The usage of lazy coordinate arrays in the CMOR checker of #1912 broke the automatic fix of longitudes not in [0, 360] for multidimensional arrays here:
https://github.com/ESMValGroup/ESMValCore/blob/745bb6ffaf6dc2985f7bf19e696718453c9cfd9f/esmvalcore/cmor/check.py#L798-L802
Error:
```
Traceback (most recent call last):                                                                                                                                                                                                                                            
File "/work/bd0854/b309141/mambaforge/envs/esm/lib/python3.10/site-packages/dask/array/core.py", line 1889, in __setitem__ …
```
> Fixed `set_range_in_0_360` for dask arrays

- esmvalcore/preprocessor/_multimodel.py
- tests/unit/preprocessor/_multimodel/test_multimodel.py
This PR allows the usage of the `multi_model_statistics` on cubes with identical `name()` and `units` but potentially different `var_name` and `long_name` (these will be set to `None` in these cases). Due to the way [`Cube.name()`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/common/mixin.html#iris.common.mixin.CFVariableMixin.name) works, different `standard_names` will **NEVER** be merged (because the `name()` of these will always differ).
Similar to https://github.com/ESMValGroup/ESMValCore/pull/1813/, but for cube names instead of coordinate names.
Link to documentation: https://esmvaltool--1921.org.readthedocs.build/projects/ESMValCore/en/1921/api/esmvalcore.preprocessor.html?highlight=multi_model_stat#esmvalcore.preprocessor.multi_model_statistics
***
It is the …
> Allowed usage of `multi_model_statistics` on cubes with identical `name()` and `units` (but e.g. different long_name)

- doc/quickstart/find_data.rst
- environment.yml
- esmvalcore/cmor/_fixes/icon/_base_fixes.py
- esmvalcore/cmor/_fixes/icon/icon.py
- setup.py
- tests/integration/cmor/_fixes/icon/test_icon.py
After extensive testing of the ICON on-the-fly CMORizer with the new UGRIDization (thanks @Paulinebonnet111!!) we discovered two issues with this:
1. The automatic download of the grid file can lead to corrupted nc files when initiated from multiple processes (this happens with `max_parellel_tasks` > 1) at the same time.
2. Some diagnostics cannot handle UGRID data (yet). An example is the [Psyplot diagnostic](https://docs.esmvaltool.org/en/latest/api/esmvaltool.diag_scripts.psyplot_diag.html?highlight=psyplot#module-esmvaltool.diag_scripts.psyplot_diag).
This PR fixes these issues by
1. introducing a [`filelock`](https://py-filelock.readthedocs.io/en/latest/index.html) before attempting to download the grid file. I also added a smarter caching of the mesh to the CMORizer, which reduces …
> Fix automatic download of ICON grid file and make ICON UGRIDization optional (default: true)

- esmvalcore/esgf/_download.py
- esmvalcore/esgf/facets.py
- tests/integration/esgf/search_results/expected.yml
- tests/integration/esgf/search_results/historical_gn_r4i1p1f1_CMIP6_CESM2_Amon_tas.json
- tests/integration/esgf/search_results/obs4MIPs_GPCP-V2.3_pr.json
- tests/integration/esgf/test_search_download.py
Improve the way facets are read from the ESGF search results and use them to create the local directory structure. This results in more cases where the facets are available and fixes an issue with the obs4MIPs directory where a `.` in the dataset name was interpreted as a `/` when creating the local file path.
***
To try out the improved facets, run
```python
from esmvalcore.esgf import find_files
files = find_files(
short_name='tas',
mip='Amon',
project='CMIP5',
dataset='*',
institute='*',
ensemble='r1i1p1',
exp='historical',
timerange='2000/2000',
)
for file in files:
print(file) …
```
> Improve reading facets from ESGF search results

- esmvalcore/cmor/_fixes/cmip6/fgoals_f3_l.py
- tests/integration/cmor/_fixes/cmip6/test_fgoals_f3_l.py
FGOALS-f3-L clt has unit %, values are <= 1 in ssp585 simulation.
Closes #1927 
***
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
~~- [ ] [🛠][1] The [list of authors](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#list-of-authors) is up to date~~
> Fix for FGOALS-f3-L clt

- doc/recipe/overview.rst
This is a simple fix to improve the formatting of the time range docs. Follow the documentation link below and scroll to the timerange examples. In [the current version of the docs](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/overview.html#recipe-section-datasets), the nested lists are not detected by Sphinx and the resulting documentation is hard to read. This PR replaces the nested lists with an overview table. An alternative version to fix the issue fixes the nested lists, see #1941. Only one of #1940 and #1941 should be merged.
Closes #1939. Alternative implementation to #1941.
Link to documentation: https://esmvaltool--1940.org.readthedocs.build/projects/ESMValCore/en/1940/recipe/overview.html#recipe-section-datasets
***
It is the responsibility of the author to …
> Replace timerange nested lists in docs with overview table

- esmvalcore/config/extra_facets/cmip5-institutes.yml
- tests/unit/test_dataset.py
This adds the institute name `CCCMA` used on ESGF for the CMIP5 datasets CanAM4, CanCM4, and CanESM2. Without this institute name, the tool is not able to find the files for these datasets on ESGF.
***
*** …
> Add institute name used on ESGF for CMIP5 CanAM4, CanCM4, and CanESM2

- esmvalcore/cmor/_fixes/cmip6/bcc_csm2_mr.py
- tests/integration/cmor/_fixes/cmip6/test_bcc_csm2_mr.py
This PRs applies the `OceanFixGrid` to the `areacello` of the BCC-CSM2-MR model. That is needed for https://github.com/ESMValGroup/ESMValTool/pull/3021. 
***
***
> Fix areacello in BCC-CSM2-MR

- tests/integration/preprocessor/_regrid/test_extract_location.py
Use a mocked version of `geopy.geocoders.Nominatim` to avoid `ReadTimeoutError`.
Closes https://github.com/ESMValGroup/ESMValCore/issues/1982
***
***
> Use mocked `geopy.geocoders.Nominatim` to avoid `ReadTimeoutError`

- esmvalcore/cmor/_fixes/icon/icon.py
- tests/integration/cmor/_fixes/icon/test_icon.py
Fixed an issue with the ICON hourly fix_time function to get rid of some falsly hourly data, cause of rounding issues with the day fraction format ICON used, e.g. got 13:59:59 instead of 14:00:00 and also changed the test file to get exactly that tested.
*** …
> Fix: Icon hourly data rounding issues

- esmvalcore/cmor/_fixes/cesm/cesm2.py
- esmvalcore/cmor/_fixes/emac/emac.py
- esmvalcore/cmor/_fixes/icon/icon.py
- esmvalcore/cmor/_fixes/native_datasets.py
- esmvalcore/cmor/table.py
- tests/integration/cmor/_fixes/cesm/test_cesm2.py
- tests/integration/cmor/_fixes/emac/test_emac.py
- tests/integration/cmor/_fixes/icon/test_icon.py
- tests/integration/cmor/_fixes/test_native_datasets.py
- tests/unit/cmor/test_table.py
CMIP6 provides [multiple](https://github.com/ESMValGroup/ESMValCore/blob/576a5bb3a57678ec8c9a5fcf89fc62d5d1ef9c4b/esmvalcore/cmor/tables/cmip6/Tables/CMIP6_coordinate.json#L2213) time dimensions, e.g., `time`, `time1`, etc. They all have the common standard name `time`.
Currently, we are using the dimension name (`time`, `time1`, ...) to identify coordinates in fixes. This PR introduces a convenience method `VariableInfo.has_coord_with_standard_name` to identify coordinates through their `standard_name`.
Closes #1969 
Link to documentation: https://esmvaltool--1971.org.readthedocs.build/projects/ESMValCore/en/1971/api/esmvalcore.cmor.html?highlight=has_dimension#esmvalcore.cmor.table.VariableInfo.has_coord_with_standard_name
***
It is the responsibility of the author to make sure the pull …
> Make time-related fixes work with time dimensions `time1`, `time2`, `time3`

- esmvalcore/cmor/_fixes/icon/_base_fixes.py
Currently, the ICON on-the-fly CMORizer might fail if a user does not already have the `$HOME/.esmvaltool/cache` directory. The relevant `mkdir` is called *AFTER* the first usage of this cache directory. This PR fixes that. 
*** …
> Make sure to always create cache directory when using ICON grid files

- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-condalock-file.yml
- .github/workflows/install-from-pypi.yml
- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-comment.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Drop support for Python 3.8 because [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommends that we drop support for Python 3.8 on Apr 14, 2023.
Closes #1995
***
*** …
> Drop support for Python 3.8

- README.md
Sister PR to Tool's https://github.com/ESMValGroup/ESMValTool/pull/3185 - our nice and happy logo has disappeared off the PyPI pkg page, most probably since we don't link it from the RAW file on the README
***
*** …
> Show ESMValTool logo on PyPI webpage

- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-pypi.yml
Now that we have esmvalcore=2.8.1 out and supporting python=3.11 we need to add py311 to GA tests running installs from deployed packages. @bouweandela pls include this in the bugfixes category, so we can have it for 2.9.0rc1 or 2.9.0stable, depending what you choose do, bud :beer: 
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-r …
> add python 3.11 to github actions tests installing deployed packages (conda and PyPI)

- esmvalcore/preprocessor/_regrid.py
- tests/unit/preprocessor/_regrid/test_regrid.py
In #968 a rechunking step was introduced if the target grid resolution was considerably higher than the source grid. However, it failed to take into account that the target grid could have more dimensions than just latitude and longitude. This pull request fixes the issue.
Closes #2085
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pul …
> Fix regridding issue where target grid is more than 2D

- esmvalcore/_citation.py
- tests/unit/test_citation.py
Very small change that correctly handles bibtex references that include `-`, as is the case for many bibtex files in `esmvaltool/references`.
Closes #2092 
Required to fix warnings arising from https://github.com/ESMValGroup/ESMValTool/pull/3197#issuecomment-1589813326
Link to documentation: https://esmvaltool--2097.org.readthedocs.build/projects/ESMValCore/en/2097/ (no change)
***
***
- 🙏 We …
> Include `-` in allowed characters for bibtex references

- esmvalcore/preprocessor/_io.py
Avoid realizing data in preprocessor function concatenate when cubes overlap.
***
***
> Avoid realizing data in preprocessor function `concatenate` when cubes overlap

- esmvalcore/esgf/_search.py
- tests/unit/esgf/test_search.py
> Do not raise an exception if the requested version of a file is not available for all matching files on ESGF

- esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py
- tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg.py
Converts the EC-Earth3-Veg tos calendar to `proleptic_gregorian` to make it possible to concatenate the historical experiment with the ssp126 experiment.
See #1731
***
***
> Add fix for EC-Earth3-Veg tos calendar

- setup.py
~There is an issue with prospector=1.10.2 at the moment and installing it with `with_mypy` makes it not work at all, so I am removing this extra tool for now, so we have some functionality out of it, rather than a complete shutdown;~
~Nevermind, `prospectpr=1.10.2` needs `with-mypy` instead of `with_mypy` due to `poetry` changing version, and @carlio (the prospector main dev) tells me this may change in the future again, depending how poetry wakes up in the morning (what version it is one)~
@bouweandela suggested we remove the extra tool option altogether since we run the mypy tests separately anyway :+1: 
See https://github.com/landscapeio/prospector/issues/624
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item …
> remove `with_mypy` or `with-mypy` extension/optional tool for prospector

- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_io.py
Follow up on #2103. This reduces duplicate code and avoids a potential crash if for some reason `recipe_dataset_index` would not be set (which seems unlikely).
***
***
> Improve preprocessor output sorting code

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_regrid.py
- tests/unit/preprocessor/_regrid/test_regrid.py
This PR removes the discontinuity check on the grid because iris.util.find_discontiguities realises the auxiliary coordinates 
Closes #2117 
***
***
> Remove coord discontinuity check in regrid

- setup.py
During testing for the v2.9.0 release of ESMValTool, we noticed that the latest versions of iris are considerably less performant with the Dask default scheduler. Therefore it would be good to allow using older versions of iris, even if these do not support the distributed scheduler. Note that a new installation will still default to the latest version of iris, so this is only for users who really want to use the older version.
See discussion in https://github.com/ESMValGroup/ESMValTool/issues/3239#issuecomment-1613298587
***
[1]: https://docs.esmvaltool.org/en/latest/community/review.html#technical …
> Relax the pin on iris to allow the use of older versions for performance reasons

- environment.yml
Just a very quick PR to clean up the way pins are written in the environment file
***
***
> clean-up how pins are written in conda environment file

- .github/workflows/create-condalock-file.yml
- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-condalock-file.yml
- .github/workflows/install-from-pypi.yml
- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-comment.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
This specifies the shell definition (bash, in this case) in a `defaults` section of the GA workflow, and more importantly, does this only once so that everytime a new command is added (via `run` key), one doesn't have to keep adding the bash definition above it; this makes the workflow a lot more readable; originally suggested by @bouweandela :beer: 
Closes #2031 
***
*** …
> [Github Actions] Compress all bash shell setters into one default option per workflow

- .github/workflows/run-tests-monitor.yml
For some reason the monitor tests GA workflow got a yaml syntax error, this made the test unusable, this fixes it.
Closes #2134 
***
***
> [Github Actions] Fix Monitor Tests Github Action

- .github/workflows/create-condalock-file.yml
~conda-lock=2.1.0 has issues building our lockfile, so interim solution is to pin it to 2.0.0 that is known to work well.~
This is a slightly more complex issue: conda/mamba as they get shipped via the setup-miniconda@v2 action are old (will have to do a thorough check for all our actions), so updating via conda update is not doing anything. Forcing a modern mamba updates conda too, and latest conda-lock==2.1.0 (or 2.1.1 as of today) then works well. The problem about conda/mamba being old is a persistent one, and endemic to all our GA tests that use the setup-miniconda@v2, I reported it in #2138 and I will have to do something about it.
For now, the solution here does the trick:
- update mamba manually right before installing conda-lock, that in turn, force-updates the base conda
- the …
> [Condalock] make sure mamba/conda are at latest version by forcing a pinned mamba install

- doc/quickstart/find_data.rst
- esmvalcore/cmor/_fixes/native6/era5.py
- esmvalcore/cmor/_fixes/native6/era5_land.py
- tests/integration/cmor/_fixes/native6/test_era5.py
Change sign of evspsbl and evspsblpot to have the same direction as CMIP models. Added both variables for ERA5_land.
For ERA5 evapotranspiration and potential evapotranspiration are negative, if they go from the surface into the atmosphere for CMIP models they are positive:
According to the description of Evapotranspiration on the Copernicus page (https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-monthly-means?tab=overview): 
> The ECMWF Integrated Forecasting System (IFS) convention is that downward fluxes are positive. Therefore, negative values indicate evaporation and positive values indicate condensation.
In the CMOR table, these fluxes are defined as positive, if they go from the surface into the atmosphere:
>  Evaporation at surface (also known as …
> ERA5 on-the-fly CMORizer: changed sign of `evspsbl` and `evspsblpot`

- esmvalcore/_recipe/from_datasets.py
- tests/unit/recipe/test_from_datasets.py
> Fix sorting of ensemble members in `esmvalcore.dataset.datasets_to_recipe`

- esmvalcore/cmor/check.py
This PR avoids the realisation of bounds for auxiliary coordinates, by calling coord.core_bounds() instead of coord.bounds()
Closes #2145 
***
~- [x] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~
~- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~ …
> Call coord.core_bounds() instead of coord.bounds in `check.py`

- .readthedocs.yaml
The library `zstd` and its Python binding `zstandard` must be installed in compatible versions. Proper pinning was added to the Conda-forge packages recently (see https://github.com/conda-forge/zstandard-feedstock/pull/48, https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/484), but for some reason that doesn't get picked up by our setup. As a stop-gap solution to get our builds running again, I am here adding a pin to the matching versions of the packages.
Closes #2203 
***
[2]: …
> Ensure compatible zstandard and zstd versions for .conda support

- esmvalcore/_recipe/recipe.py
- esmvalcore/dataset.py
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_load.py
- tests/integration/preprocessor/test_preprocessing_task.py
- tests/integration/recipe/test_recipe.py
- tests/unit/recipe/test_recipe.py
- tests/unit/test_dataset.py
Remove the deprecated argument ``callback`` from the preprocessor function [``load``](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.load).
Upgrade instructions: use [`esmvalcore.dataset.Dataset.load()`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.dataset.html#esmvalcore.dataset.Dataset.load) instead. 
Closes #1800
***
***
To help with the …
> Remove deprecated callback argument from preprocessor ``load`` function

- .circleci/config.yml
Update the [CircleCI orbs](https://circleci.com/developer/orbs) for reporting code coverage to a more recent version.
***
***
> Update code coverage orbs

- esmvalcore/_main.py
- esmvalcore/config/_config_validators.py
- tests/integration/test_deprecated_config.py
- tests/integration/test_main.py
This PR removes the deprecated configuration option `offline`.
Detailed upgrade instructions: https://github.com/ESMValGroup/ESMValCore/pull/1935
***
> Removed deprecated configuration option `offline`

- esmvalcore/cmor/_fixes/cmip6/iitm_esm.py
- esmvalcore/cmor/_fixes/cmip6/kace_1_0_g.py
- esmvalcore/cmor/_fixes/fix.py
- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/cmor/fixes.py
- esmvalcore/preprocessor/_time.py
- tests/integration/cmor/_fixes/test_shared.py
- tests/unit/cmor/test_fixes.py
- tests/unit/cmor/test_generic_fix.py
This PR adds `esmvalcore.cmor.fixes.get_time_bounds` and `esmvalcore.cmor.fixes.get_next_month`.
***
> Added `get_time_bounds` and `get_next_month` to public API

- esmvalcore/preprocessor/_io.py
In `concatenate` cubes are cropped using only the date and not the time. In some cases, this leads to losing a time point between two cubes, resulting in a CMOR check failure. This happens since https://github.com/ESMValGroup/ESMValCore/pull/2144.
Closes #2239
***
*** …
> Fix `concatenate` preprocessor function

- doc/conf.py
RTD are now introducing a deprecation [warning](https://readthedocs.org/projects/esmvalcore/builds/22341626/) so the buids fail on that warning. They say we should add that to that dict - frankly, I don't know why that'll be default False, it makes no sense not to be able to navigate with keys, but heyho. [Docs](https://esmvaltool--2245.org.readthedocs.build/projects/ESMValCore/en/2245/) build fine and dandy now! :beer: 
***
***
To help …
> Add `navigation_with_keys: True` to `html_theme_options` in Readthedocs `conf.py`

- esmvalcore/preprocessor/_io.py
> Fix time overlap handling in concatenation

- CITATION.cff
- doc/changelog.rst
- doc/recipe/preprocessor.rst
Update release version and add changelog for the upcoming v2.10.0 release.
Link to documentation: https://esmvaltool--2249.org.readthedocs.build/projects/ESMValCore/en/2249/changelog.html#v2-10-0
***
*** …
> Add changelog and update version number for v2.10.0rc1

- esmvalcore/local.py
- tests/unit/local/test_get_rootpath.py
>  Improve the exception message when an option within the rootpath section is missing from the user configuration file

- environment.yml
Temporarily pin Python to lower than 3.12 until the issue with prospector/flake8 is resolved. See https://github.com/ESMValGroup/ESMValCore/pull/2228#issuecomment-1825779348.
Once this is merged and the new docker container is built, it should fix the failing tests on CircleCI for now.
Closes #2271
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html# …
> Pin Python to lower than 3.12

- .github/workflows/build-and-deploy-on-pypi.yml
- setup.py
This is us going forward and keeping up with the newest trends, and a big thank you to @bouweandela suggesting this to me for a different package. This is a simple, token-free, password-free secure method to upload the Python package to PyPI; it's described in https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/ and setup explained in https://docs.pypi.org/trusted-publishers/adding-a-publisher/ - but, in a nutshell, it goes like this:
- once the pkg has been built, the GA workflow uses a PyPA workflow that uploads it to PyPI, *if and only if*...
- an owner of the PyPI project enables Trusted Publishers on the PyPI project page (in settings etc)
This is the changed GA workflow at our end, for this to be enabled (note that the Python setup action has been upgraded to v4, …
> make build and deploy to PyPI Github Action use PyPI's new trusted publishers authentication

- esmvalcore/_recipe/recipe.py
This PR makes sure that supplementary variables are shown explicitly in the debug log.
Before:
```bash
2024-01-17 10:30:37,879 UTC [504383] DEBUG   esmvalcore._recipe.recipe:263 Using input files for variable tas of dataset CMIP6 BCC-ESM1:
/work/bd0854/DATA/ESMValTool2/download/CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Amon/tas/gn/v20181214/tas_Amon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/BCC/BCC-ESM1/1pctCO2/r1i1p1f1/fx/areacella/gn/v20190613/areacella_fx_BCC-ESM1_1pctCO2_r1i1p1f1_gn.nc
/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/CMIP/BCC/BCC-ESM1/1pctCO2/r1i1p1f1/fx/sftlf/gn/v20190613/sftlf_fx_BCC-ESM1_1pctCO2_r1i1p1f1_gn.nc
```
After:
```bash
2024-01-17 10:19:03,774 UTC [447883] DEBUG   esmvalcore._recipe.recipe:272 Using input …
```
> Show files of supplementary variables explicitly in log

- doc/quickstart/configure.rst
- doc/recipe/preprocessor.rst
- esmvalcore/cmor/table.py
- tests/integration/cmor/test_table.py
If a derived variable is present in the CMOR tables, but not in the `mip` specified in the recipe, look it up in other `mip`s. This avoids the need to create custom CMOR tables for such cases.
Updated docs: https://esmvaltool--2256.org.readthedocs.build/projects/ESMValCore/en/2256/recipe/preprocessor.html#variable-derivation
***
*** …
> Read derived variables from other MIP tables

- esmvalcore/cmor/tables/custom/CMOR_tcw.dat
This PR adds a custom CMOR table for the 3-dim variable total cloud water (tcw) that is needed by the new JRA-25 CMORizer (https://github.com/ESMValGroup/ESMValTool/pull/3470).
> Add custom CMOR table for total cloud water (tcw)

- .github/workflows/run-tests.yml
- environment.yml
- esmvalcore/cmor/_fixes/icon/icon.py
- setup.py
This PR fixes [recent test failures](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/10270/workflows/774a0b7d-be4a-436a-89b2-2b1429d1b77b/jobs/44121) that are caused by a [bug in pandas](https://github.com/pandas-dev/pandas/issues/57002). This bug breaks the `round` function that we use to round to the nearest second:
https://github.com/ESMValGroup/ESMValCore/blob/d6008f3d010e3ad6d2708d47ed8d48aa396af739/esmvalcore/cmor/_fixes/icon/icon.py#L495-L497
In addition, this removes the use of two deprecated features:
1. Replace 'S' by 's' (see https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)
2. Surround `DatetimeProperties.to_pydatetime` by `np.array` as recommended in the deprecation message. Unfortunately, this does not remove the …
> Pin pandas to avoid broken `round` function

- .github/workflows/create-condalock-file.yml
The conda lock generation GH Actions workflow always fails at a silly final step (assigning a review team), see eg https://github.com/ESMValGroup/ESMValCore/actions/runs/7484160285/job/20370571263 - this is not needed in any shape or form, I am the reviewer, and even if I am on hols, we avoid sending blanket messages to teams for this particular review (unless we agree we should asssign a team to review eg Tech Lead, but even then we need to give the bot a correct team name)
***
- ~[ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~
[1]: …
> remove team reviewers from conda lock generation workflow in Github Actions

- .github/workflows/run-tests.yml
- tests/unit/preprocessor/_regrid/test__stock_cube.py
- tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Closes #2320 
This PR clears the LRU grid of `_global_stock_cube` after each test to avoid a race condition that may lead to failing tests.
***
***
> Fix flaky regrid test by clearing LRU cache after each test

- esmvalcore/_recipe/check.py
- tests/integration/recipe/test_recipe.py
In the preprocessor function `regrid`, the usage of the deprecated regridding scheme `linear_extrapolate` is allowed. However, the corresponding [recipe check](https://github.com/ESMValGroup/ESMValCore/blob/70b19569599c7c1511563b610c3e453340c6be58/esmvalcore/_recipe/check.py#L497) does not. This PR fixes that.
Closes #2323
***
*** …
> Allow deprecated regridding scheme `linear_extrapolate` in recipe checks

- doc/quickstart/configure.rst
- esmvalcore/config/_esgf_pyclient.py
Remove the printed warning that users need to log on to ESGF, as this is no longer needed.
Closes  #1590
***
***
> Remove warning about logging in to ESGF

- esmvalcore/cmor/_fixes/cmip6/ciesm.py
- esmvalcore/cmor/_fixes/cmip6/fio_esm_2_0.py
- tests/integration/cmor/_fixes/cmip6/test_ciesm.py
- tests/integration/cmor/_fixes/cmip6/test_fio_esm_2_0.py
Units of input data claim to be `%`, but they are `1`. This PR adds a fix for that.
Tested this myself thoroughly.
***
***
> Added fix for wrong units of `clt` for CIESM and FIO-ESM-2-0

- .zenodo.json
- CITATION.cff
- esmvalcore/_recipe/check.py
- esmvalcore/_recipe/recipe_schema.yml
- esmvalcore/_recipe/to_datasets.py
- tests/integration/recipe/test_recipe.py
This PR should correct the bug of not correctly raising the error message in the variable check of the recipe.
Closes #2312
***
***
> Fix error message in variable definition check

- esmvalcore/cmor/_fixes/cesm/cesm2.py
- esmvalcore/cmor/_fixes/cmip5/hadgem2_cc.py
- esmvalcore/cmor/_fixes/cmip5/hadgem2_es.py
- esmvalcore/cmor/_fixes/cmip5/miroc_esm.py
- esmvalcore/cmor/_fixes/cmip6/access_esm1_5.py
- esmvalcore/cmor/_fixes/cmip6/cesm2.py
- esmvalcore/cmor/_fixes/cmip6/ec_earth3.py
- esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py
- esmvalcore/cmor/_fixes/cmip6/giss_e2_1_g.py
- esmvalcore/cmor/_fixes/cmip6/miroc6.py
- esmvalcore/cmor/_fixes/common.py
- esmvalcore/cmor/_fixes/cordex/cordex_fixes.py
- esmvalcore/cmor/_fixes/emac/emac.py
- esmvalcore/cmor/_fixes/icon/_base_fixes.py
- esmvalcore/cmor/_fixes/native6/era5.py
- esmvalcore/cmor/_fixes/native6/mswep.py
- esmvalcore/cmor/_fixes/shared.py
- esmvalcore/preprocessor/_derive/sm.py
- esmvalcore/preprocessor/_units.py
- esmvalcore/preprocessor/_volume.py
- tests/integration/cmor/_fixes/cmip5/test_hadgem2_es.py
- tests/unit/preprocessor/_derive/test_sm.py
Various small improvements in lazy data computations by using coordinate methods `has_bounds()`, `core_points()`, `core_bounds()` where possible.
Related to #674 and #42
***
***
> More lazy fixes and preprocessing functions

- esmvalcore/_recipe/check.py
- tests/integration/recipe/test_recipe.py
Very similar to https://github.com/ESMValGroup/ESMValCore/pull/2324, I forgot another scheme in https://github.com/ESMValGroup/ESMValCore/pull/2231 😬 
***
***
> Allow deprecated regridding scheme `unstructured_nearest` in recipe checks

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Closes #2349 
As @schlunma correctly points out in the issue, Pandas have not fixed a bug in 2.2.1 either, bug nicely described by Manu in #2305 (original PR with first pin):
This PR fixes [recent test failures](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/10270/workflows/774a0b7d-be4a-436a-89b2-2b1429d1b77b/jobs/44121) that are caused by a [bug in pandas](https://github.com/pandas-dev/pandas/issues/57002). This bug breaks the `round` function that we use to round to the nearest second:
https://github.com/ESMValGroup/ESMValCore/blob/d6008f3d010e3ad6d2708d47ed8d48aa396af739/esmvalcore/cmor/_fixes/icon/icon.py#L495-L497
In addition, this removes the use of two deprecated features:
1. Replace 'S' by 's' (see https://pandas.pydata.org/pandas-docs/stable/user_guide/timeserie …
> Pin pandas yet again avoid new `2.2.1` as well

- tests/integration/cmor/_fixes/test_common.py
Issue described in https://github.com/SciTools/iris/issues/5806 and reported internally in #2357 
Remember to plug intended behaviour after Iris folk fix that, or, un-xfail the test
@schlunma gives a nice overview of the test: This test tests a fix that converts a non-CF-compliant netCDF file into a CF-compliant file. One issue of this netCDF file is that the units of the bounds differ to those of the points.
Since 3.8, iris now [ignores](https://github.com/SciTools/iris/pull/5746) bounds with different (incompatible) units than the points. I think we need to wait for a reply of the iris people before we can properly fix this. It would be especially helpful to know if we can somehow retrieve the bounds after loading the cube.
***
It is the responsibility of the author to make sure the …
> xfail `tests/integration/cmor/_fixes/test_common.py::test_cl_hybrid_height_coord_fix_metadata` while Iris folk fix behaviour

- doc/quickstart/find_data.rst
- esmvalcore/cmor/_fixes/icon/_base_fixes.py
- esmvalcore/cmor/_fixes/icon/icon.py
- esmvalcore/preprocessor/__init__.py
- tests/integration/cmor/_fixes/icon/test_icon.py
Currently, the ICON grid file can either be specified via the facet `horizontal_grid` or automatically downloaded from a public website specified by the `GRID_FILE_URI` attribute of the data. Since the grid file is almost always present in the ICON output directory, this PR adds support for that. If possible, the ICON grid file is now retrieved from the ICON directory specified in the user configuration file.
Link to documentation: https://esmvaltool--2337.org.readthedocs.build/projects/ESMValCore/en/2337/quickstart/find_data.html#icon
***
[1]: …
> Support loading ICON grid from ICON rootpath

- esmvalcore/preprocessor/_time.py
See https://github.com/SciTools/iris/pull/5767: wrapping large arguments, such as numpy arrays in a `functools.partial` is an example of how functions can be created that will make this into a sizeable memory leak. This fixes this by using all numpy arrays as positional arguments in [`dask.array.apply_gufunc`](https://docs.dask.org/en/latest/generated/dask.array.gufunc.apply_gufunc.html#dask.array.gufunc.apply_gufunc).
Closes #2355 
*** …
> Fixed potential memory leak in `local_solar_time`

- esmvalcore/cmor/tables/custom/CMOR_rtnt.dat
The `positive` attribute of in the rtnt table says "up", but it clearly needs to be "down".
***
> Fixed 'positive' attribute in custom rtnt table

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
This PR updates the check of argument `interval` in the preprocessor function `resample_hours` (line 1236 in `_time.py`) from
`    if cube_period.total_seconds() / 3600 >= interval:`
to
`    if cube_period.total_seconds() / 3600 > interval:`
This change allows to process 3-hourly CMIP6 data and hourly ERA5 data with the same preprocessor settings. This is needed e.g. when calculating diurnal cycles from CMIP6 and ERA5 that need to have the same time coordinate (frequency and actual values) to be compared with the preprocessor function `distance_metric`.
The preprocessor `resample_hours` is currently not used by any recipe in the main branch, so risks of this change affecting existing diagnostics is expected to be very small.
[1]: …
> Update interval check in resample_hours

- esmvalcore/cmor/tables/custom/CMOR_clhmtisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_clhtkisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_cllmtisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_clltkisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_clmmtisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_clmtkisccp.dat
- esmvalcore/cmor/tables/custom/CMOR_lwcre.dat
- esmvalcore/cmor/tables/custom/CMOR_netcre.dat
- esmvalcore/cmor/tables/custom/CMOR_rsnt.dat
- esmvalcore/cmor/tables/custom/CMOR_swcre.dat
- esmvalcore/preprocessor/_derive/lwcre.py
- esmvalcore/preprocessor/_derive/netcre.py
- esmvalcore/preprocessor/_derive/rsnt.py
- esmvalcore/preprocessor/_derive/swcre.py
- tests/unit/preprocessor/_derive/test_lwcre.py
- tests/unit/preprocessor/_derive/test_netcre.py
- tests/unit/preprocessor/_derive/test_rsnt.py
- tests/unit/preprocessor/_derive/test_swcre.py
This PR fixes `positive` attributes in custom CMOR variables:
- For ISCCP cloud are fractions, remove it (it does not make sense to have it here)
- For the cloud radiative effects (CREs), change it from `up` to `down`
- For TOA Net downward Shortwave Radiation, change it from `up` to `down`
This PR also adds missing tests for these derived variables to improve our overall test coverage.
***
***
- 🙏 …
> Fix `positive` attributes in custom CMOR variables

- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_io/test_concatenate.py
For at least 6 years, iris dropped derived coordinates (i.e., aux factories) during concatenation (see https://github.com/SciTools/iris/issues/2478). For this reason, we implemented our own custom code to solve this:
https://github.com/ESMValGroup/ESMValCore/blob/1f73cc0ca565d37b51c295e558da0f6883a2e8f1/esmvalcore/preprocessor/_io.py#L39
Since the [issue is solved now since iris 3.5](https://github.com/SciTools/iris/pull/5096), this PR removes the corresponding custom code in ESMValCore. I did not remove a tiny [test](https://github.com/ESMValGroup/ESMValCore/blob/d128753fd6f6d2a10ba9b2b0c500b369fff1dd95/tests/integration/preprocessor/_io/test_concatenate.py#L279-L289) that checks if the actual concatenation still works; and indeed, it does (also without our custom code) 🚀 
Closes #2284 …
> Remove custom fix for concatenation of aux factories now that bug in iris is solved

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
[Tests](https://github.com/ESMValGroup/ESMValCore/actions/runs/8655273498/job/23733957234) are failing with the same issue we had in the past, described by @schlunma in https://github.com/ESMValGroup/ESMValCore/pull/2305 and with an original bug report in pandas at https://github.com/pandas-dev/pandas/issues/57002 - they just switched the milestone for that for 2.2.3 apparently!
***
***
- 🙏 We …
> Pin blithering pandas yet again :panda_face: `test_icon` fails again with pandas=2.2.2

- environment.yml
- esmvalcore/_provenance.py
- esmvalcore/preprocessor/_io.py
- setup.py
- tests/integration/conftest.py
- tests/integration/recipe/test_recipe.py
Closes #2376
Note: this is **not** fully backwards-compatible, as this changes the way iris writes attributes (some attributes are moved from global to local). I don't think this is a problem, but might be good to keep in mind.
***
*** …
> Use `iris.FUTURE.save_split_attrs = True` to remove iris warning

- esmvalcore/preprocessor/_io.py
One more new iris warning to ignore.
***
***
> Ignored iris warnings about global attributes

- esmvalcore/preprocessor/_time.py
- tests/unit/preprocessor/_time/test_time.py
Avoid very large chunks in `climate_statistics` preprocessor function when used with `period=full`.
Issue reported in https://github.com/ESMValGroup/ESMValTool/issues/3244#issuecomment-2095756345
***
*** …
> Avoid large chunks in `climate_statistics` preprocessor function with `period='full'`

- esmvalcore/preprocessor/_regrid_esmpy.py
- tests/unit/preprocessor/_regrid_esmpy/test_regrid_esmpy.py
Realize the data only once for the ESMPy regridders.
Closes https://github.com/ESMValGroup/ESMValTool/issues/3590
Test recipe:
```yaml
documentation:
description: Example recipe that shows slow regridding.
title: Example recipe that shows slow regridding.
authors:
- andela_bouwe
maintainer:
- andela_bouwe
references:
- acknow_project
projects:
- esmval
preprocessors:
time_ocean_zonal_mean:
custom_order: true
climate_statistics:
operator: mean
period: full
extract_levels:
levels: [ 0,  10, 20, 50, 100, 200, 300, 500, 750, 1000, 1250, 1500, 1750, 2000, 2250, 2500, 2750, 3000, 3250, 3500, 3750, 4000, 4250, 4500, 4750, 5000, 5250, 5500, 5750]
scheme: linear_extrapolate
coordinate: depth
regrid:
target_grid: 1x1
scheme: nearest
zonal_statistics:
operator: mean
datasets:
- dataset: CanESM5-1 …
```
> Load data only once for ESMPy regridders

- environment.yml
- setup.py
We should pin numpy <2 for the release - David Hassell pulled the rc1 in the cfpython env, here's what I wrote to him this is the bug in pip that makes possible a pre package get pulled in https://github.com/pypa/pip/issues/7579 and real world case for the same issue you had here https://github.com/Unidata/cftime/issues/327 - slim chances for us to hit this bug, since all's been fine so far, but better err on the safe side!
@ehogan @chrisbillowsMO I think it'd be safe to include this in the release, maybe just after ESMValCore rc1, so it doesn't mess with your current procedures. Once numpy=2 stable is out, and we've fixed all the wiggles (ours or not) via https://github.com/ESMValGroup/ESMValCore/pull/2395 then we can unpin. Cheers :beer: 
***
It is the responsibility of the author to …
> Pin numpy<2.0.0 to avoid pulling 2.0.0rcX

- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
- environment.yml
Closes #2419 
`compilers` was added by @bouweandela four years ago in #603 - see https://github.com/ESMValGroup/ESMValCore/pull/603#issuecomment-631651179 - I don't think we still need it but may be worth checking the docker build goes well without it anyway
OSX tests: failing with "setuptools_scm._run_cmd.CommandNotFoundError: git" - this has been seen in https://github.com/ESMValGroup/ESMValTool/pull/3581 and it's not hitting just this node, but rather, it's an endemic issue related to macOS 14 on arm64:
```
Image: macos-14-arm64
Version: 20240422.3
Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
```
For some …
> Remove compilers dependency from conda environment and force install x64 git in OSX Github Action workflows

- .github/workflows/build-and-deploy-on-pypi.yml
- .github/workflows/citation_file_validator.yml
- .github/workflows/create-condalock-file.yml
- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-condalock-file.yml
- .github/workflows/install-from-pypi.yml
- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
Three of our actions use outdated versions, therefore one sees a long list of warnings on the [action's front page](https://github.com/ESMValGroup/ESMValCore/actions/runs/8994363671) - the problem with oudated actions is that there will be fewer and fewer nodes that actually support them, so that means either run delays or even worse: the RR word (run rejection, don't get any other ideas, like Rolls Royce :laughing: )
***
***
To help …
> [CI Github Actions] Update (outdated) actions versions that produce Node.js warnings

- esmvalcore/esgf/_download.py
- tests/unit/esgf/test_download.py
Due to https://github.com/psf/requests/issues/5536, downloading files from ESGF loaded entire files into memory, leading to potentially high memory use when downloading large files. This pull request avoids the issue.
***
projects/ESMValCore/en/latest/contributing.html#dependencies) correctly
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of- …
> Avoid loading entire files into memory when downloading from ESGF

- environment.yml
- setup.py
With the new [release](https://github.com/SciTools-incubator/iris-esmf-regrid/releases/tag/v0.10.0) of iris-esmf-regrid we can update some pins in the environment.
See also https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2092921514.
***
*** …
> Updated esmf-related pins

- esmvalcore/preprocessor/_volume.py
- tests/unit/preprocessor/_volume/test_volume.py
Make calculating the volume lazy.
Closes #647
***
***
> Make volume calculation in preprocessor function `volume_statistics` lazy

- esmvalcore/iris_helpers.py
- tests/unit/test_iris_helpers.py
Preserve cube attribute global vs local as well as possible in `esmvalcore.preprocessor.concatenate`. See [`iris.cube.CubeAttrsDict`](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris.cube.html#iris.cube.CubeAttrsDict) for more information.
***
*** …
> Preserve cube attribute global vs local when concatenating

- esmvalcore/cmor/_fixes/obs4mips/airs_2_0.py
- tests/integration/cmor/_fixes/obs4mips/test_airs_2_0.py
Fixes https://github.com/ESMValGroup/ESMValTool/issues/3680
***
***
> Fix units and `valid_range` of AIRS-2-0

- esmvalcore/cmor/tables/custom/CMOR_tosStderr.dat
- tests/integration/cmor/test_table.py
This pull request adds a custom cmor table entry for sea surface temperature uncertainty (tosStderr), and a test for this new entry.
Closes #2469
***
***
> New custom variable for tos uncertainty

- CITATION.cff
There was a typo introduced by #2430.
This PR fix the issue
> Fix CFF file

- .circleci/config.yml
- doc/conf.py
I'm not sure if this is the right way to solve this issue, but at least it fixes the build. If anyone has better ideas, that would be most welcome.
Successful build: https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/11389/workflows/7ef9bd62-5a41-4aa6-954f-cf7e031876ec/jobs/47859
Closes #2479
Link to documentation: https://esmvaltool--2480.org.readthedocs.build/projects/ESMValCore/en/2480/
***
***
To help with the number …
> Ignore autosummary warning in documentation build

- esmvalcore/_recipe/check.py
> Fix type hint for new mypy version

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Closes #2503
~I will also open an issue at Dask with an MRC, but this is all we can do, for now, at our end~
So far, this is an `iris` issue reported here https://github.com/SciTools/iris/issues/6109
***
*** …
> Pin dask to avoid 2024.8.0 - problems with masked fill/missing values

- doc/quickstart/find_data.rst
The documentation build is broken since #2457 was merged because it included a broken reference. This pull request fixes the reference and also the broken link reported in #2510.
Closes #2510.
Link to documentation: https://esmvaltool--2519.org.readthedocs.build/projects/ESMValCore/en/2519/
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-o …
> Fix documentation build and broken link

- .github/workflows/run-tests.yml
- environment.yml
- setup.py
Closes #2535 
Long story short:
- `iris-grib` needs be pinned due to #2178 
- `ncl` has a hard pin `esmf<8.6.0` so whatever `ncl` gets installed for `esmf/esmpy>=8.6.0` is about two years old (still 6.6.2 but a very old build, that did not have the pin in)
- it is rather safe to use `esmf/esmpy<8.6.0` ie `8.4.2` as per https://github.com/SciTools/iris-esmf-regrid/issues/415
***
***
- 🙏 We kindly …
> Free esmpy of ` >=8.6.0` pin and pin `iris-grib >=0.20.0`

- esmvalcore/config/_config_object.py
- tests/conftest.py
- tests/unit/config/test_config_object.py
- tests/unit/main/test_esmvaltool.py
Fix tests if a deprecated `~/.esmvaltool/config-user.yml` file exists on the system.
Closes https://github.com/ESMValGroup/ESMValCore/issues/2541
***
***
> Fix tests if deprecated `~/.esmvaltool/config-user.yml` file is available

- doc/api/esmvalcore.config.rst
- esmvalcore/_main.py
- esmvalcore/config/_config_object.py
- tests/unit/config/test_config_object.py
While working on making ESMValTool with the new configuration (https://github.com/ESMValGroup/ESMValCore/pull/2448) I noticed that we are missing a simple public function to update the configuration from one or more directories.
This PR adds that.
Related to #2371 
Link to documentation: https://esmvaltool--2538.org.readthedocs.build/projects/ESMValCore/en/2538/api/esmvalcore.config.html#esmvalcore.config.Config.update_from_dirs
***
*** …
> Add public `Config.update_from_dirs()` method

- esmvalcore/cmor/check.py
- esmvalcore/cmor/fix.py
- esmvalcore/dataset.py
- tests/integration/cmor/_fixes/obs4mips/test_airs_2_0.py
- tests/integration/cmor/test_fix.py
- tests/unit/cmor/test_cmor_check.py
- tests/unit/cmor/test_fix.py
- tests/unit/test_dataset.py
This PR removes deprecated features related to CMOR fixes and checks that have been deprecated in v2.10.0 and are scheduled for removal in v2.12.0. See https://github.com/ESMValGroup/ESMValCore/pull/2157 for details.
- Option `automatic_fixes` of [`CMORCheck`](https://esmvaltool--2157.org.readthedocs.build/projects/ESMValCore/en/2157/api/esmvalcore.cmor.html#esmvalcore.cmor.check.CMORCheck): use the functions [`fix_metadata`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.fix_metadata), [`fix_data`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.fix_data), or [`Dataset.load`](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.dataset. …
> Remove deprecated CMOR fix/check code

- .circleci/config.yml
- .github/workflows/create-condalock-file.yml
- .github/workflows/install-from-conda.yml
- .github/workflows/install-from-pypi.yml
- .github/workflows/install-from-source.yml
- .github/workflows/run-tests-monitor.yml
- .github/workflows/run-tests.yml
- sister PR of https://github.com/ESMValGroup/ESMValTool/pull/3774
- Original issue from ESMValTool (with description of "brownouts" and Miniforge's attempts to get us all off Mambaforge asap) https://github.com/ESMValGroup/ESMValTool/issues/3772
- move to Miniforge3 image from [condaforge/miniforge3](https://hub.docker.com/r/condaforge/miniforge3)
- no references of Mambaforge in our docs...
- though, the `mambaforge` container needs be changed from Readthedocs' build configuration - problem is, RTD don't support Miniforge3 https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python - will see what I can do - for now I opened an issue at RTD https://github.com/readthedocs/readthedocs.org/issues/11690
***
It is the responsibility of the author to make sure the pull …
> retire Mambaforge

- docker/Dockerfile
- docker/Dockerfile.dev
Missed this in #2556 - this is the last but on Mambaforge apart from the RTD wait
***
***
> use `miniforge3` for our docker builds instead of `mambaforge`

- .github/workflows/create-condalock-file.yml
Related to https://github.com/ESMValGroup/ESMValTool/issues/3782 - currently `conda-lock` is struggling with mamba>=2 but Ben Mares at `conda-lock` has fixed the issue, and all we need to do is wait for a major release of `conda-lock`; in the meantime the workaround is to pin mamba in the Github action, so we can get our lock file generated.
***
*** …
> pin mamba in conda lock creation github action

- README.md
So I use the same utility as I did for ESMValTool https://shields.io/badges/docker-automated-build
- all other options return Invalid in the badge, not 100% sure why this one says Manual (last build was triggered manually perhaps?), but at least it looks better then a grey Invalid. Frankly, am not 100% sure this is the badge we need at all, but Docker themselves don't give any info on how to build a badge, like PyPI or Conda/Anaconda do. Meh.
- so @bouweandela suggested we remove the badge altogether, which I did here...
- unless perhaps @lukruh or @bettina-gier know how to fix it - they are far more badge/arts-in-Python savvy than meself :beer: 
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject …
> remove Docker build badge in README

- esmvalcore/cmor/_fixes/fix.py
- esmvalcore/cmor/_fixes/native6/era5.py
- esmvalcore/cmor/_fixes/native_datasets.py
- esmvalcore/iris_helpers.py
- esmvalcore/preprocessor/_units.py
- tests/unit/preprocessor/_units/test_convert_units.py
- tests/unit/test_iris_helpers.py
While performing tests for https://github.com/ESMValGroup/ESMValTool/pull/3784, I noticed that our fixes do not use our [own unit conversion function](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.convert_units), which allows special unit conversions like m -> DU.
This PR adds this, but uses a "safe" version of the unit conversion which will not allow a change of the cube's `standard_name` (this would lead to errors in the subsequent CMOR checks).
*Note*: I had to restructure the functions a little bit to avoid circular imports.
Related to
- https://github.com/ESMValGroup/ESMValTool/pull/3784
- https://github.com/ESMValGroup/ESMValCore/pull/2509
- …
> Use our own unit conversion function in our fixes

- esmvalcore/config/_config_validators.py
- esmvalcore/local.py
- tests/unit/config/test_config_validator.py
Closes https://github.com/ESMValGroup/ESMValCore/issues/2577
***
***
> Do not use `Path` objects as configuration dictionary keys to avoid errors in `dask.config.merge`

- esmvalcore/_main.py
- tests/unit/main/test_esmvaltool.py
While testing https://github.com/ESMValGroup/ESMValCore/pull/2522, I noticed that `CFG` is not updated with config options given via command line. This PR fixes that.
It would probably be good to unify our usage of `Session` and `CFG` in the code base, but that's something for another PR.
Closes https://github.com/ESMValGroup/ESMValCore/issues/2594
***
*** …
> Update `CFG` with configuration options given via command line

- esmvalcore/config/_dask.py
- tests/unit/config/test_dask.py
Avoid a crash when there is a timeout when shutting down the Dask cluster. I have seen this happen on Levante at DKRZ recently. It does not appear to be a real problem as the cluster is shut down after the tool completes running.
***
*** …
> Avoid a crash when there is a timeout when shutting down the Dask cluster

- .github/workflows/create-condalock-file.yml
mamba<2 is not compatible with Python 3.13, and we are pinning it until conda-lock==3 comes about, so I am switching the pin in the conda lock generator workflow, back to Python 3.12, so we can have updated conda lock files in the meantime. See https://github.com/ESMValGroup/ESMValCore/actions/runs/12102229199/job/33856299466
***
*** …
> switch back to Python 3.12 for conda lock file creation due to mamba<2 pin

- esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py
- tests/integration/cmor/_fixes/cmip6/test_cesm2.py
- tests/integration/cmor/_fixes/cmip6/test_fgoals_g3.py
This is a follow up for #2602. This is pretty much the same fix and tests I had created for CESM2 from NCAR in #2574 and also I found a slight typo from my last pull request. This should fix the monotonicity issue but I could not figure out where the frequency issue is coming from. 
***
> Monotonicity fixes for Fgoals

- esmvalcore/cmor/_fixes/cmip6/fio_esm_2_0.py
- tests/integration/cmor/_fixes/cmip6/test_fio_esm_2_0.py
FIO-ESM-2-0 (CMIP6) Amon data can have invalid latitude and/or longitude bounds. The existing fix does not consider all problematic cases (e.g., when the invalid latitude point is at 90° with bounds 90° and 90°). This PR expands this fix for this corner case.
***
*** …
> Expand Amon fix of FIO-ESM-2-0 (CMIP6)

- tests/conftest.py
- tests/unit/config/test_dask.py
Add fixture to always ignore user's configuration when running tests.
Closes https://github.com/ESMValGroup/ESMValCore/issues/2623
***
***
> Always ignore user's configuration when running Dask tests

- esmvalcore/cmor/_fixes/emac/emac.py
- esmvalcore/iris_helpers.py
- esmvalcore/preprocessor/_area.py
- esmvalcore/preprocessor/_compare_with_refs.py
- esmvalcore/preprocessor/_cycles.py
- esmvalcore/preprocessor/_derive/_shared.py
- esmvalcore/preprocessor/_derive/amoc.py
- esmvalcore/preprocessor/_derive/toz.py
- esmvalcore/preprocessor/_derive/troz.py
- esmvalcore/preprocessor/_derive/uajet.py
- esmvalcore/preprocessor/_mask.py
- esmvalcore/preprocessor/_multimodel.py
- esmvalcore/preprocessor/_other.py
- esmvalcore/preprocessor/_rolling_window.py
- esmvalcore/preprocessor/_shared.py
- esmvalcore/preprocessor/_time.py
- esmvalcore/preprocessor/_trend.py
- esmvalcore/preprocessor/_volume.py
- tests/unit/preprocessor/_derive/test_shared.py
- tests/unit/preprocessor/test_shared.py
- tests/unit/test_iris_helpers.py
See https://github.com/ESMValGroup/ESMValCore/pull/2625#issuecomment-2609185527. This ignores all potential [`iris.warnings.IrisVagueMetadataWarning`](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris.warnings.html#iris.warnings.IrisVagueMetadataWarning) that can appear when collapsing/aggregating cubes in our preprocessors. This should be safe because we extensively check the corresponding coordinates in our CMOR checks.
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-re …
> Unified ignoring of `iris.warnings.IrisVagueMetadataWarning` in preprocessors

- doc/develop/preprocessor_function.rst
- tests/integration/preprocessor/_io/test_load.py
Fixes test that loads GRIB files on conda-forge. I am not sure how to test this properly, since the test worked fine on CircleCI before, but I am pretty confident that it works because we use that code for [another test](https://github.com/ESMValGroup/ESMValCore/blob/dd1e29cc1b28e396601b6d4463d8a65f558f8688/tests/unit/config/test_config.py#L40-L41) which seems to work fine on conda-forge.
Closes https://github.com/ESMValGroup/ESMValCore/issues/2664
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#sc …
> Fix test that loads realistic GRIB file

- doc/recipe/preprocessor.rst
- esmvalcore/preprocessor/_regrid.py
- tests/integration/preprocessor/_regrid/test_regrid.py
- tests/unit/preprocessor/_regrid/__init__.py
- tests/unit/preprocessor/_regrid/test_regrid.py
Add an option to ignore horizontal coordinates if there are multiple when regridding.
For example, some files provide both 'latitude' and 'grid_latitude'. This uses 'latitude' by default, but 'grid_latitude' can be selected from the recipe.
Related to https://github.com/ESMValGroup/ESMValTool/issues/3916#issuecomment-2671272258
- https://esmvaltool--2672.org.readthedocs.build/projects/ESMValCore/en/2672/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.regrid
- https://esmvaltool--2672.org.readthedocs.build/projects/ESMValCore/en/2672/recipe/preprocessor.html#regridding-input-data-with-multiple-horizontal-coordinates
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject …
> Add option to ignore horizontal coordinates if there are multiple when regridding

- esmvalcore/preprocessor/_regrid.py
- tests/unit/preprocessor/_regrid/test_regrid.py
If the source grid and target grid for regridding are sufficiently similar, [the operation is skipped](https://github.com/ESMValGroup/ESMValCore/blob/always_overwrite_coords_after_regrid/esmvalcore/preprocessor/_regrid.py#L861). Currently, in this case, the target grid coordinates' points and bounds are written to the source cube, but **not** other metadata. This might lead to problems in subsequent preprocessor functions (e.g., `distance_metric`) or diagnostics that expect cubes to have identical coordinate metadata.
Here, this is fixed by always assigning the target coordinates themselves to the source cube, not only their points and bounds.
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject to …
> Always write target coordinates to source cube after regridding

- CITATION.cff
- doc/changelog.rst
This PR updates the CITATION.cff to version 2.12.0, as well as fixing the release notes
Link to documentation: https://esmvaltool--2678.org.readthedocs.build/projects/ESMValCore/en/2678/changelog.html
***
*** …
> Update release version for v2.12.0

- esmvalcore/config/extra_facets/icon-mappings.yml
Mappings for ICON-XPP ocean variables. 
The sea ice variables (sithick/sic) will need adjustments in the fix, since they have an extra "lev" dimension that is not expected by CMOR. I posted one possible generic solution in the comments of https://github.com/ESMValGroup/ESMValCore/pull/2699. Otherwise, the variables would need to fixed be individually.
Moreover, variables like mixed layer depth (mlotst) or sea surface height (zos) might have different names/definitions in different output files. I added mappings of what I considered to be reasonable defaults.
Does not close but helps to close https://github.com/ESMValGroup/ESMValCore/issues/2694
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether the item will be subject …
> [NOT FOR CHANGELOG; PR NOT IN MAIN] Add mappings for ocean variables

- .circleci/config.yml
Upper pins on dependencies in iris-esmf-regrid broke our [upstream tests](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/12891/workflows/660cbe59-9f57-4774-8901-c2b36c44c697/jobs/53598): https://github.com/SciTools/iris-esmf-regrid/pull/506
Installing with `--no-deps` avoids `pip` tripping up over this.
Successful run: https://github.com/ESMValGroup/ESMValCore/pull/2710/checks?check_run_id=40709150012
***
***
To help …
> Use --no-deps in upstream tests to avoid installation problems caused by upper pins

- esmvalcore/cmor/_fixes/obs4mips/c3s_gto_ecv_9_0.py
- tests/integration/cmor/_fixes/obs4mips/test_c3s_gto_ecv_9_0.py
This fix converts any nan's in the obs4MIPs dataset "GTO-ECV-9-0" (total ozone columns, toz) into missing values. This is needed to allow for e.g. applying the area statistics preprocessor.
> Fix for obs4MIPs dataset C3S-GTO-ECV-9-0 (toz)

- esmvalcore/local.py
- tests/unit/local/test_time.py
If start and end dates cannot be read from a file's name, we currently use [Iris to load the file and determine the dates from the time coordinate](https://github.com/ESMValGroup/ESMValCore/blob/0533aa1fcf9ba7610870ce6fe28627d0e19dc258/esmvalcore/local.py#L132-L154). This is particular relevant for native model output where the date in the filename can have arbitrary formats.
This native model output (in my particular case data from ICON and EMAC) usually contains lots of variables (sometimes hundreds) in a single netCDF file, and also consists of hundreds of netCDF files per dataset (sometimes one file only contains a single time step). Since reading netCDF files with many variables can be [very slow with Iris](https://github.com/SciTools/iris/issues/6223), this can lead to enormous run …
> Use `netCDF4.Dataset` to read start and end date from files

- esmvalcore/cmor/_fixes/native6/era5.py
- tests/integration/cmor/_fixes/native6/test_era5.py
ERA5's rlut and rlutcs are negative, but need to be positive. Here is an example plot of the LWCRE (rlutcs - rlut):
***
***
> Fix sign of ERA5 rlut and rlutcs

- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_compare_with_refs.py
- esmvalcore/preprocessor/_concatenate.py
- esmvalcore/preprocessor/_io.py
- tests/integration/preprocessor/_concatenate/test_concatenate.py
Having the `concatenate`  preprocessor function in the `esmvalcore.preprocessor._io` module is causing circular import issues in #2765. To keep changes to a minimum in that pull request, I created a separate pull request just to move it.
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-req …
> Move concatenate preprocessor function to its own module

- tests/conftest.py
- tests/unit/main/test_esmvaltool.py
Avoid reading configuration from disk for every single test, which was introduced in #2736, and caused a slowdown in the tests.
***
***
> Avoid reading configuration from disk for every single test

- .pre-commit-config.yaml
- esmvalcore/_recipe/to_datasets.py
- tests/unit/recipe/test_to_datasets.py
Since #2755, automatic addition of supplementary variables searches for too many supplementary variables (also those belonging to other datasets, grids, etc). This happens because the automatically added supplementary variables have a `"*"` for all facet values which are no longer overwritten by the values from the main variable since #2755.
***
***
- 🙏 …
> Avoid too wide supplementary file search

- tests/unit/test_iris_helpers.py
See test fail [here](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/13330/workflows/b57a2c04-0889-485d-8262-b228f2a856ae/jobs/55154?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary); looks like a new numpy warning is raised. To avoid these failures in the future, just don't assume that no warning is raised.
***
***
- 🙏 We …
> Do not assume that no warnings are raised during `test_dataset_to_iris`

- esmvalcore/preprocessor/_io.py
Closes #2790 
There was quite a bit of investigation down about this in https://github.com/pp-mo/ncdata/issues/139 and in https://github.com/pydata/xarray/issues/10612 and in my own GH repo at  https://github.com/valeriupredoi/esmvaltool_zarr_tests and, with help from @pp-mo and @kmuehlbauer we managed to get the performance of Zarr loading go up by a big notch though keeping all data lazy, both for remote bucket and local Zarr stores. So far, a generic `chunks={}` should work OK, maybe we want to have smart chunking done in the future, but at this stage, this setting helps a LOT with memory consumption and runtime. Cheers very much, gents! :beers: 
EDIT (thanks, @schlunma ) `chunks="auto"` does not work for some files `NotImplementedError: Can not use auto rechunking with object dtype. …
> Pass `chunks={}` to Xarray dataset loader for Zarr stores

- doc/recipe/preprocessor.rst
- esmvalcore/_recipe/check.py
- esmvalcore/_recipe/recipe.py
- esmvalcore/cmor/table.py
- esmvalcore/preprocessor/__init__.py
- esmvalcore/preprocessor/_other.py
- tests/integration/cmor/test_table.py
- tests/integration/recipe/test_recipe.py
- tests/unit/preprocessor/_other/test_other.py
This PR adds the preprocessor `align_metadata` which aligns cube metadata with a specific target project. This is useful to perform multi-model analysis across different projects (e.g., CMIP5 and CMIP6).
Example recipe:
```yml
---
documentation:
description: Test
authors:
- schlund_manuel
title: Test.
preprocessors:
test:
align_metadata:
target_project: CMIP6
regrid:
target_grid: 2x2
scheme: linear
multi_model_statistics:
span: overlap
statistics: [mean]
diagnostics:
test:
scripts:
null
variables:
clivi:
preprocessor: test
mip: Amon
additional_datasets:
- {project: OBS, dataset: CLARA-AVHRR, type: sat, version: V002-01, tier: 3, alias: MultiObsMean, timerange: 19990101/20181231}
- {project: OBS, dataset: CLOUDSAT-L2, type: sat, version: P1-R05-gridbox-average-noprecip, tier: 3, alias: …
```
> Add preprocessor `align_metadata`

- doc/contributing.rst
- doc/recipe/overview.rst
Removes mentions of Julia in the documentation ahead the discontinued support for Julia in v2.13.
Support in the ESMValCore code is kept for now.
Address [#4132](https://github.com/ESMValGroup/ESMValTool/issues/4132)
> Remove mention of Julia in documentation ahead of discontinued support in v2.13

- tests/integration/preprocessor/_io/test_zarr.py
The test `tests/integration/preprocessor/_io/test_zarr.py::test_load_zarr_local_not_zarr_file` was failing due to a change in the exception used in zarr:
`FAILED tests/integration/preprocessor/_io/test_zarr.py::test_load_zarr_local_not_zarr_file - FileExistsError: [Errno 17] File exists: '/root/project/tests/sample_data/zarr-sample-data/example_field_0.zarr17'`
This is solved by replacing
https://github.com/ESMValGroup/ESMValCore/blob/dcf9179d35264d39b0c8b3ba5f8fa76f54e1c24e/tests/integration/preprocessor/_io/test_zarr.py#L220-L224
with
```
with pytest.raises(GroupNotFoundError):
load(zarr_path)
```
Test pipeline now passing https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/13642/workflows/9624418d-8022-41b2-a4d1-0e912388450a
***
It is the responsibility of the author to …
> Change zarr exception test to GroupNotFoundError
