doc/sphinx/source/requirements.txt, esmvalcore/_config.py, esmvalcore/_data_finder.py, esmvalcore/preprocessor/__init__.py, esmvalcore/preprocessor/_io.py, esmvalcore/preprocessor/_mapping.py, esmvalcore/preprocessor/_multimodel.py, esmvalcore/preprocessor/_regrid.py, meta.yaml, setup.py, tests/integration/test_diagnostic_run.py, tests/integration/test_recipe.py
Remove code for
- iris 1 support
- Python 2 support (six package)
=> Remove legacy code

esmvalcore/_provenance.py
This should improve the situation reported in issue #13 by a lot.
=> Reduce time required for provenance recording

esmvalcore/preprocessor/_derive/sm.py
Unfortunately unit tests are missing, so not sure if this works. Partially addresses #42.
=> Make sm derivation lazy

esmvalcore/preprocessor/_derive/toz.py
While this does not solve #42 for the `toz` derivation, at least it is now done with 32 bit floating point numbers instead of 64 bit, so it should save some memory.
=> Use float32 for toz derivation instead of float64

esmvalcore/cmor/_fixes/CMIP5/MIROC5.py, esmvalcore/cmor/_fixes/CMIP5/MRI_CGCM3.py, esmvalcore/cmor/_fixes/CMIP5/MRI_ESM1.py
Unfortunately there are no unit tests, so i cannot be sure that I did not mess anything up, but the fixes are fairly simple, so I think this should be fine.
=> Make fixes lazy

esmvalcore/_config.py, esmvalcore/_recipe.py, esmvalcore/_task.py, esmvalcore/config-user.yml
Adds config setting for quicklooks
=> Enable quicklook settings

esmvalcore/preprocessor/_emac/var_mapping.yml
First fixes of the outstanding CMOR custom problems.
=> Dev emac import custcmorfix

esmvalcore/preprocessor/_emac/_derive/rlus.py, esmvalcore/preprocessor/_emac/_derive/rsus.py, esmvalcore/preprocessor/_emac/_derive/rsut.py, esmvalcore/preprocessor/_emac/var_mapping.yml
Adding the scripts to correctly derive rsus, rsut and rlus from EMAC variables.
=> Dev emac import dervar2

esmvalcore/config-developer.yml
Added file structure for RCAST in `config-developer.yml`.
=> Add configuration for RCAST

esmvalcore/cmor/check.py, tests/unit/cmor/test_cmor_check.py
As a bonus, we were limiting time checking to DimCoords (to avoid issues when having time, time_counter, forecast_time). Now if we don't find a DimCoord we look for AuxCoords also
Fixes issue #173
=> Check time is monotonic

esmvalcore/preprocessor/_io.py, esmvalcore/preprocessor/_time.py
This will reduce the number of warnings coming from iris
- Ignore warnings about missing cell measures
- Ignore warnings about missing time bounds where not needed
See #127
=> Ignore known iris warnings

doc/esmvalcore/recipe.rst
Adding a simple reference to the alias we just added
=> Added a bit of documentation about the alias

esmvalcore/cmor/tables/custom/CMOR_albDiffiTr13.dat
Related to: https://github.com/ESMValGroup/ESMValTool/pull/1186
=> Added a dataset specific variable (Duveiller2018)

esmvalcore/cmor/table.py, esmvalcore/cmor/tables/custom/CMOR_sispeed.dat, esmvalcore/cmor/tables/custom/CMOR_sithick.dat, esmvalcore/preprocessor/_derive/sispeed.py, esmvalcore/preprocessor/_derive/sithick.py, tests/integration/preprocessor/_derive/test_sispeed.py, tests/integration/preprocessor/_derive/test_sithick.py
Sispeed is a new variable in CMIP6 but can be computed in CMIP5 datasets using usi and vsi (siu and siv in CMIP6)
=> Add sispeed derivation

doc/esmvalcore/fixing_data.rst, doc/esmvalcore/preprocessor.rst, setup.cfg
=> Added doc for cmor and fix preprocessor steps

esmvalcore/cmor/check.py, esmvalcore/cmor/table.py
Improved error management in some parts of the CMOR module. New messages implemented and fixed a couple that were not working as intended
=> Better error messages

.zenodo.json, CITATION.cff, CONTRIBUTING.md, esmvalcore/_version.py, meta.yaml, setup.py
This pull request adds
- A CITATION.cff file
- .zenodo.json file
- minor updates to setup.py
- Increases version number to 2.0.0b1
Related issue #2
=> Add CITATION.cff and Zenodo configuration

README.md
=> Use Zenodo DOI

doc/esmvalcore/preprocessor.rst, esmvalcore/preprocessor/__init__.py, esmvalcore/preprocessor/_detrend.py, tests/unit/preprocessor/_detrend/test_detrend.py
Add a new preprocessor function that performs a linear or constant detrend using `scipy.signal`.
=> Add detrend preprocessor function

esmvalcore/_version.py, meta.yaml
Note that I already made the release, but forgot to first upgrade the version number.
=> Increase version to v2.0.0b2

esmvalcore/cmor/check.py, tests/unit/cmor/test_cmor_check.py
=> Support pt frequencies

esmvalcore/cmor/table.py, esmvalcore/config-developer.yml, tests/integration/cmor/test_read_cmor_tables.py, tests/integration/cmor/test_table.py
=> Fix wrong name of cmor_path that prevented obs4mips cmor tables from being used

esmvalcore/cmor/tables/custom/CMOR_ohc.dat, esmvalcore/preprocessor/_derive/ohc.py, tests/unit/preprocessor/_derive/test_ohc.py
This adds a new derived variable for the ocean heat content per cell.
It's the core part of ESMValGroup/ESMValTool#922.
=> Add ocean heat content (ohc) derived variable

esmvalcore/preprocessor/_area.py, tests/unit/preprocessor/_area/test_area.py
=> Fix bug in extract_region for irregular grids

esmvalcore/cmor/_fixes/fix.py, tests/integration/cmor/_fixes/test_fix.py
To solve issues #251 and ESMValGroup/ESMValTool#1292
=> Make fixes case insensitive

esmvalcore/cmor/tables/custom/CMOR_ptype.dat
This adds custom variable `precipitation_type`
**Tasks**
* * *
Closes #264
=> Add precipitation type custom table entry

.circleci/config.yml
=> Only try to upload coverage if possible

esmvalcore/config-developer.yml
=> Change badc cmip5 drs version `latest` to `[latestversion]` (closes #278)

README.md
Correct the link to the readthedocs badge
=> Fix readthedocs badge in README.md

doc/esmvalcore/preprocessor.rst, esmvalcore/preprocessor/_area.py, esmvalcore/preprocessor/_shared.py, esmvalcore/preprocessor/_time.py, tests/unit/preprocessor/_area/test_area.py, tests/unit/preprocessor/_time/test_time.py
Added `sum` statistic to several preprocessor functions.
closes #283
=> Extend statistics preproc

esmvalcore/cmor/tables/custom/CMOR_vegfrac.dat, esmvalcore/preprocessor/_derive/vegfrac.py
This PR adds vegfrac as a derived variable. It's a really simple variable (1 - bare soil fraction). Surprised that it didn't exist already. It would be good if some land surface experts could weigh in on this though, as it's fairly basic.
=> Added vegfrac as a derived variable

esmvalcore/cmor/_fixes/cmip5/fgoals_g2.py, tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py
Fgoals fix will no longer fail for cubes with no time coordinate
Closes #304
=> Fix Fgoals fix

esmvalcore/cmor/_fixes/cmip5/gfdl_cm2p1.py, esmvalcore/cmor/_fixes/cmip5/gfdl_cm3.py, esmvalcore/cmor/_fixes/cmip5/gfdl_esm2g.py, esmvalcore/cmor/_fixes/cmip5/gfdl_esm2m.py, tests/integration/cmor/_fixes/cmip5/test_gfdl_cm2p1.py, tests/integration/cmor/_fixes/cmip5/test_gfdl_cm3.py, tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2g.py, tests/integration/cmor/_fixes/cmip5/test_gfdl_esm2m.py
Fix wrong units in `areacello` for the GFDL models (as reported in [#888](https://github.com/ESMValGroup/ESMValTool/pull/888)).
=> GFDL fixes for areacello

esmvalcore/config-developer.yml
=> reinstated correct latestversion for CMIP5 files

.github/pull_request_template.md
Add a checkbox asking for a descriptive title
=> Add descriptive title requirement to pull request template

.circleci/config.yml
See https://github.com/conda/conda/issues/9337
=> Disable conda update on CircleCI

esmvalcore/cmor/tables/custom/CMOR_ctotal.dat, esmvalcore/preprocessor/_derive/ctotal.py, tests/unit/preprocessor/_derive/test_ctotal.py
**Tasks**
Notes:
- This works for summing up cSoil …
=> add derivation of total ecosystem carbon mass content (closes #321)

.mailmap
=> Add .mailmap file to identify authors with multiple email addresses/names

.zenodo.json, CITATION.cff, esmvalcore/_version.py, meta.yaml
Increase version to v2.0.0b3 for the upcoming release and polish citation information
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
=> Increase version to v2.0.0b3

esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
-   [x] Circle/CI tests pass. Status can be seen below your pull request. …
=> Fix fix for tas of GFDL-CM4

esmvalcore/preprocessor/_mask.py
=> Mask_landsea file finding NOT done using the first member of file name only

esmvalcore/_task.py
fix typo in making files executable
@bascrezee
=> Update _task.py due to typo

esmvalcore/preprocessor/_derive/rlnstcs.py
**Tasks**
-   [ x] [Create an issue] Issue #394
-   [x ] This pull request has a descriptive title that can be used in a changelog
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/preprocessor.html)
Should not modify it, only adjust do changes in the preprocessor?
- …
=> rlnstcs fix

esmvalcore/config-developer.yml
=> Add institute mapping for CSIRO datasets

.circleci/config.yml, .github/pull_request_template.md, CONTRIBUTING.md, README.md, doc/esmvalcore/config.rst, doc/esmvalcore/derivation.rst
=> Update documentation so it uses the master branch by default

esmvalcore/cmor/check.py
=> Remove duplicate line in check.py

esmvalcore/cmor/check.py, esmvalcore/preprocessor/_time.py, tests/unit/preprocessor/_time/test_time.py
Remove auxiliary coordinates
**Tasks**
-   [x] Circle/CI tests pass. …
=> Remove automatic addition of time auxiliary coordinates

esmvalcore/preprocessor/_download.py
=> Support downloading fx files using synda

doc/esmvalcore/fixing_data.rst
Correct typo in documentation on how to implement a fix
=> Correct typo in documentation on how to implement a fix

esmvalcore/cmor/tables/custom/CMOR_hurStderr.dat
This adds a custom CMOR table for `hurStderr`. Necessary for ESMValGroup/ESMValTool#1508.
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmva …
=> Added custom CMOR table for hurStderr

esmvalcore/cmor/_fixes/cmip5/ec_earth.py, esmvalcore/cmor/_fixes/shared.py, tests/integration/cmor/_fixes/cmip5/test_ec_earth.py, tests/integration/cmor/_fixes/test_shared.py
=> Fix areacello in CMIP5 EC-Earth

esmvalcore/preprocessor/_time.py, tests/unit/preprocessor/_time/test_time.py
Closes:  https://github.com/ESMValGroup/ESMValCore/issues/481
=> Fix extract month

CITATION.cff, esmvalcore/_version.py, meta.yaml
New release needed for finishing ESMValGroup/ESMValTool#1432
=> Increase version to v2.0.0b6

esmvalcore/preprocessor/_mask.py
=> explicit conversion to float of min_value

esmvalcore/cmor/check.py, tests/unit/cmor/test_cmor_check.py
Closes #490 and is motivated by expert comment https://github.com/ESMValGroup/ESMValCore/issues/490#issuecomment-586322028
=> Remove attributes DimCoord and/or AuxCoord attribute from time coordinate

tests/unit/cmor/test_cmor_check.py
Fix a unit test that was broken when #475 got merged.
=> Fix test failing on stricter cmor check

doc/esmvalcore/preprocessor.rst, esmvalcore/preprocessor/_mask.py, tests/integration/preprocessor/_mask/test_mask.py
=> added test for simple mask combination for a small threshold for mask_fillvalues

esmvalcore/preprocessor/_volume.py
=> Extract_transect func still had mentions to extract_slice in raised exceptions

esmvalcore/_config.py, esmvalcore/_main.py, esmvalcore/_recipe_checks.py, esmvalcore/_task.py
Use Julia environment for running Julia diagnostics
- Also updated esmvalcore/_task.py so it makes use of the 'new' `pathlib` library instead of `os.path`
- Added a nicer error message in case you forgot to install an interpreter for some diagnostic language
**Tasks**
-   [x] Codacy code quality checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why. …
=> Use Julia environment for running Julia diagnostics

esmvalcore/_task.py
**Tasks**
If you need help with any of the tasks above, please do not hesitate to ask …
=> Fix bug with matplotlib backend environmental variable

CITATION.cff, esmvalcore/_version.py, meta.yaml
Increase version to v2.0.0b8, because we will need a new release after #555 has been merged.
**Tasks**
* * *
Related to #554
=> Increase version to v2.0.0b8

CONTRIBUTING.md
Fix a link in making a release section
=> Fix a link in making a release documentation

esmvalcore/cmor/_fixes/cmip5/fgoals_g2.py, esmvalcore/cmor/_fixes/cmip5/fgoals_s2.py, esmvalcore/cmor/_fixes/cmip6/fgoals_g3.py, esmvalcore/cmor/_fixes/shared.py, tests/integration/cmor/_fixes/cmip5/test_fgoals_g2.py, tests/integration/cmor/_fixes/cmip5/test_fgoals_s2.py, tests/integration/cmor/_fixes/cmip6/test_fgoals_g3.py, tests/integration/cmor/_fixes/test_shared.py
This PR adds fixes for `cl`, `cli` and `clw` for FGOALS models (CMIP5) and (CMIP6).
**Tasks**
-   [x] If writing a new/modified preprocessor function, please update the [documentation](https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/ …
=>  Added fixes for FGOALS models

setup.py
=> Avoid broken pytest-html plugin

esmvalcore/cmor/tables/custom/CMOR_vmrh2o.dat
Custom variable required by the `HALOE` observational dataset.
=> Add custom table for vmrh2o

meta.yaml
**Tasks**
-   [ ] This pull request has a descriptive title that can be used in a changelog …
=> Unpin on Python<3.8 for conda package (run)

esmvalcore/preprocessor/_derive/clltkisccp.py, esmvalcore/preprocessor/_derive/ctotal.py, esmvalcore/preprocessor/_derive/vegfrac.py
**Tasks**
~~-   Add unit tests~~ …
=> Fix derive scripts wrt required method

esmvalcore/cmor/check.py, tests/unit/cmor/test_cmor_check.py
=> Check coordinates do not have repeated standard names

CITATION.cff, esmvalcore/_version.py, meta.yaml
A new release is needed for #402 and ESMValGroup/ESMValTool#1545.
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
* * *
=> Increase version to v2.0.0b9

doc/changelog.rst, esmvalcore/utils/draft_release_notes.py
These are the release notes for v2.0.0b9 and some updates to the script to generate them.
**Tasks**
* * *
=> Add v2.0.0b9 release notes

esmvalcore/_task.py, tests/unit/test_task.py
=> Add a few unit tests for DiagnosticTask

esmvalcore/preprocessor/_derive/ctotal.py, tests/unit/preprocessor/_derive/test_ctotal.py
=> Fix derived variable ctotal calculation depending on project and standard name

setup.py
=> pin flake8<3.8.0

doc/api/esmvalcore.preprocessor.rst, doc/conf.py, doc/recipe/preprocessor.rst, doc/requirements.txt, setup.py
**Tasks**
If you need help with any of the tasks above, please do not hesitate to ask …
=> Document default order in which preprocessor functions are applied

esmvalcore/config-developer.yml
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files do not contain …
=> More flexible native6 default DRS

esmvalcore/preprocessor/_io.py, tests/integration/preprocessor/_io/test_concatenate.py
**Tasks**
If you need help with any of the tasks above, please …
=> Fix concatenation of a single cube

doc/conf.py
Update the copyright info on readthedocs, so it is the same as in ESMValGroup/ESMValTool#1664.
=> Update copyright info on readthedocs

environment.yml, tests/unit/preprocessor/_derive/test_ctotal.py
**Tasks**
-   [ ] This pull request has a descriptive title that can be used in a changelog …
=> Fix test for lower python version and add note on lxml

esmvalcore/_config.py
=> Avoid crashing when there is directory 'esmvaltool' in the current working directory

doc/requirements.txt, setup.py
Update Sphinx to v3, so our documentation builds again.
**Tasks**
=> Update Sphinx to v3 or later

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
Update the version to 2.0.0 and add release notes for the upcoming release.
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files do not contain mistakes
=> Increase version to 2.0.0 and add release notes

esmvalcore/_config.py
=> Options arg in read_config_user_file now optional (#709)

package/meta.yaml, setup.py
A new version of yamale has been released, but our schemas only work with v2. This pull request pins yamale to v2.
**Tasks**
* * *
Related to #717
=> Pin Yamale to v2

doc/quickstart/install.rst
Add installation instructions for pip installation
**Tasks**
* * *
Closes #84
=> Add installation instructions for pip installation

.pre-commit-config.yaml, doc/contributing.rst, setup.cfg, setup.py
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files …
=> Add pre-commit for linting/formatting

setup.cfg
Remove isort setup to fix formatting conflict with yapf
**Tasks**
* * *
Closes #777
=> Remove isort setup to fix formatting conflict with yapf

esmvalcore/_main.py
**Tasks**
-   [X] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom)
-   [X] This pull request has a descriptive title that can be used in a changelog
* * *
Closes https://github.com/ESMValGroup/ESMValTool/issues/1826
=> Sorted output for `esmvaltool recipes list`

.zenodo.json
**Tasks**
If you need help with any of the tasks above, please do not …
=> Update the zenodo file with contributors

doc/quickstart/run.rst, esmvalcore/_main.py
=> Improve command line run documentation

.zenodo.json
Add @mwjury 
* * *
Closes #801
=> Update the zenodo file with contributors (continued)

esmvalcore/cmor/_fixes/cmip6/mcm_ua_1_0.py, esmvalcore/cmor/_fixes/cmip6/noresm2_lm.py, tests/integration/cmor/_fixes/cmip6/test_mcm_ua_1_0.py, tests/integration/cmor/_fixes/cmip6/test_noresm2_lm.py
**Tasks**
-   [x] [Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do, if you haven't done so already (and add the link at the bottom) see #806 
-   [ ] If writing a new/modified preprocessor function, please update the [documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/recipe/preprocessor.html)
-   [ ] Circle/CI tests pass. Status can be seen below your pull …
=> Cmip6 lon bnds fixes

.github/workflows/action-conda-publish.yml, .github/workflows/action-pypi-build-and-deploy.yml
**Tasks**
-   [x] Please use `yamllint` to check that your YAML files …
=> Trigger pypi on release and conditional conda build on master

doc/contributing.rst
Update the instructions for making a release
=> Update instructions for making a release

esmvalcore/config-user.yml
Several paths were not set correctly for finding data on Mistral, this pull request improves that.
=> Fix path settings for DKRZ/Mistral

.github/workflows/action-conda-publish.yml, .github/workflows/action-install-from-conda.yml, .github/workflows/action-install-from-pypi.yml, .github/workflows/action-install-from-source.yml, .github/workflows/action-test.yml
=> switched miniconda conda setup hooks for Github Actions workflows

doc/changelog.rst
=> Add labels to changelogs of individual versions for easy reference (closes #898)

.github/workflows/action-install-from-conda.yml
Mirror from https://github.com/ESMValGroup/ESMValTool/pull/1969 and the issue documented in https://github.com/ESMValGroup/ESMValTool/issues/1968
=> Github Actions: change time when conda install test runs

tests/unit/experimental/test_utils.py
No need for that, also added maintainers in the recipes that are tested here see https://github.com/ESMValGroup/ESMValTool/pull/1970 - please run the tests and make sure all tests pass OK before committing and merging into `master` - two tests were failing due to lack of maintainers in the recipe!
=> remove redundant test line from test_utils.py

.circleci/config.yml, docker/Dockerfile, docker/Dockerfile.dev
Create a new conda environment to install ESMValCore in the docker containers, because updating the default conda environment leads to outdated dependencies as described in https://github.com/ESMValGroup/ESMValTool/issues/1980
-   Related to https://github.com/ESMValGroup/ESMValTool/issues/1980
***
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/intr …
=> Use new conda environment for installing ESMValCore in Docker containers

doc/quickstart/find_data.rst, esmvalcore/config-user.yml
-   Closes #862 
***
-   [x] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   [x] …
=> Change in config-user defaults and documentation with new location for esmeval OBS data on JASMIN

esmvalcore/_main.py
Improves traceability and bookkeeping
***
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or …
=> Print source file when using config get_config_user command

doc/changelog.rst
Changelog for v2.2.0, preview it [here](https://esmvaltool--983.org.readthedocs.build/projects/ESMValCore/en/983/changelog.html#v2-2-0)
***
-   [x] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/c …
=> Add first draft of v2.2.0 changelog

.github/pull_request_template.md, doc/contributing.rst
As we use them in the changelog, they are a must in every PR
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   [ ] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or …
=> Add checkbox in PR template to assign labels

setup.py
***
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new …
=> re-added fiona in setup.py

doc/changelog.rst
***
-   [ ] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new …
=> Final changelog for 2.2.0

setup.py
Change ESMValTool sample data instalation source from GitHub to PyPI to avoid deployment issues
-   Closes #997
***
-   [x] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contrib …
=> Install ESMValTool sample data from PyPI

doc/api/esmvalcore.api.config.rst, esmvalcore/experimental/config/__init__.py
-   Closes #1004 
-   Link to documentation: https://esmvaltool--1006.org.readthedocs.build/projects/ESMValCore/en/1006/
***
-   [x] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/lates …
=> Fix documentation build

doc/contributing.rst, doc/interfaces.rst, doc/quickstart/configure.rst, doc/recipe/overview.rst
Add section labels needed for linking from the ESMValTool documentation.
=> Add labels required for linking from ESMValTool docs

tests/unit/preprocessor/_area/test_area.py
=> Fix test that makes conda build fail

.github/pull_request_template.md, doc/api/esmvalcore.api.config.rst, doc/api/esmvalcore.rst, doc/contributing.rst, doc/develop/derivation.rst, doc/develop/fixing_data.rst, doc/develop/index.rst, doc/develop/preprocessor_function.rst, doc/interfaces.rst, doc/quickstart/configure.rst, doc/quickstart/install.rst, doc/quickstart/recipes.rst, doc/recipe/overview.rst
This pull request updates the contribution guidelines and the pull request template.
Link to documentation: https://esmvaltool--1047.org.readthedocs.build/projects/ESMValCore/en/1047/contributing.html
***
*** …
=> Update contribution guidelines

esmvalcore/preprocessor/_area.py
Add new id_prop key to try. 
Closes: #1070
***
***
=> Add key to id_prop

.github/workflows/action-conda-publish.yml, .github/workflows/action-install-from-conda.yml
via [Github Actions](https://github.com/ESMValGroup/ESMValCore/actions/runs/767382451) - that all pass with flying colors, so a job well done @zklaus :beer:
=> test installation of esmvalcore from conda-forge

doc/quickstart/install.rst
This PR adds a DKRZ-Mistral entry to the list of HPC clusters where a pre-installed version of ESMValTool is available. Related to #989 
Link to documentation: [https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/install.html](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/install.html)
***
*** …
=> Add instructions how to use the central installation at DKRZ-Mistral

doc/recipe/preprocessor.rst, esmvalcore/_recipe.py, esmvalcore/preprocessor/_ancillary_vars.py, esmvalcore/preprocessor/_area.py, tests/integration/preprocessor/_ancillary_vars/test_add_fx_variables.py, tests/integration/test_recipe.py
This pull request should address the issues reported in #1096. 
Closes #1096 
***
***
=> Review fx handling

.circleci/config.yml, setup.py
- Increase the timeout for running the `install`, `develop`, and `conda_build` test scenarios on CircleCI
- Add stub libraries required by mypy as development dependencies
Closes #1166 #1168
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in …
=> Fix failing CircleCI tests

.github/workflows/action-test.yml, esmvalcore/_config/_config.py
catastrophic tests failures resulting from the need to call`lru_cache` as a method in the decorator, for Python<3.8 (this was a bug in Python), why it hits us only now, beats me)
tests for Pythons (3.6 and 3.7 included) now [pass](https://github.com/ESMValGroup/ESMValCore/actions/runs/928470550)
Closes #1171 
***
*** …
=> fix lru cache decorator with explicit call to method

.circleci/config.yml, environment.yml, package/meta.yaml
This pull request fixes the problems with the nightly build on CircleCI.
- Use Python 3.9 to run the installation (from source installation and development installation) tests on CircleCI
- Skip mypy tests in conda build
Closes #1166
***
*** …
=> Pin Python to 3.9 in environment.yml on CircleCI and skip mypy tests in conda build

CITATION.cff, doc/contributing.rst, esmvalcore/_version.py, package/meta.yaml
This updates the version number in all the right places for release 2.3.0
***
***
=> Set version to 2.3.0

doc/changelog.rst
This updates the changelog with all the pull requests for 2.3.0.
Link to documentation: https://esmvaltool--1163.org.readthedocs.build/projects/ESMValCore/en/1163/changelog.html
***
*** …
=> Final changelog for 2.3.0

esmvalcore/config-user.yml
Thanks to @zklaus for noticing this! The DRS entries in the commented-out template for `config-user.yml` have now been updated for paths at JASMIN. I **think** CORDEX needs BADC everywhere since it was originally stored in BADC only.
Closes #1183 
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two …
=> update config-user.yml template with correct drs entries for CEDA-JASMIN

.circleci/config.yml, README.md, doc/contributing.rst, setup.cfg
Closes #961 
Link to documentation: https://esmvaltool--1190.org.readthedocs.build/projects/ESMValCore/en/1190/contributing.html#tests
***
***
=> Upload coverage to codecov

esmvalcore/preprocessor/_multimodel.py, tests/unit/preprocessor/_multimodel/test_multimodel.py
Filter warnings about collapsing multi-model dimension in multimodel statistics preprocessor function. This is a dimension that by definition does not have bounds, so the warnings do not make sense.
Closes #1219
***
*** …
=> Filter warnings about collapsing multi-model dimension in multimodel statistics preprocessor function

.circleci/config.yml
All tests in CircleCI are currently failing because an error in the curl instalation for the codecov reporter. This PR aims to fix this
=> Fix curl install in CircleCI

esmvalcore/_data_finder.py, tests/unit/data_finder/test_get_start_end_year.py
=> Add "." (dot) as allowed separation character for the time range group

CITATION.cff, doc/contributing.rst, esmvalcore/_version.py, package/meta.yaml
Upping the version number for the 2.3.1 bugfix release.
***
***
=> Bugfix release: set version to 2.3.1

doc/changelog.rst
Documenting changes included in bugfix release 2.3.1
***
***
=> Changelog 2.3.1

esmvalcore/experimental/templates/recipe_output_page.j2
Add link to plot directory in `index.html`
Closes #1254
***
***
=> Add link to plot directory in index.html

.circleci/config.yml, .github/workflows/action-conda-publish.yml, package/meta.yaml
Speeding up `conda_build` test using `boa` ([boa on conda](https://anaconda.org/conda-forge/boa) and [boa documentation](https://github.com/mamba-org/boa) - boa is part of the mamba project) and its extension to use `mamba` solver during build instead of the `conda` solver. Speedup of a few factors; tested with local build and on [Github Actions](https://github.com/ESMValGroup/ESMValCore/pull/1243/checks?check_run_id=3201971674)
Closes #1242 
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientif …
=> Speed up conda build `conda_build` Circle test by using `mamba` solver via `boa` (and use it for Github Actions test too)

esmvalcore/_data_finder.py, setup.py, tests/sample_data/experimental/test_run_recipe.py
With this change, the tool will no longer recursively look into all subdirectories for data. This speeds up finding data in certain cases and promotes a clean data organization.
Closes #281
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in …
=> Replace os.walk by glob.glob in data finder (only look for data in the specified locations)

.github/workflows/action-install-from-source.yml, .github/workflows/action-test.yml, environment.yml, package/meta.yaml, setup.py
Sister PR to https://github.com/ESMValGroup/ESMValTool/pull/2266
Closes https://github.com/ESMValGroup/ESMValTool/issues/2245
=> Unpin upper bound for iris (previously was at <3.0.4) 

esmvalcore/_main.py
Update the core development team in the start log message so it is the same as the members of @ESMValGroup/esmvaltool-coreteam.
@ESMValGroup/esmvaltool-coreteam Could you please check that this is correct?
***
=> Update the core development team

esmvalcore/preprocessor/_io.py, tests/integration/preprocessor/_io/test_load.py
=> Add 'comment' to list of removed attributes

esmvalcore/cmor/_fixes/cmip6/mpi_esm1_2_hr.py, tests/integration/cmor/_fixes/cmip6/test_mpi_esm1_2_hr.py
=> Add fix for differing latitude coordinate between historical and ssp585 in MPI-ESM1-2-HR r2i1p1f1

esmvalcore/cmor/_fixes/cmip6/ec_earth3.py, tests/integration/cmor/_fixes/cmip6/test_ec_earth3.py
=> Add fixes for time and latitude coordinate of EC-Earth3 r3i1p1f1

tests/integration/test_task.py
Speed up the unit tests of esmvalcore/_tasks.py by making a minimal selection that tests all functionality.
***
***
=> Speed up tests of tasks

doc/interfaces.rst, doc/requirements.txt, environment.yml, esmvalcore/_provenance.py, package/meta.yaml, setup.py, tests/integration/test_recipe.py
Closes #1135
Link to documentation: https://esmvaltool--1307.org.readthedocs.build/projects/ESMValCore/en/1307/interfaces.html
***
***
=> No longer make plots of provenance

doc/interfaces.rst
Update the documentation of the provenance interface so it is in line with the ESMValTool documentation here: https://docs.esmvaltool.org/en/latest/community/diagnostic.html#recording-provenance
Link to documentation: https://esmvaltool--1305.org.readthedocs.build/projects/ESMValCore/en/1305/interfaces.html#information-provided-by-the-diagnostic-script-to-esmvalcore
***
*** …
=> Update the documentation of the provenance interface

esmvalcore/_recipe.py, tests/integration/test_recipe.py
=> Removed automatic addition of areacello to obs4mips datasets

esmvalcore/_provenance.py
This pull request speeds up recording provenance. For recipe_impact.yml, it now takes 150 seconds on my laptop (used to be 2200 seconds).
Fixes part of #1298
***
***
=> Speed up provenance recording

esmvalcore/cmor/check.py, tests/unit/cmor/test_cmor_check.py
In #1217, the `obs4mips` project was renamed to `obs4MIPs`. However, #1032 added code that still used the old name and was not merged into #1217 before merging it. This pull request completes the rename.
***
*** …
=> Fix obs4MIPs capitalization

.github/workflows/action-install-from-source.yml, .github/workflows/action-pypi-build-and-deploy.yml, .github/workflows/action-test-monitor.yml, .github/workflows/action-test.yml, tests/integration/esgf/test_search_download.py
The syntax
```python
a = 1
f"{a=}"
```
is not supported in Python 3.7.
This pull request removes the use of that syntax.
***
***
=> Fix Python 3.7 tests

doc/recipe/overview.rst, esmvalcore/_recipe.py, esmvalcore/experimental/recipe_info.py, esmvalcore/experimental/recipe_output.py, esmvalcore/experimental/templates/RecipeInfo.j2, esmvalcore/experimental/templates/RecipeOutput.j2, esmvalcore/experimental/templates/TaskOutput.j2, esmvalcore/experimental/templates/head.j2, esmvalcore/experimental/templates/recipe_output_page.j2, esmvalcore/recipe_schema.yml, tests/integration/test_diagnostic_run.py, tests/integration/test_main.py, tests/integration/test_recipe.py, tests/sample_data/experimental/recipe_api_test.yml, tests/unit/experimental/test_output_file.py, tests/unit/experimental/test_recipe_info.py, tests/unit/experimental/test_recipe_output.py, tests/unit/test_recipe.py
This improves the results web page:
- Add titles to recipe and diagnostic
- Use the diagnostic description
- More compact layout
- Links to provenance and citation information added
- Link to work dir added
- Fixed link to plots dir if directory was moved after processing
It adds a mandatory `title` to the documentation section of recipes, this makes this pull request not backwards compatible. However, it should be easy to add titles to all recipes using their documentation webpage.
Optionally, diagnostic sections can now also have a title.
Closes #1319 
Link to documentation: https://esmvaltool--1332.org.readthedocs.build/projects/ESMValCore/en/1332/recipe/overview.html
***
It is the responsibility of the author to make sure the pull request is ready to review. The icons indicate whether …
=> Improve results web page

esmvalcore/cmor/_fixes/cmip6/ciesm.py, tests/integration/cmor/_fixes/cmip6/test_ciesm.py
=> Add fix for CIESM pr

CITATION.cff, esmvalcore/_version.py, package/meta.yaml
Update the version number for the upcoming release candidate.
=> Update version number for third release candidate 2.4.0rc3

doc/changelog.rst
=> Update changelog for 2.4.0rc3

CITATION.cff, esmvalcore/_version.py, package/meta.yaml
Update the version number for the release.
=> Update version number to final 2.4.0 release

doc/changelog.rst
Update changelog for 2.4.0
Closes #1342.
=> Update changelog for 2.4.0

doc/changelog.rst
=> Remove duplicate entries in changelog

.github/workflows/install-from-conda.yml, environment.yml, setup.py
`pandas` is no longer a required build dependency of `iris` so we should add it for our needs, since the package is actively used and imported in ESMValCore :panda_face: 
Closes #1401 
***
*** …
=> add `pandas` as dependency :panda_face: 

esmvalcore/_recipe.py, tests/unit/test_recipe.py
Added support of `extra_facets` to fx variables added by the preprocessor.
Closes #1398 
***
***
=> Added support of `extra_facets` to fx variables added by the preprocessor

doc/quickstart/install.rst
Suggested by @bouweandela - to be lifted from #1164 and dropped into a new stand-alone PR :+1: see https://github.com/ESMValGroup/ESMValCore/pull/1164#discussion_r765671097
***
***
=> Documentation on how to use HPC central installations

esmvalcore/_config/extra_facets/icon-mapping.yml, esmvalcore/_recipe.py, tests/integration/test_recipe.py
This PR correctly augments input for derived variables now with `extra_facets`.
Closes #1411
***
***
=> Augmented input for derived variables with extra_facets

tests/integration/cmor/_fixes/native6/test_era5.py
Dodgy old method that now is at odds with `numpy=1.22` - frankly I don't see why we use it?
Closes https://github.com/ESMValGroup/ESMValCore/issues/1418
***
***
=> remove accessing `.xml()` cube method from test

.circleci/config.yml, doc/quickstart/install.rst, setup.py
Python=3.10 is here and we don't have any issues using it, let's up the bits that specify 3.9 to 3.10!
Closes #1431 
***
***
=> Add Python=3.10 to package info, update Circle CI auto install and documentation for Python=3.10

.github/workflows/build-and-deploy-on-pypi.yml, .github/workflows/install-from-conda.yml, .github/workflows/install-from-pypi.yml, .github/workflows/install-from-source.yml, .github/workflows/run-tests-monitor.yml, .github/workflows/run-tests.yml
Adding `python=3.10` to the list of tested for Python versions in the Github Actions runs; note that the GA that builds the PyPi package uses the latest Python version that is now 3.10 so this has changed to 3.10.
Closes #1425 
***
*** …
=> Add Python=3.10 to Github Actions and switch to Python=3.10 for the Github Action that builds the PyPi package

package/meta.yaml, setup.py
@bouweandela and I have decided to pin flake8, so we stop getting garbage instead of actual FLAKE8 issues when tests fail with FLAKE8 issues
Closes #1405 
***
*** …
=> Pin `flake8<4` to keep getting relevant error traces when tests fail with FLAKE8 issues

doc/quickstart/install.rst
@bouweandela had the good idea to add a link to the conda lock file in the documentation, see his comment https://github.com/ESMValGroup/ESMValCore/pull/1164#issuecomment-1028848853 so am adding it in here :lock_with_ink_pen: 
***
*** …
=> add direct link to download conda lock file in the install documentation

.github/workflows/cffconvert.yml, .github/workflows/citation_file_validator.yml, CITATION.cff
Hello!
We noticed that your CITATION.cff had a small issue and fixed it - possibly by just updating cffversion to 1.2.0.
In addition to the fix, this Pull Request automates validation of the CITATION.cff file using the [cffconvert GitHub Action](https://github.com/marketplace/actions/cffconvert). That way, it's a little bit easier to be robust against future changes to the CITATION.cff file.
BTW it's perfectly fine if you don't feel like accepting this Pull Request for whatever reason -- we just thought it might be helpful is all.
We found your repository using a partially automated workflow; if you have any questions about that, feel free to create an issue over at https://github.com/cffbots/filtering/issues/
On behalf of the cffbots team,
@abelsiqueira / @fdiblen / @jspaaks …
=> Local PR for #1459 CITATION.cff fix and automatic validation of your citation metadata

esmvalcore/_provenance.py
=> Fix provenance file permissions

doc/contributing.rst
This PR adds documentation on how to deprecate features. 
Closes #1421
Link to documentation: https://esmvaltool--1426.org.readthedocs.build/projects/ESMValCore/en/1426/contributing.html#backward-compatibility
***
*** …
=> Updated documentation on how to deprecate features

doc/quickstart/install.rst
Added a reference hook so I can reference the section from elsewhere, sorry I forgot to add it yesterday
***
***
=> added reference hook to conda lock shtuffs in documentation install section

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
=> Increased ESMValCore version to 2.5.0rc2

doc/conf.py
Restores the old `scipy` intersphinx mapping that works again.
***
=> Restored `scipy` intersphinx mapping

tests/integration/data_finder.yml
Contributes to close #1353 by creating DRS path test for two flavors of ISPLCM filenames
Also builds on discussion in #1377
***
***
=> Add DRS path test for IPSLCM files

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
=> Increased ESMValCore version to 2.5.0rc3

doc/develop/fixing_data.rst
This PR adds a link to access the version `V220` of the MSWEP dataset. This version is no longer available on the source website (http://www.gloh2o.org/) but was used to develop the recipe `hydrology/recipe_hydro_forcing.yml`. The new link was already mentioned in #969.
Closes #1505 
Link to documentation: https://esmvaltool--1506.org.readthedocs.build/projects/ESMValCore/en/1506/develop/fixing_data.html#observational-datasets
***
~~- [ …
=> Fix download instructions for the MSWEP dataset

doc/quickstart/find_data.rst
This PR simply aims at aligning the documentation with the new cmorizer framework from [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657). Since observation downloading and reformatting is handled by the tool, this is just a cosmetic change. To be merged only after [#1657](https://github.com/ESMValGroup/ESMValTool/pull/1657).
Related to https://github.com/ESMValGroup/ESMValTool/pull/1657
Link to documentation: https://docs.esmvaltool.org/projects/esmvalcore/en/latest/quickstart/find_data.html
***
[2]: …
=> Documentation updated for the new cmorizer framework

environment.yml, package/meta.yaml, setup.py
=> Pinned `iris`

.github/workflows/run-tests.yml, tests/unit/test_iris_io.py
@schlunma finding the serious saving issue presented in #1509 prompted me to think we should have a test module that tests all these serious bugs from `iris` IO, no matter they fix them - just so that we are sure they don't resurface. These are cheap tests and shouldn't be a burden on the testing and CI performance.
- Test runs with `iris=3.2.0.post0` FAIL [here](https://github.com/ESMValGroup/ESMValCore/runs/5321735240?check_suite_focus=true)
- Test runs with `iris=3.1` PASS [here](https://github.com/ESMValGroup/ESMValCore/runs/5360398116?check_suite_focus=true)
***
[1]: …
=> [Tests fail `iris>=3.2.0`] Add a test module that runs tests of `iris` I/O everytime we notice serious bugs there

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
https://esmvaltool--1519.org.readthedocs.build/projects/ESMValCore/en/1519/changelog.html
***
=> Increased ESMValCore version to 2.5.0rc4

environment.yml, package/meta.yaml, setup.py
Pin `iris>=3.1.0,<3.2.0`. See discussion in https://github.com/ESMValGroup/ESMValCore/issues/1509.
Closes https://github.com/ESMValGroup/ESMValCore/issues/1509
***
*** …
=> Pinned iris<3.2.0

README.md
Here's a very nice and easy PR for your consideration: adding a GA test badge - this is very simple to create: simply go to the Actions tab, click on the test you want to create a badge for on the left side, where all the available (and active) tests are, then three dots on the right side, and select Create Badge, copy the Markdown text and plop it in the README - voila!
***
***
- 🙏 We kindly ask …
=> add Github Actions Test badge in README

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
https://esmvaltool--1529.org.readthedocs.build/projects/ESMValCore/en/1529/changelog.html
***
=> Increased ESMValCore version to 2.5.0rc5

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
https://esmvaltool--1532.org.readthedocs.build/projects/ESMValCore/en/1532/changelog.html
***
=> Increased ESMValCore version to 2.5.0rc6

CITATION.cff, doc/changelog.rst, esmvalcore/_version.py, package/meta.yaml
https://esmvaltool--1534.org.readthedocs.build/projects/ESMValCore/en/1534/changelog.html
***
=> Increased ESMValCore version to 2.5.0

doc/develop/fixing_data.rst, doc/quickstart/configure.rst, doc/quickstart/find_data.rst
The documentation on how to include native datasets is sparse and also wrong at some points. This PR fixes this.
Link to doc:
- How to add support for new native datasets (`develop/fixing_data`): https://esmvaltool--1559.org.readthedocs.build/projects/ESMValCore/en/1559/develop/fixing_data.html#add-support-for-new-native-datasets
- List of supported native datasets (`quickstart/find_data`): https://esmvaltool--1559.org.readthedocs.build/projects/ESMValCore/en/1559/quickstart/find_data.html#datasets-in-native-format
- Example for config-developer entry ( `quickstart/configure`): https://esmvaltool--1559.org.readthedocs.build/projects/ESMValCore/en/1559/quickstart/configure.html#configuring-datasets-in-native-format
It is the responsibility of the author to make sure the pull request is …
=> Improved documentation on native dataset support

doc/recipe/preprocessor.rst, esmvalcore/preprocessor/__init__.py, esmvalcore/preprocessor/_regrid.py, tests/integration/preprocessor/_regrid/test_extract.py, tests/integration/preprocessor/_regrid/test_extract_coordinate_points.py, tests/unit/preprocessor/_regrid/__init__.py
This PR adds a general `extract` preprocessor to extract points from any coordinate following either a `linear` or a `nearest` scheme. It was contributed by Javi but never made it to this repo. Just added some tests.
Closes #1563 
***
*** …
=> Add general `extract_coordinate_points` preprocessor

CITATION.cff
Adding @dhohn to the CITATION file - David, do you mind adding your affiliation and ORCID no (if you have one, if not, just remove the line) please here, mate? Then approve the PR pls :beer: 
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) in …
=> Add David Hohn to contributors' list

.circleci/config.yml
The CircleCI cache for the main branch was never updated. This pull request adds the year and week number to the cache key, so CircleCI caches are refreshed every week. See [here](https://circleci.com/docs/2.0/configuration-reference/#savecache) for info.
***
*** …
=> Refresh CircleCI cache weekly

.circleci/config.yml
Followup pull request on #1597, because I forgot to update the cache key when restoring the cache.
***
***
=> Use correct cache restore key on CircleCI

docker/Dockerfile, docker/Dockerfile.dev
This PR should fix the Docker build
Closes #1629 
***
***
=> Remove update command in Dockerfile

esmvalcore/preprocessor/_time.py, tests/unit/preprocessor/_time/test_time.py
This should add needed tests and docs to finish off #1250.
Once merged, #1250 will need to be rebased onto main to get the tests passing then should be good to go I think...
=> Add tests and docs

CITATION.cff
This PR increases the release version number to the first release candidate for version 2.6 (v2.6.0rc1)
***
***
=> Increase version number for ESMValCore v2.6.0rc1

doc/conf.py, doc/contributing.rst
As requested in https://github.com/ESMValGroup/ESMValTool/pull/2613#discussion_r891239939, this adds a note to the documentation on making a release to give the required permissions to the new release manager.
Link to documentation: https://esmvaltool--1645.org.readthedocs.build/projects/ESMValCore/en/1645/contributing.html#making-a-release
***
*** …
=> Add a note on transferring permissions to the release manager

doc/contributing.rst
This adds documentation on building and uploading Docker containers. Similar to https://github.com/ESMValGroup/ESMValTool/pull/2662.
Links to documentation:
- https://esmvaltool--1644.org.readthedocs.build/projects/ESMValCore/en/1644/contributing.html#check-that-all-tests-and-builds-work
- https://esmvaltool--1644.org.readthedocs.build/projects/ESMValCore/en/1644/contributing.html#check-the-docker-images
***
***
To help with the number …
=> Add documentation on building and uploading Docker images

CITATION.cff, doc/changelog.rst
This PR updates the changelog and the Citation file for the release of v2.6.0rc3
Link to documentation: https://esmvaltool--1646.org.readthedocs.build/projects/ESMValCore/en/1646/changelog.html#v2-6-0
***
~- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~
~- [ ] [🧪][2] The new functionality is [relevant and scientifically …
=> Update changelog and version for 2.6rc3

doc/quickstart/install.rst
Similar to https://github.com/ESMValGroup/ESMValTool/issues/1888 but for the Core
Link to documentation: https://esmvaltool--1647.org.readthedocs.build/projects/ESMValCore/en/1647/quickstart/install.html#pre-installed-versions-on-hpc-clusters
***
~~- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
~~- [ ] [🛠][1] Changes are [backward …
=> Update documentation on ESMValTool module at DKRZ

CITATION.cff, doc/changelog.rst
This PR updates the CITATION file for version 2.6 of ESMValCore. Just leaving this ready for tomorrow.
~Closes #issue_number~
***
~- [ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~
*** …
=> Set final version of ESMValCore for 2.6

esmvalcore/preprocessor/_area.py
=> Add support for regions stored as MultiPolygon to extract_shape preprocessor

doc/quickstart/install.rst
Adds the Met Office installation method under Mistral and JASMIN.
Closes #1691 
Link to documentation: https://esmvaltool--1692.org.readthedocs.build/projects/ESMValCore/en/1692/quickstart/install.html#pre-installed-versions-on-hpc-clusters-other-servers
***
*** …
=> Add Met Office Installation Method

doc/contributing.rst
Add some clarifying comments in the `Making a release section` of the documentation.
Closes #1688 
Link to documentation: https://esmvaltool--1689.org.readthedocs.build/projects/ESMValCore/en/1689/contributing.html#making-a-release
***
~- [ ] [🧪][2] The new functionality is [relevant and scientifically sound](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#scientific-relevance)~
~- [ ] [🛠][1] Code is written …
=> Update `Making a release` section of the documentation

.github/workflows/run-tests.yml, environment.yml, setup.py
***
Since we are not using the plugin anymore, we can now unpin flake8 to free :whale: 
See #1696.
***
=> Unpin flake8

esmvalcore/iris_helpers.py, esmvalcore/preprocessor/_mask.py, tests/integration/preprocessor/_mask/test_mask.py, tests/integration/test_recipe.py, tests/unit/test_iris_helpers.py
This PR removes code that has been scheduled for removal in v2.8.0 or earlier versions.
***
***
=> Remove deprecated features scheduled for removal in v2.8.0 or earlier

esmvalcore/esgf/_search.py, setup.py
Port changes from https://github.com/ESMValGroup/ESMValCore/pull/1834 into the 2.7.1 bugfix release branch.
=> [v2.7.1 bugfix release] fix esgf search as from PR 1834 and include change for v2.7.1 bugfix release

doc/quickstart/configure.rst, esmvalcore/_config/_esgf_pyclient.py, tests/integration/esgf/search_results/Amon_r1i1p1_historical,rcp85_INM-CM4_CMIP5_tas.json, tests/integration/esgf/search_results/Amon_r1i1p1_historical_FIO-ESM_CMIP5_tas.json, tests/integration/esgf/search_results/Amon_r1i1p1_rcp85_HadGEM2-CC_CMIP5_tas.json, tests/unit/config/test_esgf_pyclient.py
Changes from #1838 ported to v2.7.1 bugfix release
=> [v2.7.1 bugfix release] Update CEDA ESGF index node hostname ported to v2.7.1

environment.yml, setup.py
=> Pin esmpy<8.4

esmvalcore/config-developer.yml
=> Update filename template for obs4MIPs to better match filenames

doc/changelog.rst
I promised this to @remi-kazeroni but only got around to do it now :beer: 
Closes #1904 
Link to documentation: [for PR1905](https://esmvaltool--1905.org.readthedocs.build/projects/ESMValCore/en/1905/changelog.html)
***
*** …
=> add changelog for latest released version v2.7.1

doc/recipe/preprocessor.rst
The NCEP dataset is now renamed to NCEP-NCAR-R1.
This is a companion pull request to [#2932](https://github.com/ESMValGroup/ESMValTool/pull/2932) from the ESMValTool repository.
Update to the documentation due to the renaming from the "NCEP" dataset to "NCEP-NCAR-R1".
The changes are **not** backward compatible, but this should also be handled with the pull request [#2932](https://github.com/ESMValGroup/ESMValTool/pull/2932).
***
***
To …
=> Update preprocessor.rst due to renaming of NCEP dataset to NCEP-NCAR-R1

CITATION.cff
This PR increases the release version number to the first release candidate for version 2.8 (v2.8.0rc1)
***
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#dependencies) correctly~~
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#re …
=> Increase version number for ESMValCore v2.8.0rc1

doc/gensidebar.py
Make the table of contents the same when viewing the ESMValCore and ESMValTool documentation.
Link to documentation: https://esmvaltool--1958.org.readthedocs.build/projects/ESMValCore/en/1958/
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) …
=> Synchronize documentation table of contents with ESMValTool

doc/contributing.rst
This PR adds a missing link to the ESMValTool documentation: https://docs.esmvaltool.org/en/latest/community/release_strategy.html#detailed-timeline-steps
It's recommended to read these detailed steps before making a Core release.
Related to https://github.com/ESMValGroup/Community/discussions/79
Link to documentation: [here](https://esmvaltool--1957.org.readthedocs.build/projects/ESMValCore/en/1957/contributing.html#making-a-release)
***
[2]: https://docs.esmvaltool.org/en/latest/community/review.html#scientific-revie …
=> Add link to ESMValTool release procedure steps

esmvalcore/config/extra_facets/cmip5-institutes.yml
Changes institute from `CSIRO-QCCCE` to `UNSW` to make data from the `CSIRO-Mk3L-1-2` model downloadable on ESGF.
Closes #1965 
***
~~- [ ] [🧪][2] and [🛠][1] [Documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#documentation) is available~~
~~- [ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
~~- [ ] …
=> Update the institute facet of the CSIRO-Mk3L-1-2 model

CITATION.cff
This PR increases the release version number to the second release candidate for version 2.8 (v2.8.0rc2)
***
~~- [ ] [🛠][1] Changes are [backward compatible](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#backward-compatibility)~~
~~- [ ] [🛠][1] Any changed [dependencies have been added or removed](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributi …
=> Increase version number for ESMValCore v2.8.0rc2

.github/workflows/run-tests.yml, environment.yml, setup.py
Closes #1975 and should help with #1974 
Link to documentation: https://readthedocs.org/projects/esmvalcore/builds/19816340/
***
***
=> Re-pin sphinx to latest 6.1.3

CITATION.cff
Release candidate rc2 will be released tomorrow as stable Core `v2.8.0`. This PR update the version number to `v2.8.0`
***
***
=> Increase version number for ESMValCore `v2.8.0`

.readthedocs.yaml, doc/api/esmvalcore.cmor.rst, doc/conf.py, esmvalcore/cmor/check.py
=> Python311-klaus

environment.yml, setup.py
PR opened off my phone, so will need a bit of cleanup after I open it
Closes #2010 
***
***
=> Pin numpy !=1.24.3

doc/api/esmvalcore.cmor.rst, doc/conf.py, environment.yml, esmvalcore/cmor/check.py, setup.py
=> Python311 klaus

esmvalcore/preprocessor/_regrid.py, tests/integration/preprocessor/_regrid/test_extract_location.py
=> Use default SSL context when using geopy.geocoders.Nominatim

.github/workflows/create-condalock-file.yml
Sister PR to https://github.com/ESMValGroup/ESMValTool/pull/3174
***
***
=> [condalock] modernize conda lock file creation workflow with mamba, Mambaforge etc

esmvalcore/experimental/recipe_output.py, esmvalcore/experimental/templates/TaskOutput.j2
This uses the `os.path.relpath` function to compute relative paths for the output in `index.html`. This function supports paths that are not a subpath of each other, unlike `pathlib.Path.relative_to` (note [2](https://docs.python.org/3/library/pathlib.html#id4)).
Closes #2054
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests …
=> Fix issue with writing index.html when using --resume-from

setup.py
Remove the `[vectorized]` extra because it is not supported by shapely 2.
***
***
=> Remove vectorized extra from shapely

doc/changelog.rst
Add changelog for v2.8.1
Link to documentation: https://esmvaltool--2079.org.readthedocs.build/projects/ESMValCore/en/2079/changelog.html#v2-8-1
***
***
=> Add changelog for v2.8.1

doc/changelog.rst
=> Add v2.8.1 release notes

CITATION.cff, doc/changelog.rst
Add the changelog for the upcoming v2.9.0 release and increments the version and release date to v2.9.0rc1 in CITATION.cff.
Link to documentation: https://esmvaltool--2088.org.readthedocs.build/projects/ESMValCore/en/2088/changelog.html#v2-9-0
***
*** …
=> Add changelog for v2.9.0

esmvalcore/cmor/_fixes/cmip6/giss_e2_1_g.py, tests/integration/cmor/_fixes/cmip6/test_giss_e2_1_g.py
=> Correct GISS-E2-1-G `tos` units

README.md
Sister PR to https://github.com/ESMValGroup/ESMValTool/pull/3258
***
***
=> Fix gitter badge in README

CITATION.cff, doc/changelog.rst
Final updates for the release:
- update the release notes with latest changes
- update the version number and release date in CITATION.cff
Link to documentation: https://esmvaltool--2123.org.readthedocs.build/projects/ESMValCore/en/2123/changelog.html#v2-9-0
***
*** …
=> Update changelog and release date for v2.9.0 release

CITATION.cff, README.md, doc/changelog.rst, doc/recipe/preprocessor.rst, esmvalcore/_citation.py, esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg.py, esmvalcore/cmor/_fixes/cmip6/giss_e2_1_g.py, esmvalcore/esgf/_search.py, esmvalcore/preprocessor/_io.py, esmvalcore/preprocessor/_regrid.py, setup.py, tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg.py, tests/integration/cmor/_fixes/cmip6/test_giss_e2_1_g.py, tests/unit/esgf/test_search.py, tests/unit/preprocessor/_regrid/test_regrid.py, tests/unit/test_citation.py
Merge `v2.9.x` into `main` to get versioning correctly.
***
***
=> Merge v2.9.x into main

doc/contributing.rst
Closes #2133 
Link to documentation: https://esmvaltool--2131.org.readthedocs.build/projects/ESMValCore/en/2131/contributing.html#mark-the-release-in-the-main-branch
***
***
=> Add merge instructions to release instructions

CITATION.cff
There is a small typo in CITATION.cff, leading to a failed check: https://github.com/ESMValGroup/ESMValCore/actions/runs/5968126913/job/16191265040. This pull request fixes issue.
***
*** …
=> Fix typo in citation file

esmvalcore/preprocessor/__init__.py
Many preprocessor function reduce the data in size, resulting in chunks that are too small. This pull request addresses the issue by rechunking between preprocessor functions. This results in smaller task graphs, reducing the risk of overloading the scheduler.
This helps with issue #2184.
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of- …
=> Rechunk between preprocessor steps

esmvalcore/preprocessor/_mask.py
I've set back one line in the code from dask to numpy because I accidently changed it.
***
=> Restored usage of numpy in `_mask_with_shp`

doc/recipe/preprocessor.rst
This removes some outdated documentation that I overlooked in https://github.com/ESMValGroup/ESMValCore/pull/2202. This should also fix the documentation build.
Link to documentation: https://esmvaltool--2210.org.readthedocs.build/projects/ESMValCore/en/2210/recipe/preprocessor.html
Closes  #2211
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#re …
=> Remove outdated documentation

README.md
The Meercode monitoring badge is blank because their [API](https://api.meercode.io/api) has been broken for a while now - they stopped sending weekly emails with test stats too, and their GitHub repos don't really allow for opening issues. Frankly, since nobody apart from me was checking these stats, we may as well get rid of them. @zklaus it'd be good if you allowed this as a bugfix for 2.10 so our README looks complete :smiley: 
*** …
=> remove meercode badge from README because their API is broken

esmvalcore/_main.py
Fixes https://github.com/ESMValGroup/ESMValTool/issues/3383
***
***
=> Correct usage help text of version command

esmvalcore/_recipe/from_datasets.py, tests/unit/recipe/test_from_datasets.py
=> Fix a problem with sorting datasets that have a mix of facet types

esmvalcore/cmor/_fixes/fix.py, esmvalcore/cmor/check.py
This speeds up the CMOR checks and fixes by accessing coordinate data in parallel when it is lazy and avoids computing the same thing multiple times in the generic longitude fix.
***
*** …
=> Faster coordinate checks and longitude fix

.github/workflows/install-from-condalock-file.yml
Nightly tests that install the show from conda lock files currently [fail](https://github.com/ESMValGroup/ESMValCore/actions/runs/7054003141/job/19222400255) because conda is a PITA as per usual; at any rate, prob better to have all deps from conda-forge too, and not mess about with `pip` post-installed from outside the lock file.
***
*** …
=> [conda-lock] fix test installation from conda-lock file: use `pip` from lock file

README.md
Closes #2259
Proves out it's a very straightforward solution, and these shields can be created on the fly
***
***
=> fix anaconda badge without hardcode version

.circleci/config.yml
Currently test failing at mamba env create step with error code 137 - running out of memory. Changing the resource allocation to `medium` (as @bouweandela explains in this comment https://github.com/ESMValGroup/ESMValCore/pull/2273#discussion_r1419295312) for the `build_documentation` test does the trick. We should really measure how much mem the mamba env building really needs, it could be that we can optimize it (in a separate PR).
***
- ~[ ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do~
[1]: …
=> [CircleCI] Fix `build_documentation` test

doc/changelog.rst, doc/conf.py, doc/quickstart/configure.rst
Use short links in the changelog as requested in https://github.com/ESMValGroup/ESMValTool/pull/3462#pullrequestreview-1790697752
Links to documentation:
- https://esmvaltool--2287.org.readthedocs.build/projects/ESMValCore/en/2287/changelog.html
- https://esmvaltool--2287.org.readthedocs.build/projects/ESMValCore/en/2287/quickstart/configure.html#dask-distributed-configuration
***
***
- 🙏 We kindly …
=> Use short links in changelog

.circleci/config.yml
The nightly tests have been failing recently ([example](https://app.circleci.com/pipelines/github/ESMValGroup/ESMValCore/10196/workflows/0a2f5b00-b2cf-49dd-af9b-8fa0913a84f9/jobs/43871)) with an out-of-memory error. This increases the resources available to the test from 2GB to 4GB ([see here](https://circleci.com/docs/configuration-reference/#docker-execution-environment)).
***
***
- 🙏 We kindly …
=> Increase resources for testing installation from conda-forge

.github/workflows/run-tests.yml, environment.yml, setup.py
Closes #2314 
Pretty self-explanatory :grin: 
NOTE: the `pytest-mypy` package from conda-forge is very old https://anaconda.org/conda-forge/pytest-mypy so I removed it altogether from the conda environment file and we should only install it from PyPI (unless one of us wants to go and update their pkg at the feedstock)
***
*** …
=> Pin `pytest-mypy` plugin to `>=0.10.3` comply with new `pytest==8`

esmvalcore/preprocessor/_multimodel.py
In https://github.com/ESMValGroup/ESMValCore/pull/2191, I missed to update parts of the multi-models statistics API doc. This PR takes care of that.
Link to documentation: https://esmvaltool--2321.org.readthedocs.build/projects/ESMValCore/en/2321/api/esmvalcore.preprocessor.html#esmvalcore.preprocessor.multi_model_statistics
***
*** …
=> Update `multi_model_statistics doc` with latest changes (new operators, etc.)

esmvalcore/preprocessor/_time.py, esmvalcore/preprocessor/_volume.py, tests/unit/preprocessor/_time/test_time.py, tests/unit/preprocessor/_volume/test_volume.py
=> Use lazy weights for `climate_statistics` and `axis_statistics`

esmvalcore/cmor/_fixes/icon/_base_fixes.py, esmvalcore/cmor/_fixes/icon/icon.py, tests/integration/cmor/_fixes/icon/test_icon.py
This pull request adds support for variables rtnt and rtmt for ICON.
* @schlunma Support is needed in writing the related Unit test
***
***
=> Added ICON fix for rtnt

esmvalcore/config/extra_facets/icon-mappings.yml
This PR adds more variables to the ICON extra facets file.
***
***
=> Expanded ICON extra facets

README.md
Fix the link to Codacy in the readme.
***
***
=> Fix Codacy badge

esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py
This is a follow up for issue #2384. The only thing I changed in the ESMValCore/esmvalcore/cmor/_fixes/cmip6/gfdl_cm4.py as that now the fix SfcWind is calling Uas (10m) instead of Tas (2m). The Uas and Tas fixes already have tests.
***
=> Add 10m height coordinate to SfcWind GFDL-CM4 instead of 2m height

doc/recipe/preprocessor.rst
`weighted` -> `weights`
Link to documentation: https://esmvaltool--2387.org.readthedocs.build/projects/ESMValCore/en/2387/recipe/preprocessor.html#examples
***
***
=> Fixed typo in doc about weighted statistics

.circleci/config.yml
See https://github.com/codacy/codacy-coverage-reporter and the issue about skipping when on forks https://github.com/codacy/codacy-coverage-reporter/issues/500
***
***
=> update codacy reporter orb to latest version

.github/workflows/run-tests-monitor.yml, .github/workflows/run-tests.yml
Closes #2390 
Since that issue with mamba, it's best to have our own env inspectors in, and the reason they are called after pip install is that we should be able to catch any package installed from PyPI (whether we want it to be or not).
***
*** …
=> add calls to `conda list` in Github Action test workflows to inspect environment

esmvalcore/config-user.yml
Add native6, OBS6 and RAWOBS rootpaths to metoffice config-user.yml template, and remove temporary dir. Linked Tool PR: https://github.com/ESMValGroup/ESMValTool/pull/3613
Closes #2431 
Link to documentation: https://esmvaltool--2432.org.readthedocs.build/projects/ESMValCore/en/2432/
***
- ~~[ ] [🛠][1] [Unit tests](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/contributing.html#tests) have been added~~
- ~~[ ] [🛠][1] Any …
=>  Add native6, OBS6 and RAWOBS rootpaths to metoffice config-user.yml template, and remove temporary dir

doc/quickstart/configure.rst
Add documentation on how to configure Dask with the default scheduler and for debugging purposes.
Link to documentation: https://esmvaltool--2435.org.readthedocs.build/projects/ESMValCore/en/2435/quickstart/configure.html#dask-default-scheduler-configuration
***
*** …
=> Add advice on configuring Dask

environment.yml, setup.py
This PR adds the `iris-grib` dependency in order to update the docker container to get successful tests for #2178 (following [this](https://github.com/ESMValGroup/ESMValCore/pull/2178#issuecomment-1780664119) comment).
Related to #2178
***
*** …
=> Added iris-grib depedency

doc/index.rst
Update the main documentation page, which was updated in https://github.com/ESMValGroup/ESMValTool/pull/3628, so it looks the same when viewing the ESMValCore subproject.
Link to documentation: https://esmvaltool--2464.org.readthedocs.build/projects/ESMValCore/en/2464/
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two …
=> Synchronize initial documentation page

CITATION.cff
=>  Update the release date and version number for v2.11.0

.circleci/config.yml, doc/conf.py
Add a nightly test with development versions of upstream packages, to signal problems early. As agreed at the [tech lead team meeting on 2024-07-02](https://github.com/ESMValGroup/Community/blob/main/Tech%20Lead/Minutes/20240702.md).
Other changes in this pull request:
- update the orbs to the latest versions
- write logs also to the terminal for easier viewing
***
*** …
=> Run a nightly test with the development version of dependencies

esmvalcore/config/extra_facets/access-mappings.yml, tests/integration/cmor/_fixes/access/test_access_esm1_5.py
make a slight change in title of `access-mapping.yml` to avoid a potential bug
Closes #2483 
***
***
=> fix `access-mapping.yml` extra_facets title

.pre-commit-config.yaml
Disable automatic fixes by pre-commit.ci, see e.g. [f905f39](https://github.com/ESMValGroup/ESMValCore/pull/2526/commits/f905f39147eb61496a0433c34280ae681fea58cb)
***
***
=> Disable automatic fixes by pre-commit.ci

.git-blame-ignore-revs
Ignore reformatting operations when viewing git blame.
***
***
=> Ignore reformatting when viewing git blame

README.md
It's a good idea to have one! Badge code is visible on [our Pre-Commit page](https://results.pre-commit.ci/repo/github/190192145) and can be seen in action on the branch https://github.com/ESMValGroup/ESMValCore/tree/add_precommit_badge
***
*** …
=> add a pre-commit badge to README

.circleci/config.yml
=> Disable upstream tests on commits

CITATION.cff, doc/changelog.rst
=> Update changelog and version to v2.11.1

esmvalcore/config/extra_facets/emac-mappings.yml
This PR adds more commonly used variables (mostly derived ones) to the EMAC extra facets.
***
***
=> Added more variables to EMAC extra facets

esmvalcore/_main.py
As discussed some time ago at a workshop, we would like to remove individual community members' email addresses from the tool's startup message because they tend to get outdated. This pull request replaces them with the esmvaltool development team email address.
***
*** …
=> Update the `esmvaltool` command welcome message

.github/workflows/citation_file_validator.yml, .github/workflows/create-condalock-file.yml, .github/workflows/install-from-conda.yml, .github/workflows/install-from-condalock-file.yml, .github/workflows/install-from-pypi.yml, .github/workflows/install-from-source.yml, .github/workflows/run-tests-monitor.yml, .github/workflows/run-tests.yml
=> restrict runs of cron Github Actions on forks

doc/changelog.rst
Add release notes in the changelog.
Link to documentation: https://esmvaltool--2662.org.readthedocs.build/projects/ESMValCore/en/2662/changelog.html
***
***
=> Add release notes for v2.12.0rc1

esmvalcore/cmor/_fixes/cmip6/ec_earth3_veg_lr.py, esmvalcore/cmor/_fixes/cmip6/noresm2_mm.py, tests/integration/cmor/_fixes/cmip6/test_ec_earth3_veg_lr.py, tests/integration/cmor/_fixes/cmip6/test_noresm2_mm.py
Rename the index coordinate long name so it is consistent across experiments for NorESM2-MM and EC-Earth3-Veg-LR.
This should fix running `examples/recipe_easy_ipcc.yml`.
Related to https://github.com/ESMValGroup/ESMValTool/issues/3916#issuecomment-2666192010
***
*** …
=> Add a fix for differing index coord long names in NorESM2-MM and EC-Earth3-Veg-LR

CITATION.cff, doc/changelog.rst
This PR updates the version for the second release candidate of v2.12.0 and updates the changelog with the bugfixes found in the first round of testing.
Related to https://github.com/ESMValGroup/ESMValTool/issues/3916
Link to documentation: https://esmvaltool--2675.org.readthedocs.build/projects/ESMValCore/en/2675/changelog.html
***
*** …
=> Increase version for v2.12.0rc2 and update changelog 

.github/workflows/install-from-source.yml, environment.yml, pyproject.toml
Serious issue via `fire`, see issue.
Closes #2680 
EDIT: ipython released 9.0.1 so we need to pin <9 since `fire` have not fixed it yet
***
***
=> Pin ipython<9.0

esmvalcore/cmor/_fixes/icon/icon_xpp.py, esmvalcore/config/extra_facets/icon-mappings.yml, tests/integration/cmor/_fixes/icon/test_icon_xpp.py
Adding LAI and GPP to variables for ICON XPP. 
More details see #2695
=> [NOT FOR CHANGELOG; PR NOT IN MAIN] adding lai and gpp to icon xpp

.github/workflows/run-tests.yml, environment.yml, pyproject.toml
API issues with the brand new dask==2025.4.0
Contributes to avoiding #2716 without a permanent solution, though
***
***
=> Temporary pin dask `!=2025.4.0`

.github/workflows/install-from-conda.yml, .github/workflows/install-from-condalock-file.yml, .github/workflows/install-from-pypi.yml, .github/workflows/install-from-source.yml, .github/workflows/run-tests-monitor.yml, .github/workflows/run-tests.yml, environment.yml, pyproject.toml
As recommended by #2533.
#2726 is contingent on us not supporting Python 3.10 anymore
***
***
=> Remove support for  python 3.10

esmvalcore/cmor/_fixes/cmip6/cesm2.py, esmvalcore/cmor/_fixes/cmip6/cesm2_waccm.py, esmvalcore/local.py, tests/integration/cmor/_fixes/test_data/create_test_data.py
=> Always context managers when handling `netCDF4.Dataset` objects

esmvalcore/cmor/tables/custom/CMOR_dpn2o.dat, esmvalcore/cmor/tables/custom/CMOR_n2oflux.dat
This PR adds new CMOR tables for
- `dpn2o`: Surface Nitrous Oxide (N2O) Partial Pressure Difference between Sea Water and Air
- `n2oflux`: Surface Upward Ocean to Atmosphere Mole Flux of Nitrous Oxide (N2O)
***
*** …
=> Added custom CMOR tables for `dpn2o` and `n2oflux`

README.md
=> fix Codecov badge in README

.pre-commit-config.yaml, doc/develop/derivation.rst, doc/quickstart/configure.rst, doc/recipe/preprocessor.rst, esmvalcore/_recipe/check.py, esmvalcore/_recipe/recipe.py, esmvalcore/_recipe/to_datasets.py, esmvalcore/cmor/_fixes/icon/_base_fixes.py, esmvalcore/dataset.py, esmvalcore/exceptions.py, esmvalcore/local.py, esmvalcore/preprocessor/__init__.py, esmvalcore/preprocessor/_compare_with_refs.py, esmvalcore/preprocessor/_derive/__init__.py, esmvalcore/preprocessor/_derive/_baseclass.py, esmvalcore/preprocessor/_derive/ohc.py, esmvalcore/preprocessor/_derive/qep.py, esmvalcore/preprocessor/_derive/vegfrac.py, esmvalcore/preprocessor/_regrid.py, esmvalcore/preprocessor/_volume.py, esmvalcore/typing.py, tests/integration/preprocessor/_derive/test_interface.py, tests/integration/recipe/test_recipe.py, tests/integration/test_local.py, tests/unit/local/test_select_files.py, tests/unit/preprocessor/_derive/test_vegfrac.py, tests/unit/preprocessor/_multimodel/test_multimodel.py, tests/unit/preprocessor/test_preprocessor_file.py, tests/unit/recipe/test_recipe.py, tests/unit/test_dataset.py
While working on https://github.com/ESMValGroup/ESMValCore/issues/2769, I made lots of trivial changes to the code (like adding type hints and removing unnecessary line breaks when raising exceptions). Since the implementation of https://github.com/ESMValGroup/ESMValCore/issues/2769 also turned out to be much more complex than expected, I thought it's a good idea to split that into multiple PRs.
This first PR implements all these trivial changes. There's **no** change in functionality. Here's an overview:
- Added type hints
- Remove unnecessary line breaks when raising exceptions
- Added the private methods `_is_derived` and `_derivation_necessary` to `Dataset`, but these are **not** used yet
- Cleaned the doc on variable derivation
Related to …
=> In modules relevant for variable derivation: cleaned code, doc, and added type hints

.github/dependabot.yml
Let [dependabot automatically open pull requests to update GitHub Actions](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates).
***
***
- 🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValCore/pulls) …
=> Automatically open pull requests to update GitHub Actions

.github/workflows/build-and-deploy-on-pypi.yml
Sister PR to Tool's https://github.com/ESMValGroup/ESMValTool/pull/4151
***
***
=> use finer current version for pypa PyPI upload github action

esmvalcore/_main.py, esmvalcore/cmor/table.py, esmvalcore/esgf/facets.py, esmvalcore/exceptions.py, pyproject.toml
Enable ruff rule that prevents `print` statements
Part of https://github.com/ESMValGroup/ESMValCore/issues/2528
***
***
=> Enable ruff rule to prevent print statements

esmvalcore/_recipe/check.py, esmvalcore/_task.py, esmvalcore/config/_diagnostics.py, esmvalcore/dataset.py, esmvalcore/preprocessor/__init__.py, pyproject.toml, tests/unit/config/test_config.py, tests/unit/recipe/test_recipe.py
Enable ruff rule that enforces using items() to iterate over dict key/value pairs
Part of https://github.com/ESMValGroup/ESMValCore/issues/2528
***
***
=> Enable ruff rule that enforces using items() to iterate over dict key/value pairs

esmvalcore/cmor/_fixes/cmip5/bnu_esm.py, esmvalcore/cmor/_fixes/cmip5/miroc5.py, esmvalcore/cmor/_fixes/cmip5/miroc_esm_chem.py, esmvalcore/cmor/_fixes/cmip6/cesm2.py, esmvalcore/cmor/_fixes/common.py, esmvalcore/config/_config_object.py, esmvalcore/config/_esgf_pyclient.py, esmvalcore/preprocessor/_area.py, esmvalcore/preprocessor/_compare_with_refs.py, esmvalcore/preprocessor/_io.py, esmvalcore/preprocessor/_mask.py, esmvalcore/preprocessor/_other.py, esmvalcore/preprocessor/_regrid_esmpy.py, esmvalcore/preprocessor/_volume.py, pyproject.toml, tests/integration/cmor/_fixes/cesm/test_cesm2.py, tests/integration/cmor/_fixes/emac/test_emac.py, tests/integration/cmor/_fixes/icon/test_icon.py, tests/integration/cmor/_fixes/icon/test_icon_xpp.py, tests/integration/cmor/_fixes/native6/test_mswep.py, tests/integration/conftest.py, tests/integration/test_diagnostic_run.py, tests/unit/config/test_esgf_pyclient.py, tests/unit/preprocessor/_mask/test_mask.py, tests/unit/preprocessor/_multimodel/test_multimodel.py, tests/unit/preprocessor/_regrid/test_extract_regional_grid.py
Enable the ruff rule that checks for commented out code and remove any commented out code/reformat text so it does not look like commented out code.
Part of #2528
***
***
=> Enable ruff rule that checks for commented out code

README.md, doc/contributing.rst
Now that we have replaced Codacy by pre-commit.ci in #2818, we no longer need the Codacy badge.
***
***
=> Remove codacy badge

.circleci/config.yml, .github/workflows/create-condalock-file.yml, .github/workflows/install-from-condalock-file.yml, .github/workflows/install-from-pypi.yml, .github/workflows/install-from-source.yml, .github/workflows/run-tests-monitor.yml, .github/workflows/run-tests.yml, doc/quickstart/install.rst, environment.yml
Use `pip install --no-deps` to avoid overwiting packages from the conda environment
Issue https://github.com/ESMValGroup/ESMValTool/issues/2735
***
***
=> Use ``pip install --no-deps`` to avoid overwiting packages from the conda environment
